function sGd(){}
function mGd(){}
function N2e(){}
function S2e(){}
function X2e(){}
function b3e(){}
function h3e(){}
function k3e(b){this.b=b}
function j3e(b){rJb(b.b,null)}
function d3e(b,c){this.b=b;this.c=c}
function Rdg(b){MJb(new Q2e(b.b.p,b.b.p.Ul(),b.b.b))}
function rGd(){var b;while(nGd){b=nGd;nGd=nGd.c;!nGd&&(oGd=null);Rdg(b.b)}}
function $2e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function U2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function uGd(){pGd=new sGd;yJc((vJc(),uJc),5);!!$stats&&$stats(nKc(Qxi,Abh,-1,-1));pGd.dl();!!$stats&&$stats(nKc(Qxi,$fh,-1,-1))}
function Z2e(b){var c,d;rJb(b.b,null);b.c.Xl(MIe(KLh,KLh));c=BJe();d=new d3e(b.c,b.e);b.d?cKe(c,b.g,d):$Ke(c,b.g,S1c(vZb(b.i),1),d)}
function P2e(b,c){var d;c>1?(d=NIe(Txi,Uxi,D1c(jCd,{113:1,175:1,177:1,323:1},1,[SJg+c]))):S1c(NW(S1c(b.k.ll(0),150),tih),174).Sd(dth)?(d=NIe(Vxi,Wxi,D1c(jCd,{113:1,175:1,177:1,323:1},1,[S1c(NW(b.s,jSg),1)]))):(d=NIe(vQh,wQh,D1c(jCd,{113:1,175:1,177:1,323:1},1,[S1c(NW(b.s,jSg),1)])));return d}
function $Ke(c,d,e,g){var b,j,k,n,o;n=new nUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Yfh,evtGroup:n.b,method:Rxi,millis:(new Date).getTime(),type:Abh});o=DSd(c);try{vSd(o.b,SJg+LRd(o,Akh));vSd(o.b,SJg+LRd(o,Sxi));vSd(o.b,EPg);vSd(o.b,SJg+LRd(o,Kkh));vSd(o.b,SJg+LRd(o,ljh));RRd(o,d);vSd(o.b,SJg+LRd(o,e));k=sSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Yfh,evtGroup:n.b,method:Rxi,millis:(new Date).getTime(),type:njh});ESd(c,(bTd(),aTd),Rxi,n,k,g)}catch(b){b=oDd(b);if(V1c(b,313)){j=b;Fle(g,j)}else throw b}}
function Q2e(b,c,d){m7();var e,g,i,j,k,n,o,p,q,r,s,t;OJb.call(this);_9(this,650,500);eLb(this.ub,Xxi);!!this.E&&RQ(GQ(this.E,p0g),Xxi);KJb(this,false);this.b=new E8b;eLb(this.b.ub,MIe(iCh,iCh));this.b.xb=false;t8(this.b,false);C8(this.b,Yxi);Vzb(this.b,new Ztc(0));_9(this.b,650,500);t=new FMb;FAb(this.b,t);p=new yWd;q=new yWd;for(n=c.k.Ud();n.$d();){k=S1c(n._d(),150);F1c(p.d,p.e++,k);hWd(q,S1c(NW(k,Whh),1))}i=new KBb;Vzb(i,new Rrc);i.hc=0;i.Jc&&HQ(DR(J7(i),TOg),false);i.xb=false;this.c=I8e(p);_9(this.c,650,200);FAb(i,this.c);FAb(this.b,i);s=new qdc;_9(s,620,100);if(!d){FAb(this.b,new GMb(Zxi+MIe(UQh,VQh)+$xi));FAb(this.b,s)}j=p.e;kZ(this.c.I.g,new U2e(this,c,j,i,s,d,t));if(d){o=MIe(xQh,_xi);FAb(this.b,new GMb(o));dLb(this.ub,(BRe(),zRe(),wRe))}r=new wIb(MIe($Nh,$Nh),new $2e(this,b,d,q,s,p));g=new wIb(MIe(_Nh,_Nh),new k3e(this));e=new yYb;e.E=(RJ(),OJ);hYb(e,r,e.Hb.e);hYb(e,g,e.Hb.e);FAb(this.b,e);DBb(this,e);this.uh(this.b,this.Hb.e)}
var fyi='620',gyi='70%',$xi=': <br />',Zxi='<br />',ayi='<br /><br />',_xi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',hyi='AsyncLoader5',iyi='DeleteItemWindow',jyi='DeleteItemWindow$1',kyi='DeleteItemWindow$2',lyi='DeleteItemWindow$2$1',myi='DeleteItemWindow$3',Wxi='Do you really want to remove the selected PAGE {0}?',Uxi='Do you really want to remove the {0} selected resources?',Xxi='Informations',Rxi='JahiaContentManagementService_Proxy.markForDeletion',Yxi='JahiaGxtDeleteItem',eyi='This node is still used by:',cyi='Those nodes are still used in:',Sxi='markForDeletion',Txi='message.remove.multiple.confirm',byi='message.remove.multiple.usage',Vxi='message.remove.single.page.confirm',dyi='message.remove.single.usage',Qxi='runCallbacks5';_=sGd.prototype=mGd.prototype=new IH;_.gC=function tGd(){return $ed};_.dl=function xGd(){rGd()};_.cM={};_=Q2e.prototype=N2e.prototype=new fJb;_.gC=function R2e(){return Wmd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=U2e.prototype=S2e.prototype=new cib;_.gC=function V2e(){return Smd};_.cg=function W2e(b){var c,d,e;c=S1c(b.d,174);d=c.Nd();e=P2e(this.d,this.e);if(d>0){e+=ayi+(this.e>1?MIe(byi,cyi):MIe(dyi,eyi))}else{RAb(this.b.b,this.c);aab(this.i,fyi,gyi);if(this.g){_9(this.b,-1,130);_9(this.b.b,-1,130)}}EMb(this.j,e);Kzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=$2e.prototype=X2e.prototype=new njb;_.ig=function _2e(b){Z2e(this,S1c(b,216))};_.gC=function a3e(){return Umd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=d3e.prototype=b3e.prototype=new Cle;_.gC=function e3e(){return Tmd};_.Ll=function f3e(b){this.b.Wl();b.ok();BQb(MIe(Ath,Bth),b.ok())};_.ye=function g3e(b){var c;this.b.Wl();c=null;V1c(this.b,354)?(c=S1c(this.b,354).d.u):V1c(this.b,355)&&(c=S1c(this.b,355));if(!!c&&pWd(this.c,S1c(NW(c.q.j,Whh),1),0)!=-1){this.b.Yl(2);this.b.Zl(null)}else{this.b.Yl(63);this.b.Zl(null)}};_.cM={};_.b=null;_.c=null;_=k3e.prototype=h3e.prototype=new njb;_.ig=function l3e(b){j3e(this,S1c(b,216))};_.gC=function m3e(){return Vmd};_.cM={188:1};_.b=null;var $ed=r6d(R3h,hyi),Wmd=r6d(Zbi,iyi),Smd=r6d(Zbi,jyi),Umd=r6d(Zbi,kyi),Tmd=r6d(Zbi,lyi),Vmd=r6d(Zbi,myi);$entry(uGd)();