function zGd(){}
function tGd(){}
function i3e(){}
function n3e(){}
function s3e(){}
function y3e(){}
function E3e(){}
function H3e(b){this.b=b}
function G3e(b){uJb(b.b,null)}
function A3e(b,c){this.b=b;this.c=c}
function meg(b){PJb(new l3e(b.b.p,b.b.p._l(),b.b.b))}
function yGd(){var b;while(uGd){b=uGd;uGd=uGd.c;!uGd&&(vGd=null);meg(b.b)}}
function v3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function p3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function BGd(){wGd=new zGd;AJc((xJc(),wJc),5);!!$stats&&$stats(pKc(Jzi,Vbh,-1,-1));wGd.kl();!!$stats&&$stats(pKc(Jzi,Ohh,-1,-1))}
function u3e(b){var c,d;uJb(b.b,null);b.c.cm(hJe(zNh,zNh));c=YJe();d=new A3e(b.c,b.e);b.d?zKe(c,b.g,d):vLe(c,b.g,Z1c(yZb(b.i),1),d)}
function k3e(b,c){var d;c>1?(d=iJe(Mzi,Nzi,K1c(qCd,{113:1,175:1,177:1,323:1},1,[nKg+c]))):Z1c(RW(Z1c(b.k.sl(0),150),hkh),174).Sd(Tuh)?(d=iJe(Ozi,Pzi,K1c(qCd,{113:1,175:1,177:1,323:1},1,[Z1c(RW(b.s,JSg),1)]))):(d=iJe(mSh,nSh,K1c(qCd,{113:1,175:1,177:1,323:1},1,[Z1c(RW(b.s,JSg),1)])));return d}
function vLe(c,d,e,g){var b,j,k,n,o;n=new GUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Mhh,evtGroup:n.b,method:Kzi,millis:(new Date).getTime(),type:Vbh});o=WSd(c);try{OSd(o.b,nKg+cSd(o,omh));OSd(o.b,nKg+cSd(o,Lzi));OSd(o.b,aQg);OSd(o.b,nKg+cSd(o,ymh));OSd(o.b,nKg+cSd(o,_kh));iSd(o,d);OSd(o.b,nKg+cSd(o,e));k=LSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Mhh,evtGroup:n.b,method:Kzi,millis:(new Date).getTime(),type:blh});XSd(c,(uTd(),tTd),Kzi,n,k,g)}catch(b){b=vDd(b);if(a2c(b,313)){j=b;ame(g,j)}else throw b}}
function l3e(b,c,d){q7();var e,g,i,j,k,n,o,p,q,r,s,t;RJb.call(this);dab(this,650,500);hLb(this.ub,Qzi);!!this.E&&RQ(GQ(this.E,H0g),Qzi);NJb(this,false);this.b=new H8b;hLb(this.b.ub,hJe($Dh,$Dh));this.b.xb=false;x8(this.b,false);G8(this.b,Rzi);Yzb(this.b,new auc(0));dab(this.b,650,500);t=new IMb;IAb(this.b,t);p=new RWd;q=new RWd;for(n=c.k.Ud();n.$d();){k=Z1c(n._d(),150);M1c(p.d,p.e++,k);AWd(q,Z1c(RW(k,Kjh),1))}i=new NBb;Yzb(i,new Urc);i.hc=0;i.Jc&&HQ(DR(N7(i),qPg),false);i.xb=false;this.c=d9e(p);dab(this.c,650,200);IAb(i,this.c);IAb(this.b,i);s=new tdc;dab(s,620,100);if(!d){IAb(this.b,new JMb(Szi+hJe(LSh,MSh)+Tzi));IAb(this.b,s)}j=p.e;oZ(this.c.I.g,new p3e(this,c,j,i,s,d,t));if(d){o=hJe(oSh,Uzi);IAb(this.b,new JMb(o));gLb(this.ub,(YRe(),WRe(),TRe))}r=new zIb(hJe(PPh,PPh),new v3e(this,b,d,q,s,p));g=new zIb(hJe(RPh,RPh),new H3e(this));e=new BYb;e.E=(RJ(),OJ);kYb(e,r,e.Hb.e);kYb(e,g,e.Hb.e);IAb(this.b,e);GBb(this,e);this.uh(this.b,this.Hb.e)}
var $zi='620',_zi='70%',Tzi=': <br />',Szi='<br />',Vzi='<br /><br />',Uzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',aAi='AsyncLoader5',bAi='DeleteItemWindow',cAi='DeleteItemWindow$1',dAi='DeleteItemWindow$2',eAi='DeleteItemWindow$2$1',fAi='DeleteItemWindow$3',Pzi='Do you really want to remove the selected PAGE {0}?',Nzi='Do you really want to remove the {0} selected resources?',Qzi='Informations',Kzi='JahiaContentManagementService_Proxy.markForDeletion',Rzi='JahiaGxtDeleteItem',Zzi='This node is still used by:',Xzi='Those nodes are still used in:',Lzi='markForDeletion',Mzi='message.remove.multiple.confirm',Wzi='message.remove.multiple.usage',Ozi='message.remove.single.page.confirm',Yzi='message.remove.single.usage',Jzi='runCallbacks5';_=zGd.prototype=tGd.prototype=new IH;_.gC=function AGd(){return dfd};_.kl=function EGd(){yGd()};_.cM={};_=l3e.prototype=i3e.prototype=new iJb;_.gC=function m3e(){return bnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=p3e.prototype=n3e.prototype=new gib;_.gC=function q3e(){return Zmd};_.cg=function r3e(b){var c,d,e;c=Z1c(b.d,174);d=c.Nd();e=k3e(this.d,this.e);if(d>0){e+=Vzi+(this.e>1?hJe(Wzi,Xzi):hJe(Yzi,Zzi))}else{UAb(this.b.b,this.c);eab(this.i,$zi,_zi);if(this.g){dab(this.b,-1,130);dab(this.b.b,-1,130)}}HMb(this.j,e);Nzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=v3e.prototype=s3e.prototype=new rjb;_.ig=function w3e(b){u3e(this,Z1c(b,216))};_.gC=function x3e(){return _md};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=A3e.prototype=y3e.prototype=new Zle;_.gC=function B3e(){return $md};_.Sl=function C3e(b){this.b.bm();b.ok();EQb(hJe(ovh,pvh),b.ok())};_.ye=function D3e(b){var c;this.b.bm();c=null;a2c(this.b,354)?(c=Z1c(this.b,354).d.u):a2c(this.b,355)&&(c=Z1c(this.b,355));if(!!c&&IWd(this.c,Z1c(RW(c.q.j,Kjh),1),0)!=-1){this.b.dm(2);this.b.em(null)}else{this.b.dm(63);this.b.em(null)}};_.cM={};_.b=null;_.c=null;_=H3e.prototype=E3e.prototype=new rjb;_.ig=function I3e(b){G3e(this,Z1c(b,216))};_.gC=function J3e(){return and};_.cM={188:1};_.b=null;var dfd=O6d(G5h,aAi),bnd=O6d(Qdi,bAi),Zmd=O6d(Qdi,cAi),_md=O6d(Qdi,dAi),$md=O6d(Qdi,eAi),and=O6d(Qdi,fAi);$entry(BGd)();