function vXc(){}
function sXc(){}
function zOd(){}
function tOd(){}
function oif(){}
function wif(){}
function uif(){}
function yif(){}
function Eif(){}
function Kif(){}
function Bif(b){this.b=b}
function Aif(b){oLb(b.b,null)}
function nce(b,c){b.b.Co(b,c)}
function q9f(b){JLb(new sif(b.b.p,b.b.p.o.s))}
function uXc(){uXc=cBg;tXc=new zWc(rqh,new vXc)}
function oce(){kce();this.b=new Qce(this);wSd();this.ad[rJg]=jsh}
function yOd(){var b;while(uOd){b=uOd;uOd=uOd.c;!uOd&&(vOd=null);q9f(b.b)}}
function qif(b,c,d,e,g,i,j,k){MXe(mXe(),c,d,e,g,i,j,k,new Mif(b,c,d,e,g,i,j))}
function Mif(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function Hif(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function BOd(){wOd=new zOd;KKc((HKc(),GKc),4);!!$stats&&$stats(zLc(YDi,x9g,-1,-1));wOd.Un();!!$stats&&$stats(zLc(YDi,zrh,-1,-1))}
function rif(){$wnd.jQuery(_Di).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(aEi).val(b.x);$wnd.jQuery(bEi).val(b.y);$wnd.jQuery(cEi).val(b.w);$wnd.jQuery(dEi).val(b.h)}})}
function Gif(b){dbd(j_b(b.j),119).Ko()>0&&dbd(j_b(b.c),119).Ko()>0&&qif(b.b,dbd(ZV(b.e,Mth),1),dbd(b.g.ce(),1),dbd(j_b(b.i),119).Ko(),dbd(j_b(b.d),119).Ko(),dbd(j_b(b.j),119).Ko(),dbd(j_b(b.c),119).Ko(),false)}
function MXe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new w4d;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xrh,evtGroup:r.b,method:ZDi,millis:(new Date).getTime(),type:x9g});s=M2d(c);try{E2d(s.b,UGg+U1d(s,qwh));E2d(s.b,UGg+U1d(s,$Di));E2d(s.b,Mwh);E2d(s.b,UGg+U1d(s,bvh));E2d(s.b,UGg+U1d(s,bvh));E2d(s.b,UGg+U1d(s,cvh));E2d(s.b,UGg+U1d(s,cvh));E2d(s.b,UGg+U1d(s,cvh));E2d(s.b,UGg+U1d(s,cvh));E2d(s.b,UGg+U1d(s,Hwh));E2d(s.b,UGg+U1d(s,d));E2d(s.b,UGg+U1d(s,e));E2d(s.b,UGg+g);E2d(s.b,UGg+i);E2d(s.b,UGg+j);E2d(s.b,UGg+k);E2d(s.b,n?vLg:hKg);q=B2d(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xrh,evtGroup:r.b,method:ZDi,millis:(new Date).getTime(),type:dvh});N2d(c,(k3d(),j3d),ZDi,r,q,o)}catch(b){b=QLd(b);if(!hbd(b,313))throw b}}
function sif(b,c){r6();var d,e,g,i,j,k,n,o,p,q,r,s;LLb.call(this);VBb(this,new ntc);a9(this,712,550);this.b=b;CLb(this,xWe(eEi,eEi));this.Ac=fEi;!!this.sc&&(N6(this).id=fEi,undefined);j=new uac;j.tb=false;j.xb=false;j.hc=0;j.Jc&&IP(EQ(N6(j),SLg),false);p=new C2b;p.Ij(gEi);i=dbd(ZV(c,CRg),1).lastIndexOf(iKg);if(i>0){g=Hme(dbd(ZV(c,CRg),1),i);p.Lj(Eme(dbd(ZV(c,CRg),1),g,hEi+g))}else{p.Lj(dbd(ZV(c,CRg),1)+hEi)}C_b(p,xWe(OHh,OHh));HCb(j,p,j.Hb.e);r=new Zcc;E_b(r,KHg);r.Ac=KHg;!!r.sc&&(N6(r).id=KHg,undefined);W6(r);HCb(j,r,j.Hb.e);o=new Zcc;E_b(o,JHg);o.Ac=JHg;!!o.sc&&(N6(o).id=JHg,undefined);W6(o);HCb(j,o,j.Hb.e);s=new Zcc;C_b(s,xWe(iEi,pLh));J7(s,jEi);E_b(s,YHg);s.Ac=YHg;!!s.sc&&(N6(s).id=YHg,undefined);P7(s);B6(s);HCb(j,s,j.Hb.e);k=new Zcc;C_b(k,xWe(kEi,uLh));J7(k,lEi);E_b(k,XHg);k.Ac=XHg;!!k.sc&&(N6(k).id=XHg,undefined);P7(k);B6(k);HCb(j,k,j.Hb.e);n=new oce;T5(n,new wif,(uXc(),uXc(),tXc));n.ad.id=mEi;nce(n,c.A);HCb(j,n,j.Hb.e);d=new m$b;e=new tKb(xWe($Gh,$Gh),new Bif(this));q=new tKb(xWe(iHh,iHh),new Hif(this,s,k,c,p,r,o));XZb(d,q,d.Hb.e);XZb(d,e,d.Hb.e);BDb(this,(PI(),MI));ADb(this,d);IBb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var _Di='#cropbox',dEi='#height-input',aEi='#left-input',bEi='#top-input',cEi='#width-input',oEi='AsyncLoader4',pEi='ImageCrop',qEi='ImageCrop$1',rEi='ImageCrop$2',sEi='ImageCrop$3',tEi='ImageCrop$4',ZDi='JahiaContentManagementService_Proxy.cropImage',fEi='JahiaGxtImageCrop',hEi='_crop',$Di='cropImage',mEi='cropbox',nEi='failure.crop.label',eEi='label.crop',kEi='label.height',iEi='label.width',YDi='runCallbacks4',lEi='stylehight',jEi='stylewidth';_=vXc.prototype=sXc.prototype=new GVc;_.jm=function wXc(b){dbd(b,288);rif()};_.mm=function xXc(){return tXc};_.gC=function yXc(){return lnd};_.cM={};var tXc;_=zOd.prototype=tOd.prototype=new FG;_.gC=function AOd(){return God};_.Un=function EOd(){yOd()};_.cM={};_=oce.prototype=jce.prototype;_=uce.prototype;_.Co=function Gce(b,c){b.b=new Qce(b);b.b.Co(b,c)};_=Mce.prototype;_.Co=function Vce(b,c){!!b.b&&(b.b.Ao(b)[ksh]=UGg,undefined);(KPc(),JPc).em(b.ad,c)};_=sif.prototype=oif.prototype=new cLb;_.gC=function tif(){return Kxd};_.cM={4:1,5:1,9:1,18:1,19:1,25:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_=wif.prototype=uif.prototype=new FG;_.gC=function xif(){return Gxd};_.cM={288:1,292:1};_=Bif.prototype=yif.prototype=new Zhb;_.jg=function Cif(b){Aif(this,dbd(b,216))};_.gC=function Dif(){return Hxd};_.cM={188:1};_.b=null;_=Hif.prototype=Eif.prototype=new Zhb;_.jg=function Iif(b){Gif(this,dbd(b,216))};_.gC=function Jif(){return Ixd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=Mif.prototype=Kif.prototype=new Jze;_.gC=function Nif(){return Jxd};_.Vo=function Oif(b){if(b!=null&&b.cM&&!!b.cM[352]){(HTd(),$wnd.confirm(xWe(_Jh,_Jh)+f8g+xWe(wXh,wXh)))&&qif(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{HTd();$wnd.alert(xWe(nEi,nEi)+f8g+b.sl());xWe(nEi,nEi)}};_.Ce=function Pif(b){oLb(this.b,null);$kf(this.b.b,1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var lnd=Aje(sai,S$h),God=Aje(Vbi,oEi),Kxd=Aje(Dki,pEi),Gxd=Aje(Dki,qEi),Hxd=Aje(Dki,rEi),Ixd=Aje(Dki,sEi),Jxd=Aje(Dki,tEi);$entry(BOd)();