function UOd(){}
function OOd(){}
function Ogf(){}
function ygf(){}
function Dgf(){}
function Igf(){}
function Ugf(){}
function Qgf(b){this.b=b}
function Xgf(b){this.b=b}
function Wgf(b){oLb(b.b,null)}
function bbg(b){JLb(new Bgf(b.b.p,b.b.p.o,b.b.b))}
function Lgf(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function Fgf(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function TOd(){var b;while(POd){b=POd;POd=POd.c;!POd&&(QOd=null);bbg(b.b)}}
function Kgf(b){var c,d;oLb(b.b,null);xWe(WSh,WSh);c=mXe();d=new Qgf(b.c);b.d?PXe(c,b.e,d):GYe(c,b.e,dbd(j_b(b.g),1),d)}
function WOd(){ROd=new UOd;KKc((HKc(),GKc),5);!!$stats&&$stats(zLc(uEi,x9g,-1,-1));ROd.Un();!!$stats&&$stats(zLc(uEi,zrh,-1,-1))}
function Agf(b,c){var d;c>1?(d=yWe(xEi,yEi,Qad(sKd,{113:1,175:1,177:1,322:1},1,[UGg+c]))):dbd(ZV(dbd(b.k.no(0),150),juh),174).Sd(GEh)?(d=yWe(zEi,AEi,Qad(sKd,{113:1,175:1,177:1,322:1},1,[dbd(ZV(b.s,CRg),1)]))):(d=yWe(SXh,TXh,Qad(sKd,{113:1,175:1,177:1,322:1},1,[dbd(ZV(b.s,CRg),1)])));return d}
function GYe(c,d,e,g){var b,j,k,n,o;n=new w4d;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xrh,evtGroup:n.b,method:vEi,millis:(new Date).getTime(),type:x9g});o=M2d(c);try{E2d(o.b,UGg+U1d(o,qwh));E2d(o.b,UGg+U1d(o,wEi));E2d(o.b,BMg);E2d(o.b,UGg+U1d(o,Awh));E2d(o.b,UGg+U1d(o,bvh));$1d(o,d);E2d(o.b,UGg+U1d(o,e));k=B2d(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xrh,evtGroup:n.b,method:vEi,millis:(new Date).getTime(),type:dvh});N2d(c,(k3d(),j3d),vEi,n,k,g)}catch(b){b=QLd(b);if(hbd(b,313)){j=b;Mze(g,j)}else throw b}}
function Bgf(b,c,d){r6();var e,g,i,j,k,n,o,p,q,r,s,t;LLb.call(this);a9(this,650,500);_Mb(this.ub,BEi);!!this.E&&SP(HP(this.E,O$g),BEi);HLb(this,false);this.b=new uac;_Mb(this.b.ub,xWe(SNh,SNh));this.b.xb=false;x7(this.b,false);F7(this.b,CEi);VBb(this.b,new Kvc(0));a9(this.b,650,500);t=new yOb;CCb(this.b,t);p=new I6d;q=new I6d;for(n=c.k.Ud();n.$d();){k=dbd(n._d(),150);Sad(p.d,p.e++,k);r6d(q,dbd(ZV(k,Mth),1))}i=new HDb;VBb(i,new ntc);i.hc=0;i.Jc&&IP(EQ(N6(i),SLg),false);i.xb=false;this.c=kmf(p);a9(this.c,650,200);CCb(i,this.c);CCb(this.b,i);s=new gfc;a9(s,620,100);if(!d){CCb(this.b,new zOb(DEi+xWe(sYh,tYh)+EEi));CCb(this.b,s)}j=p.e;wY(this.c.I.g,new Fgf(this,c,j,i,s,d,t));if(d){o=xWe(UXh,FEi);CCb(this.b,new zOb(o));$Mb(this.ub,(Y2e(),W2e(),T2e))}r=new tKb(xWe(tVh,tVh),new Lgf(this,b,d,q,s));g=new tKb(xWe(uVh,uVh),new Xgf(this));e=new m$b;e.E=(PI(),MI);XZb(e,r,e.Hb.e);XZb(e,g,e.Hb.e);CCb(this.b,e);ADb(this,e);this.Ei(this.b,this.Hb.e)}
var LEi='620',MEi='70%',EEi=': <br />',DEi='<br />',GEi='<br /><br />',FEi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',NEi='AsyncLoader5',OEi='DeleteItemWindow',PEi='DeleteItemWindow$1',QEi='DeleteItemWindow$2',REi='DeleteItemWindow$2$1',SEi='DeleteItemWindow$3',AEi='Do you really want to remove the selected PAGE {0}?',yEi='Do you really want to remove the {0} selected resources?',BEi='Informations',vEi='JahiaContentManagementService_Proxy.markForDeletion',CEi='JahiaGxtDeleteItem',KEi='This node is still used by:',IEi='Those nodes are still used in:',wEi='markForDeletion',xEi='message.remove.multiple.confirm',HEi='message.remove.multiple.usage',zEi='message.remove.single.page.confirm',JEi='message.remove.single.usage',uEi='runCallbacks5';_=UOd.prototype=OOd.prototype=new FG;_.gC=function VOd(){return Jod};_.Un=function ZOd(){TOd()};_.cM={};_=Bgf.prototype=ygf.prototype=new cLb;_.gC=function Cgf(){return txd};_.cM={4:1,5:1,9:1,18:1,19:1,25:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=Fgf.prototype=Dgf.prototype=new Vgb;_.gC=function Ggf(){return pxd};_.eg=function Hgf(b){var c,d,e;c=dbd(b.d,174);d=c.Nd();e=Agf(this.d,this.e);if(d>0){e+=GEi+(this.e>1?xWe(HEi,IEi):xWe(JEi,KEi))}else{OCb(this.b.b,this.c);b9(this.i,LEi,MEi);if(this.g){a9(this.b,-1,130);a9(this.b.b,-1,130)}}xOb(this.j,e);KBb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=Lgf.prototype=Igf.prototype=new Zhb;_.jg=function Mgf(b){Kgf(this,dbd(b,216))};_.gC=function Ngf(){return rxd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=Qgf.prototype=Ogf.prototype=new Jze;_.gC=function Rgf(){return qxd};_.Vo=function Sgf(b){b.sl();pSb(xWe(bFh,cFh),b.sl())};_.Ce=function Tgf(b){$kf(this.b,63);clf(this.b)};_.cM={};_.b=null;_=Xgf.prototype=Ugf.prototype=new Zhb;_.jg=function Ygf(b){Wgf(this,dbd(b,216))};_.gC=function Zgf(){return sxd};_.cM={188:1};_.b=null;var Jod=Aje(Vbi,NEi),txd=Aje(Dki,OEi),pxd=Aje(Dki,PEi),rxd=Aje(Dki,QEi),qxd=Aje(Dki,REi),sxd=Aje(Dki,SEi);$entry(WOd)();