function ePc(){}
function bPc(){}
function $Ad(){}
function UAd(){}
function h1e(){}
function p1e(){}
function n1e(){}
function r1e(){}
function x1e(){}
function D1e(){}
function u1e(b){this.b=b}
function t1e(b){UGb(b.b,null)}
function $Wd(b,c){b.b.ul(b,c)}
function FUf(b){nHb(new l1e(b.b.p,b.b.p.p.s))}
function dPc(){dPc=ykg;cPc=new iOc(uZg,new ePc)}
function _Wd(){XWd();this.b=new AXd(this);this.ad[Vsg]=U$g}
function ZAd(){var b;while(VAd){b=VAd;VAd=VAd.c;!VAd&&(WAd=null);FUf(b.b)}}
function j1e(b,c,d,e,g,i,j,k){bFe(DEe(),c,d,e,g,i,j,k,new F1e(b,c,d,e,g,i,j))}
function F1e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function A1e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function aBd(){XAd=new $Ad;HGc((EGc(),DGc),4);!!$stats&&$stats(wHc(Y9h,EUg,-1,-1));XAd.al();!!$stats&&$stats(wHc(Y9h,g$g,-1,-1))}
function k1e(){$wnd.jQuery(_9h).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(aai).val(b.x);$wnd.jQuery(bai).val(b.y);$wnd.jQuery(cai).val(b.w);$wnd.jQuery(dai).val(b.h)}})}
function z1e(b){U$c(iXb(b.j),119).wl()>0&&U$c(iXb(b.c),119).wl()>0&&j1e(b.b,U$c(WU(b.e,f0g),1),U$c(b.g.ce(),1),U$c(iXb(b.i),119).wl(),U$c(iXb(b.d),119).wl(),U$c(iXb(b.j),119).wl(),U$c(iXb(b.c),119).wl(),false)}
function bFe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new pPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:e$g,evtGroup:r.b,method:Z9h,millis:(new Date).getTime(),type:EUg});s=FNd(c);try{xNd(s.b,tqg+NMd(s,P2g));xNd(s.b,tqg+NMd(s,$9h));xNd(s.b,o3g);xNd(s.b,tqg+NMd(s,y1g));xNd(s.b,tqg+NMd(s,y1g));xNd(s.b,tqg+NMd(s,z1g));xNd(s.b,tqg+NMd(s,z1g));xNd(s.b,tqg+NMd(s,z1g));xNd(s.b,tqg+NMd(s,z1g));xNd(s.b,tqg+NMd(s,g3g));xNd(s.b,tqg+NMd(s,d));xNd(s.b,tqg+NMd(s,e));xNd(s.b,tqg+g);xNd(s.b,tqg+i);xNd(s.b,tqg+j);xNd(s.b,tqg+k);xNd(s.b,n?_ug:Ltg);q=uNd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:e$g,evtGroup:r.b,method:Z9h,millis:(new Date).getTime(),type:A1g});GNd(c,(dOd(),cOd),Z9h,r,q,o)}catch(b){b=pyd(b);if(!X$c(b,311))throw b}}
function l1e(b,c){n5();var d,e,g,i,j,k,n,o,p,q,r,s;pHb.call(this);zxb(this,new kpc);Y7(this,712,550);this.b=b;gHb(this,ODe(eai,eai));this.Ac=fai;!!this.sc&&(J5(this).id=fai,undefined);j=new r6b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&QO(MP(J5(j),vvg),false);p=new A$b;p.vi(gai);i=U$c(WU(c,Oyg),1).lastIndexOf(Mtg);if(i>0){g=H4d(U$c(WU(c,Oyg),1),i);p.yi(E4d(U$c(WU(c,Oyg),1),g,hai+g))}else{p.yi(U$c(WU(c,Oyg),1)+hai)}BXb(p,ODe(mfh,mfh));lyb(j,p,j.Hb.e);r=new W8b;DXb(r,nrg);r.Ac=nrg;!!r.sc&&(J5(r).id=nrg,undefined);S5(r);lyb(j,r,j.Hb.e);o=new W8b;DXb(o,mrg);o.Ac=mrg;!!o.sc&&(J5(o).id=mrg,undefined);S5(o);lyb(j,o,j.Hb.e);s=new W8b;BXb(s,ODe(iai,rjh));F6(s,jai);DXb(s,Brg);s.Ac=Brg;!!s.sc&&(J5(s).id=Brg,undefined);L6(s);x5(s);lyb(j,s,j.Hb.e);k=new W8b;BXb(k,ODe(kai,wjh));F6(k,lai);DXb(k,Arg);k.Ac=Arg;!!k.sc&&(J5(k).id=Arg,undefined);L6(k);x5(k);lyb(j,k,j.Hb.e);n=new _Wd;P4(n,new p1e,(dPc(),dPc(),cPc));n.ad.id=mai;$Wd(n,c.A);lyb(j,n,j.Hb.e);d=new lWb;e=new ZFb(ODe(Deh,Deh),new u1e(this));q=new ZFb(ODe(Neh,Neh),new A1e(this,s,k,c,p,r,o));WVb(d,q,d.Hb.e);WVb(d,e,d.Hb.e);fzb(this,(QH(),NH));ezb(this,d);mxb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var _9h='#cropbox',dai='#height-input',aai='#left-input',bai='#top-input',cai='#width-input',oai='AsyncLoader4',pai='ImageCrop',qai='ImageCrop$1',rai='ImageCrop$2',sai='ImageCrop$3',tai='ImageCrop$4',Z9h='JahiaContentManagementService_Proxy.cropImage',fai='JahiaGxtImageCrop',hai='_crop',$9h='cropImage',mai='cropbox',nai='failure.crop.label',eai='label.crop',kai='label.height',iai='label.width',Y9h='runCallbacks4',lai='stylehight',jai='stylewidth';_=ePc.prototype=bPc.prototype=new pNc;_.jk=function fPc(b){U$c(b,288);k1e()};_.mk=function gPc(){return cPc};_.gC=function hPc(){return Nad};_.cM={};var cPc;_=$Ad.prototype=UAd.prototype=new HF;_.gC=function _Ad(){return Vbd};_.al=function dBd(){ZAd()};_.cM={};_=_Wd.prototype=WWd.prototype;_=fXd.prototype;_.ul=function qXd(b,c){b.b=new AXd(b);b.b.ul(b,c)};_=wXd.prototype;_.ul=function FXd(b,c){!!b.b&&(b.b.sl(b)[V$g]=tqg,undefined);b.ad.src=c};_=l1e.prototype=h1e.prototype=new IGb;_.gC=function m1e(){return wkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_=p1e.prototype=n1e.prototype=new HF;_.gC=function q1e(){return skd};_.cM={288:1,292:1};_=u1e.prototype=r1e.prototype=new Vgb;_.fg=function v1e(b){t1e(this,U$c(b,216))};_.gC=function w1e(){return tkd};_.cM={188:1};_.b=null;_=A1e.prototype=x1e.prototype=new Vgb;_.fg=function B1e(b){z1e(this,U$c(b,216))};_.gC=function C1e(){return ukd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=F1e.prototype=D1e.prototype=new Lge;_.gC=function G1e(){return vkd};_.Hl=function H1e(b){if(b!=null&&b.cM&&!!b.cM[354]){$wnd.confirm(ODe(Bhh,Bhh)+mTg+ODe(Cyh,Cyh))&&j1e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(ODe(nai,nai)+mTg+b.fk());ODe(nai,nai)}};_.ye=function I1e(b){UGb(this.b,null);X3e(this.b.b,1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var Nad=A1d(DNh,$Bh),Vbd=A1d(SOh,oai),wkd=A1d(qXh,pai),skd=A1d(qXh,qai),tkd=A1d(qXh,rai),ukd=A1d(qXh,sai),vkd=A1d(qXh,tai);$entry(aBd)();