function tBd(){}
function nBd(){}
function r_e(){}
function w_e(){}
function B_e(){}
function H_e(){}
function N_e(){}
function J_e(b){this.b=b}
function Q_e(b){this.b=b}
function P_e(b){UGb(b.b,null)}
function qWf(b){nHb(new u_e(b.b.p,b.b.p.p,b.b.b))}
function E_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function y_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function sBd(){var b;while(oBd){b=oBd;oBd=oBd.c;!oBd&&(pBd=null);qWf(b.b)}}
function D_e(b){var c,d;UGb(b.b,null);T3e(b.c,ODe(duh,duh));c=DEe();d=new J_e(b.c);b.d?eFe(c,b.e,d):ZFe(c,b.e,U$c(iXb(b.g),1),d)}
function vBd(){qBd=new tBd;HGc((EGc(),DGc),5);!!$stats&&$stats(wHc(uai,EUg,-1,-1));qBd.al();!!$stats&&$stats(wHc(uai,g$g,-1,-1))}
function t_e(b,c){var d;c>1?(d=PDe(xai,yai,F$c(kxd,{113:1,175:1,177:1,321:1},1,[tqg+c]))):U$c(WU(U$c(b.k.hl(0),150),F0g),174).Sd(Xbh)?(d=PDe(zai,Aai,F$c(kxd,{113:1,175:1,177:1,321:1},1,[U$c(WU(b.s,Oyg),1)]))):(d=PDe(Wyh,Xyh,F$c(kxd,{113:1,175:1,177:1,321:1},1,[U$c(WU(b.s,Oyg),1)])));return d}
function ZFe(c,d,e,g){var b,j,k,n,o;n=new pPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:e$g,evtGroup:n.b,method:vai,millis:(new Date).getTime(),type:EUg});o=FNd(c);try{xNd(o.b,tqg+NMd(o,P2g));xNd(o.b,tqg+NMd(o,wai));xNd(o.b,fwg);xNd(o.b,tqg+NMd(o,Z2g));xNd(o.b,tqg+NMd(o,y1g));TMd(o,d);xNd(o.b,tqg+NMd(o,e));k=uNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:e$g,evtGroup:n.b,method:vai,millis:(new Date).getTime(),type:A1g});GNd(c,(dOd(),cOd),vai,n,k,g)}catch(b){b=pyd(b);if(X$c(b,311)){j=b;Oge(g,j)}else throw b}}
function u_e(b,c,d){n5();var e,g,i,j,k,n,o,p,q,r,s,t;pHb.call(this);Y7(this,650,500);FIb(this.ub,Bai);!!this.E&&$O(PO(this.E,LIg),Bai);lHb(this,false);this.b=new r6b;FIb(this.b.ub,ODe(jeh,jeh));this.b.xb=false;t6(this.b,false);B6(this.b,Cai);zxb(this.b,new Hrc(0));Y7(this.b,650,500);t=new cKb;gyb(this.b,t);p=new ARd;q=new ARd;for(n=c.k.Ud();n.$d();){k=U$c(n._d(),150);H$c(p.d,p.e++,k);jRd(q,U$c(WU(k,f0g),1))}i=new lzb;zxb(i,new kpc);i.hc=0;i.Jc&&QO(MP(J5(i),vvg),false);i.xb=false;this.c=i5e(p);Y7(this.c,650,200);gyb(i,this.c);gyb(this.b,i);s=new dbc;Y7(s,620,100);if(!d){gyb(this.b,new dKb(Dai+ODe(Ezh,Fzh)+Eai));gyb(this.b,s)}j=p.e;tX(this.c.I.g,new y_e(this,c,j,i,s,d,t));if(d){o=ODe(Yyh,Fai);gyb(this.b,new dKb(o));EIb(this.ub,(mMe(),kMe(),hMe))}r=new ZFb(ODe(Awh,Awh),new E_e(this,b,d,q,s));g=new ZFb(ODe(Cwh,Cwh),new Q_e(this));e=new lWb;e.E=(QH(),NH);WVb(e,r,e.Hb.e);WVb(e,g,e.Hb.e);gyb(this.b,e);ezb(this,e);this.rh(this.b,this.Hb.e)}
var Lai='620',Mai='70%',Eai=': <br />',Dai='<br />',Gai='<br /><br />',Fai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Nai='AsyncLoader5',Oai='DeleteItemWindow',Pai='DeleteItemWindow$1',Qai='DeleteItemWindow$2',Rai='DeleteItemWindow$2$1',Sai='DeleteItemWindow$3',Aai='Do you really want to remove the selected PAGE {0}?',yai='Do you really want to remove the {0} selected resources?',Bai='Informations',vai='JahiaContentManagementService_Proxy.markForDeletion',Cai='JahiaGxtDeleteItem',Kai='This node is still used by:',Iai='Those nodes are still used in:',wai='markForDeletion',xai='message.remove.multiple.confirm',Hai='message.remove.multiple.usage',zai='message.remove.single.page.confirm',Jai='message.remove.single.usage',uai='runCallbacks5';_=tBd.prototype=nBd.prototype=new HF;_.gC=function uBd(){return Ybd};_.al=function yBd(){sBd()};_.cM={};_=u_e.prototype=r_e.prototype=new IGb;_.gC=function v_e(){return fkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=y_e.prototype=w_e.prototype=new Rfb;_.gC=function z_e(){return bkd};_.ag=function A_e(b){var c,d,e;c=U$c(b.d,174);d=c.Nd();e=t_e(this.d,this.e);if(d>0){e+=Gai+(this.e>1?ODe(Hai,Iai):ODe(Jai,Kai))}else{syb(this.b.b,this.c);Z7(this.i,Lai,Mai);if(this.g){Y7(this.b,-1,130);Y7(this.b.b,-1,130)}}bKb(this.j,e);oxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=E_e.prototype=B_e.prototype=new Vgb;_.fg=function F_e(b){D_e(this,U$c(b,216))};_.gC=function G_e(){return dkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=J_e.prototype=H_e.prototype=new Lge;_.gC=function K_e(){return ckd};_.Hl=function L_e(b){S3e(this.b);b.fk();VNb(ODe(sch,tch),b.fk())};_.ye=function M_e(b){S3e(this.b);X3e(this.b,63);_3e(this.b)};_.cM={};_.b=null;_=Q_e.prototype=N_e.prototype=new Vgb;_.fg=function R_e(b){P_e(this,U$c(b,216))};_.gC=function S_e(){return ekd};_.cM={188:1};_.b=null;var Ybd=A1d(SOh,Nai),fkd=A1d(qXh,Oai),bkd=A1d(qXh,Pai),dkd=A1d(qXh,Qai),ckd=A1d(qXh,Rai),ekd=A1d(qXh,Sai);$entry(vBd)();