function SFd(){}
function MFd(){}
function n2e(){}
function s2e(){}
function x2e(){}
function D2e(){}
function J2e(){}
function M2e(b){this.b=b}
function L2e(b){oJb(b.b,null)}
function F2e(b,c){this.b=b;this.c=c}
function rdg(b){JJb(new q2e(b.b.p,b.b.p.Ql(),b.b.b))}
function RFd(){var b;while(NFd){b=NFd;NFd=NFd.c;!NFd&&(OFd=null);rdg(b.b)}}
function A2e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function u2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function UFd(){PFd=new SFd;vJc((sJc(),rJc),5);!!$stats&&$stats(kKc(ixi,bbh,-1,-1));PFd._k();!!$stats&&$stats(kKc(ixi,vfh,-1,-1))}
function z2e(b){var c,d;oJb(b.b,null);b.c.Tl(mIe(fLh,fLh));c=bJe();d=new F2e(b.c,b.e);b.d?EJe(c,b.g,d):AKe(c,b.g,t1c(sZb(b.i),1),d)}
function p2e(b,c){var d;c>1?(d=nIe(lxi,mxi,e1c(JBd,{113:1,175:1,177:1,323:1},1,[sJg+c]))):t1c(KW(t1c(b.k.hl(0),150),Qhh),174).Sd(Ash)?(d=nIe(nxi,oxi,e1c(JBd,{113:1,175:1,177:1,323:1},1,[t1c(KW(b.s,LRg),1)]))):(d=nIe(SPh,TPh,e1c(JBd,{113:1,175:1,177:1,323:1},1,[t1c(KW(b.s,LRg),1)])));return d}
function AKe(c,d,e,g){var b,j,k,n,o;n=new PTd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:tfh,evtGroup:n.b,method:jxi,millis:(new Date).getTime(),type:bbh});o=dSd(c);try{XRd(o.b,sJg+lRd(o,Xjh));XRd(o.b,sJg+lRd(o,kxi));XRd(o.b,ePg);XRd(o.b,sJg+lRd(o,fkh));XRd(o.b,sJg+lRd(o,Iih));rRd(o,d);XRd(o.b,sJg+lRd(o,e));k=URd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:tfh,evtGroup:n.b,method:jxi,millis:(new Date).getTime(),type:Kih});eSd(c,(DSd(),CSd),jxi,n,k,g)}catch(b){b=OCd(b);if(w1c(b,313)){j=b;fle(g,j)}else throw b}}
function q2e(b,c,d){j7();var e,g,i,j,k,n,o,p,q,r,s,t;LJb.call(this);Y9(this,650,500);bLb(this.ub,pxi);!!this.E&&OQ(DQ(this.E,R_g),pxi);HJb(this,false);this.b=new B8b;bLb(this.b.ub,mIe(FBh,FBh));this.b.xb=false;q8(this.b,false);z8(this.b,qxi);Szb(this.b,new Wtc(0));Y9(this.b,650,500);t=new CMb;CAb(this.b,t);p=new $Vd;q=new $Vd;for(n=c.k.Ud();n.$d();){k=t1c(n._d(),150);g1c(p.d,p.e++,k);JVd(q,t1c(KW(k,rhh),1))}i=new HBb;Szb(i,new Orc);i.hc=0;i.Jc&&EQ(AR(G7(i),tOg),false);i.xb=false;this.c=i8e(p);Y9(this.c,650,200);CAb(i,this.c);CAb(this.b,i);s=new ndc;Y9(s,620,100);if(!d){CAb(this.b,new DMb(rxi+mIe(pQh,qQh)+sxi));CAb(this.b,s)}j=p.e;hZ(this.c.I.g,new u2e(this,c,j,i,s,d,t));if(d){o=mIe(UPh,txi);CAb(this.b,new DMb(o));aLb(this.ub,(bRe(),_Qe(),YQe))}r=new tIb(mIe(vNh,vNh),new A2e(this,b,d,q,s,p));g=new tIb(mIe(wNh,wNh),new M2e(this));e=new vYb;e.E=(OJ(),LJ);eYb(e,r,e.Hb.e);eYb(e,g,e.Hb.e);CAb(this.b,e);ABb(this,e);this.uh(this.b,this.Hb.e)}
var zxi='620',Axi='70%',sxi=': <br />',rxi='<br />',uxi='<br /><br />',txi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Bxi='AsyncLoader5',Cxi='DeleteItemWindow',Dxi='DeleteItemWindow$1',Exi='DeleteItemWindow$2',Fxi='DeleteItemWindow$2$1',Gxi='DeleteItemWindow$3',oxi='Do you really want to remove the selected PAGE {0}?',mxi='Do you really want to remove the {0} selected resources?',pxi='Informations',jxi='JahiaContentManagementService_Proxy.markForDeletion',qxi='JahiaGxtDeleteItem',yxi='This node is still used by:',wxi='Those nodes are still used in:',kxi='markForDeletion',lxi='message.remove.multiple.confirm',vxi='message.remove.multiple.usage',nxi='message.remove.single.page.confirm',xxi='message.remove.single.usage',ixi='runCallbacks5';_=SFd.prototype=MFd.prototype=new FH;_.gC=function TFd(){return yed};_._k=function XFd(){RFd()};_.cM={};_=q2e.prototype=n2e.prototype=new cJb;_.gC=function r2e(){return umd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=u2e.prototype=s2e.prototype=new _hb;_.gC=function v2e(){return qmd};_.cg=function w2e(b){var c,d,e;c=t1c(b.d,174);d=c.Nd();e=p2e(this.d,this.e);if(d>0){e+=uxi+(this.e>1?mIe(vxi,wxi):mIe(xxi,yxi))}else{OAb(this.b.b,this.c);Z9(this.i,zxi,Axi);if(this.g){Y9(this.b,-1,130);Y9(this.b.b,-1,130)}}BMb(this.j,e);Hzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=A2e.prototype=x2e.prototype=new kjb;_.ig=function B2e(b){z2e(this,t1c(b,216))};_.gC=function C2e(){return smd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=F2e.prototype=D2e.prototype=new cle;_.gC=function G2e(){return rmd};_.Hl=function H2e(b){this.b.Sl();b.ok();yQb(mIe(Xsh,Ysh),b.ok())};_.ye=function I2e(b){var c;this.b.Sl();c=null;w1c(this.b,354)?(c=t1c(this.b,354).d.u):w1c(this.b,355)&&(c=t1c(this.b,355));if(!!c&&RVd(this.c,t1c(KW(c.q.j,rhh),1),0)!=-1){this.b.Ul(2);this.b.Vl(null)}else{this.b.Ul(63);this.b.Vl(null)}};_.cM={};_.b=null;_.c=null;_=M2e.prototype=J2e.prototype=new kjb;_.ig=function N2e(b){L2e(this,t1c(b,216))};_.gC=function O2e(){return tmd};_.cM={188:1};_.b=null;var yed=T5d(j3h,Bxi),umd=T5d(rbi,Cxi),qmd=T5d(rbi,Dxi),smd=T5d(rbi,Exi),rmd=T5d(rbi,Fxi),tmd=T5d(rbi,Gxi);$entry(UFd)();