function PFd(){}
function JFd(){}
function J2e(){}
function t2e(){}
function y2e(){}
function D2e(){}
function P2e(){}
function S2e(b){this.b=b}
function R2e(b){qJb(b.b,null)}
function L2e(b,c){this.b=b;this.c=c}
function xdg(b){LJb(new w2e(b.b.p,b.b.p.Ql(),b.b.b))}
function OFd(){var b;while(KFd){b=KFd;KFd=KFd.c;!KFd&&(LFd=null);xdg(b.b)}}
function G2e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function A2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function RFd(){MFd=new PFd;xJc((uJc(),tJc),5);!!$stats&&$stats(mKc(sxi,gbh,-1,-1));MFd._k();!!$stats&&$stats(mKc(sxi,Dfh,-1,-1))}
function F2e(b){var c,d;qJb(b.b,null);b.c.Tl(sIe(nLh,nLh));c=hJe();d=new L2e(b.c,b.e);b.d?KJe(c,b.g,d):GKe(c,b.g,o1c(uZb(b.i),1),d)}
function v2e(b,c){var d;c>1?(d=tIe(vxi,wxi,_0c(GBd,{113:1,175:1,177:1,323:1},1,[yJg+c]))):o1c(MW(o1c(b.k.hl(0),150),Yhh),174).Sd(Ish)?(d=tIe(xxi,yxi,_0c(GBd,{113:1,175:1,177:1,323:1},1,[o1c(MW(b.s,RRg),1)]))):(d=tIe($Ph,_Ph,_0c(GBd,{113:1,175:1,177:1,323:1},1,[o1c(MW(b.s,RRg),1)])));return d}
function GKe(c,d,e,g){var b,j,k,n,o;n=new MTd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Bfh,evtGroup:n.b,method:txi,millis:(new Date).getTime(),type:gbh});o=aSd(c);try{URd(o.b,yJg+iRd(o,dkh));URd(o.b,yJg+iRd(o,uxi));URd(o.b,kPg);URd(o.b,yJg+iRd(o,nkh));URd(o.b,yJg+iRd(o,Qih));oRd(o,d);URd(o.b,yJg+iRd(o,e));k=RRd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Bfh,evtGroup:n.b,method:txi,millis:(new Date).getTime(),type:Sih});bSd(c,(ASd(),zSd),txi,n,k,g)}catch(b){b=LCd(b);if(r1c(b,313)){j=b;lle(g,j)}else throw b}}
function w2e(b,c,d){l7();var e,g,i,j,k,n,o,p,q,r,s,t;NJb.call(this);$9(this,650,500);dLb(this.ub,zxi);!!this.E&&QQ(FQ(this.E,X_g),zxi);JJb(this,false);this.b=new D8b;dLb(this.b.ub,sIe(NBh,NBh));this.b.xb=false;s8(this.b,false);B8(this.b,Axi);Uzb(this.b,new Ytc(0));$9(this.b,650,500);t=new EMb;EAb(this.b,t);p=new XVd;q=new XVd;for(n=c.k.Ud();n.$d();){k=o1c(n._d(),150);b1c(p.d,p.e++,k);GVd(q,o1c(MW(k,zhh),1))}i=new JBb;Uzb(i,new Qrc);i.hc=0;i.Jc&&GQ(CR(I7(i),zOg),false);i.xb=false;this.c=o8e(p);$9(this.c,650,200);EAb(i,this.c);EAb(this.b,i);s=new pdc;$9(s,620,100);if(!d){EAb(this.b,new FMb(Bxi+sIe(xQh,yQh)+Cxi));EAb(this.b,s)}j=p.e;jZ(this.c.I.g,new A2e(this,c,j,i,s,d,t));if(d){o=sIe(aQh,Dxi);EAb(this.b,new FMb(o));cLb(this.ub,(hRe(),fRe(),cRe))}r=new vIb(sIe(DNh,DNh),new G2e(this,b,d,q,s,p));g=new vIb(sIe(ENh,ENh),new S2e(this));e=new xYb;e.E=(QJ(),NJ);gYb(e,r,e.Hb.e);gYb(e,g,e.Hb.e);EAb(this.b,e);CBb(this,e);this.uh(this.b,this.Hb.e)}
var Jxi='620',Kxi='70%',Cxi=': <br />',Bxi='<br />',Exi='<br /><br />',Dxi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Lxi='AsyncLoader5',Mxi='DeleteItemWindow',Nxi='DeleteItemWindow$1',Oxi='DeleteItemWindow$2',Pxi='DeleteItemWindow$2$1',Qxi='DeleteItemWindow$3',yxi='Do you really want to remove the selected PAGE {0}?',wxi='Do you really want to remove the {0} selected resources?',zxi='Informations',txi='JahiaContentManagementService_Proxy.markForDeletion',Axi='JahiaGxtDeleteItem',Ixi='This node is still used by:',Gxi='Those nodes are still used in:',uxi='markForDeletion',vxi='message.remove.multiple.confirm',Fxi='message.remove.multiple.usage',xxi='message.remove.single.page.confirm',Hxi='message.remove.single.usage',sxi='runCallbacks5';_=PFd.prototype=JFd.prototype=new HH;_.gC=function QFd(){return ted};_._k=function UFd(){OFd()};_.cM={};_=w2e.prototype=t2e.prototype=new eJb;_.gC=function x2e(){return rmd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=A2e.prototype=y2e.prototype=new bib;_.gC=function B2e(){return nmd};_.cg=function C2e(b){var c,d,e;c=o1c(b.d,174);d=c.Nd();e=v2e(this.d,this.e);if(d>0){e+=Exi+(this.e>1?sIe(Fxi,Gxi):sIe(Hxi,Ixi))}else{QAb(this.b.b,this.c);_9(this.i,Jxi,Kxi);if(this.g){$9(this.b,-1,130);$9(this.b.b,-1,130)}}DMb(this.j,e);Jzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=G2e.prototype=D2e.prototype=new mjb;_.ig=function H2e(b){F2e(this,o1c(b,216))};_.gC=function I2e(){return pmd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=L2e.prototype=J2e.prototype=new ile;_.gC=function M2e(){return omd};_.Hl=function N2e(b){this.b.Sl();b.ok();AQb(sIe(dth,eth),b.ok())};_.ye=function O2e(b){var c;this.b.Sl();c=null;r1c(this.b,354)?(c=o1c(this.b,354).d.u):r1c(this.b,355)&&(c=o1c(this.b,355));if(!!c&&OVd(this.c,o1c(MW(c.q.j,zhh),1),0)!=-1){this.b.Ul(2);this.b.Vl(null)}else{this.b.Ul(63);this.b.Vl(null)}};_.cM={};_.b=null;_.c=null;_=S2e.prototype=P2e.prototype=new mjb;_.ig=function T2e(b){R2e(this,o1c(b,216))};_.gC=function U2e(){return qmd};_.cM={188:1};_.b=null;var ted=Z5d(r3h,Lxi),rmd=Z5d(Bbi,Mxi),nmd=Z5d(Bbi,Nxi),pmd=Z5d(Bbi,Oxi),omd=Z5d(Bbi,Pxi),qmd=Z5d(Bbi,Qxi);$entry(RFd)();