function BGd(){}
function vGd(){}
function k3e(){}
function p3e(){}
function u3e(){}
function A3e(){}
function G3e(){}
function J3e(b){this.b=b}
function I3e(b){uJb(b.b,null)}
function C3e(b,c){this.b=b;this.c=c}
function oeg(b){PJb(new n3e(b.b.p,b.b.p.am(),b.b.b))}
function AGd(){var b;while(wGd){b=wGd;wGd=wGd.c;!wGd&&(xGd=null);oeg(b.b)}}
function x3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function r3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function DGd(){yGd=new BGd;AJc((xJc(),wJc),5);!!$stats&&$stats(pKc(Fzi,Xbh,-1,-1));yGd.ll();!!$stats&&$stats(pKc(Fzi,Mhh,-1,-1))}
function w3e(b){var c,d;uJb(b.b,null);b.c.dm(jJe(xNh,xNh));c=$Je();d=new C3e(b.c,b.e);b.d?BKe(c,b.g,d):xLe(c,b.g,_1c(yZb(b.i),1),d)}
function m3e(b,c){var d;c>1?(d=kJe(Izi,Jzi,M1c(sCd,{113:1,175:1,177:1,323:1},1,[pKg+c]))):_1c(RW(_1c(b.k.tl(0),150),fkh),174).Sd(Ruh)?(d=kJe(Kzi,Lzi,M1c(sCd,{113:1,175:1,177:1,323:1},1,[_1c(RW(b.s,NSg),1)]))):(d=kJe(kSh,lSh,M1c(sCd,{113:1,175:1,177:1,323:1},1,[_1c(RW(b.s,NSg),1)])));return d}
function xLe(c,d,e,g){var b,j,k,n,o;n=new IUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Khh,evtGroup:n.b,method:Gzi,millis:(new Date).getTime(),type:Xbh});o=YSd(c);try{QSd(o.b,pKg+eSd(o,mmh));QSd(o.b,pKg+eSd(o,Hzi));QSd(o.b,cQg);QSd(o.b,pKg+eSd(o,wmh));QSd(o.b,pKg+eSd(o,Zkh));kSd(o,d);QSd(o.b,pKg+eSd(o,e));k=NSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Khh,evtGroup:n.b,method:Gzi,millis:(new Date).getTime(),type:_kh});ZSd(c,(wTd(),vTd),Gzi,n,k,g)}catch(b){b=xDd(b);if(c2c(b,313)){j=b;cme(g,j)}else throw b}}
function n3e(b,c,d){q7();var e,g,i,j,k,n,o,p,q,r,s,t;RJb.call(this);dab(this,650,500);hLb(this.ub,Mzi);!!this.E&&RQ(GQ(this.E,J0g),Mzi);NJb(this,false);this.b=new H8b;hLb(this.b.ub,jJe(XDh,XDh));this.b.xb=false;x8(this.b,false);G8(this.b,Nzi);Yzb(this.b,new auc(0));dab(this.b,650,500);t=new IMb;IAb(this.b,t);p=new TWd;q=new TWd;for(n=c.k.Ud();n.$d();){k=_1c(n._d(),150);O1c(p.d,p.e++,k);CWd(q,_1c(RW(k,Ijh),1))}i=new NBb;Yzb(i,new Urc);i.hc=0;i.Jc&&HQ(DR(N7(i),sPg),false);i.xb=false;this.c=f9e(p);dab(this.c,650,200);IAb(i,this.c);IAb(this.b,i);s=new tdc;dab(s,620,100);if(!d){IAb(this.b,new JMb(Ozi+jJe(JSh,KSh)+Pzi));IAb(this.b,s)}j=p.e;oZ(this.c.I.g,new r3e(this,c,j,i,s,d,t));if(d){o=jJe(mSh,Qzi);IAb(this.b,new JMb(o));gLb(this.ub,($Re(),YRe(),VRe))}r=new zIb(jJe(NPh,NPh),new x3e(this,b,d,q,s,p));g=new zIb(jJe(PPh,PPh),new J3e(this));e=new BYb;e.E=(RJ(),OJ);kYb(e,r,e.Hb.e);kYb(e,g,e.Hb.e);IAb(this.b,e);GBb(this,e);this.uh(this.b,this.Hb.e)}
var Wzi='620',Xzi='70%',Pzi=': <br />',Ozi='<br />',Rzi='<br /><br />',Qzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Yzi='AsyncLoader5',Zzi='DeleteItemWindow',$zi='DeleteItemWindow$1',_zi='DeleteItemWindow$2',aAi='DeleteItemWindow$2$1',bAi='DeleteItemWindow$3',Lzi='Do you really want to remove the selected PAGE {0}?',Jzi='Do you really want to remove the {0} selected resources?',Mzi='Informations',Gzi='JahiaContentManagementService_Proxy.markForDeletion',Nzi='JahiaGxtDeleteItem',Vzi='This node is still used by:',Tzi='Those nodes are still used in:',Hzi='markForDeletion',Izi='message.remove.multiple.confirm',Szi='message.remove.multiple.usage',Kzi='message.remove.single.page.confirm',Uzi='message.remove.single.usage',Fzi='runCallbacks5';_=BGd.prototype=vGd.prototype=new IH;_.gC=function CGd(){return ffd};_.ll=function GGd(){AGd()};_.cM={};_=n3e.prototype=k3e.prototype=new iJb;_.gC=function o3e(){return dnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=r3e.prototype=p3e.prototype=new gib;_.gC=function s3e(){return _md};_.cg=function t3e(b){var c,d,e;c=_1c(b.d,174);d=c.Nd();e=m3e(this.d,this.e);if(d>0){e+=Rzi+(this.e>1?jJe(Szi,Tzi):jJe(Uzi,Vzi))}else{UAb(this.b.b,this.c);eab(this.i,Wzi,Xzi);if(this.g){dab(this.b,-1,130);dab(this.b.b,-1,130)}}HMb(this.j,e);Nzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=x3e.prototype=u3e.prototype=new rjb;_.ig=function y3e(b){w3e(this,_1c(b,216))};_.gC=function z3e(){return bnd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=C3e.prototype=A3e.prototype=new _le;_.gC=function D3e(){return and};_.Tl=function E3e(b){this.b.cm();b.ok();EQb(jJe(mvh,nvh),b.ok())};_.ye=function F3e(b){var c;this.b.cm();c=null;c2c(this.b,354)?(c=_1c(this.b,354).d.u):c2c(this.b,355)&&(c=_1c(this.b,355));if(!!c&&KWd(this.c,_1c(RW(c.q.j,Ijh),1),0)!=-1){this.b.em(2);this.b.fm(null)}else{this.b.em(63);this.b.fm(null)}};_.cM={};_.b=null;_.c=null;_=J3e.prototype=G3e.prototype=new rjb;_.ig=function K3e(b){I3e(this,_1c(b,216))};_.gC=function L3e(){return cnd};_.cM={188:1};_.b=null;var ffd=Q6d(E5h,Yzi),dnd=Q6d(Odi,Zzi),_md=Q6d(Odi,$zi),bnd=Q6d(Odi,_zi),and=Q6d(Odi,aAi),cnd=Q6d(Odi,bAi);$entry(DGd)();