function CSc(){}
function zSc(){}
function AGd(){}
function uGd(){}
function u5e(){}
function e5e(){}
function m5e(){}
function k5e(){}
function o5e(){}
function A5e(){}
function r5e(b){this.b=b}
function q5e(b){sJb(b.b,null)}
function Hcg(b){NJb(new i5e(b.b.p,b.b.p.cm().s))}
function BSc(){BSc=EEg;ASc=new GRc(Qgh,new CSc)}
function zGd(){var b;while(vGd){b=vGd;vGd=vGd.c;!vGd&&(wGd=null);Hcg(b.b)}}
function g5e(b,c,d,e,g,i,j,k){CKe(cKe(),c,d,e,g,i,j,k,new C5e(b,c,d,e,g,i,j))}
function C5e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function x5e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function CGd(){xGd=new AGd;zJc((wJc(),vJc),4);!!$stats&&$stats(oKc(czi,Ybh,-1,-1));xGd.nl();!!$stats&&$stats(oKc(czi,Chh,-1,-1))}
function h5e(){$wnd.jQuery(fzi).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(gzi).val(b.x);$wnd.jQuery(hzi).val(b.y);$wnd.jQuery(izi).val(b.w);$wnd.jQuery(jzi).val(b.h)}})}
function w5e(b){s2c(wZb(b.j),119).Kl()>0&&s2c(wZb(b.c),119).Kl()>0&&g5e(b.b,s2c(OW(b.e,yjh),1),s2c(b.g.ce(),1),s2c(wZb(b.i),119).Kl(),s2c(wZb(b.d),119).Kl(),s2c(wZb(b.j),119).Kl(),s2c(wZb(b.c),119).Kl(),false)}
function CKe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new QUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Ahh,evtGroup:r.b,method:dzi,millis:(new Date).getTime(),type:Ybh});s=eTd(c);try{YSd(s.b,tKg+mSd(s,cmh));YSd(s.b,tKg+mSd(s,ezi));YSd(s.b,ymh);YSd(s.b,tKg+mSd(s,Pkh));YSd(s.b,tKg+mSd(s,Pkh));YSd(s.b,tKg+mSd(s,Qkh));YSd(s.b,tKg+mSd(s,Qkh));YSd(s.b,tKg+mSd(s,Qkh));YSd(s.b,tKg+mSd(s,Qkh));YSd(s.b,tKg+mSd(s,tmh));YSd(s.b,tKg+mSd(s,d));YSd(s.b,tKg+mSd(s,e));YSd(s.b,tKg+g);YSd(s.b,tKg+i);YSd(s.b,tKg+j);YSd(s.b,tKg+k);YSd(s.b,n?ZOg:JNg);q=VSd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Ahh,evtGroup:r.b,method:dzi,millis:(new Date).getTime(),type:Rkh});fTd(c,(ETd(),DTd),dzi,r,q,o)}catch(b){b=RDd(b);if(!v2c(b,313))throw b}}
function i5e(b,c){n7();var d,e,g,i,j,k,n,o,p,q,r,s;PJb.call(this);Wzb(this,new Src);aab(this,712,550);this.b=b;GJb(this,nJe(kzi,kzi));this.Ac=lzi;!!this.sc&&(K7(this).id=lzi,undefined);j=new F8b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&IQ(ER(K7(j),uPg),false);p=new O0b;p.Ei(mzi);i=s2c(OW(c,OSg),1).lastIndexOf(KNg);if(i>0){g=_9d(s2c(OW(c,OSg),1),i);p.Hi(Y9d(s2c(OW(c,OSg),1),g,nzi+g))}else{p.Hi(s2c(OW(c,OSg),1)+nzi)}PZb(p,nJe(Kxh,Kxh));LAb(j,p,j.Hb.e);r=new ibc;RZb(r,kLg);r.Ac=kLg;!!r.sc&&(K7(r).id=kLg,undefined);T7(r);LAb(j,r,j.Hb.e);o=new ibc;RZb(o,jLg);o.Ac=jLg;!!o.sc&&(K7(o).id=jLg,undefined);T7(o);LAb(j,o,j.Hb.e);s=new ibc;PZb(s,nJe(ozi,jBh));H8(s,pzi);RZb(s,yLg);s.Ac=yLg;!!s.sc&&(K7(s).id=yLg,undefined);N8(s);x7(s);LAb(j,s,j.Hb.e);k=new ibc;PZb(k,nJe(qzi,oBh));H8(k,rzi);RZb(k,xLg);k.Ac=xLg;!!k.sc&&(K7(k).id=xLg,undefined);N8(k);x7(k);LAb(j,k,j.Hb.e);n=new s0d;P6(n,new m5e,(BSc(),BSc(),ASc));n.ad.id=szi;r0d(n,c.A);LAb(j,n,j.Hb.e);d=new zYb;e=new xIb(nJe(axh,axh),new r5e(this));q=new xIb(nJe(kxh,kxh),new x5e(this,s,k,c,p,r,o));iYb(d,q,d.Hb.e);iYb(d,e,d.Hb.e);FBb(this,(SJ(),PJ));EBb(this,d);Jzb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var fzi='#cropbox',jzi='#height-input',gzi='#left-input',hzi='#top-input',izi='#width-input',uzi='AsyncLoader4',vzi='ImageCrop',wzi='ImageCrop$1',xzi='ImageCrop$2',yzi='ImageCrop$3',zzi='ImageCrop$4',dzi='JahiaContentManagementService_Proxy.cropImage',lzi='JahiaGxtImageCrop',nzi='_crop',ezi='cropImage',szi='cropbox',tzi='failure.crop.label',kzi='label.crop',qzi='label.height',ozi='label.width',czi='runCallbacks4',rzi='stylehight',pzi='stylewidth';_=CSc.prototype=zSc.prototype=new NQc;_.wk=function DSc(b){s2c(b,290);h5e()};_.zk=function ESc(){return ASc};_.gC=function FSc(){return qed};_.cM={};var ASc;_=AGd.prototype=uGd.prototype=new JH;_.gC=function BGd(){return yfd};_.nl=function FGd(){zGd()};_.cM={};_=i5e.prototype=e5e.prototype=new gJb;_.gC=function j5e(){return Ond};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_=m5e.prototype=k5e.prototype=new JH;_.gC=function n5e(){return Knd};_.cM={290:1,294:1};_=r5e.prototype=o5e.prototype=new ojb;_.ig=function s5e(b){q5e(this,s2c(b,216))};_.gC=function t5e(){return Lnd};_.cM={188:1};_.b=null;_=x5e.prototype=u5e.prototype=new ojb;_.ig=function y5e(b){w5e(this,s2c(b,216))};_.gC=function z5e(){return Mnd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=C5e.prototype=A5e.prototype=new dme;_.gC=function D5e(){return Nnd};_.Vl=function E5e(b){if(b!=null&&b.cM&&!!b.cM[353]){$wnd.confirm(nJe(Yzh,Yzh)+Gah+nJe(KRh,KRh))&&g5e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(nJe(tzi,tzi)+Gah+b.ok());nJe(tzi,tzi)}};_.ye=function F5e(b){sJb(this.b,null);this.b.b.gm(1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var qed=U6d(j4h,SUh),yfd=U6d(z5h,uzi),Ond=U6d(Hdi,vzi),Knd=U6d(Hdi,wzi),Lnd=U6d(Hdi,xzi),Mnd=U6d(Hdi,yzi),Nnd=U6d(Hdi,zzi);$entry(CGd)();