function VGd(){}
function PGd(){}
function o3e(){}
function t3e(){}
function y3e(){}
function E3e(){}
function K3e(){}
function N3e(b){this.b=b}
function M3e(b){sJb(b.b,null)}
function G3e(b,c){this.b=b;this.c=c}
function seg(b){NJb(new r3e(b.b.p,b.b.p.cm(),b.b.b))}
function UGd(){var b;while(QGd){b=QGd;QGd=QGd.c;!QGd&&(RGd=null);seg(b.b)}}
function B3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function v3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function XGd(){SGd=new VGd;zJc((wJc(),vJc),5);!!$stats&&$stats(oKc(Azi,Ybh,-1,-1));SGd.nl();!!$stats&&$stats(oKc(Azi,Chh,-1,-1))}
function A3e(b){var c,d;sJb(b.b,null);b.c.fm(nJe(pNh,pNh));c=cKe();d=new G3e(b.c,b.e);b.d?FKe(c,b.g,d):BLe(c,b.g,s2c(wZb(b.i),1),d)}
function q3e(b,c){var d;c>1?(d=oJe(Dzi,Ezi,d2c(MCd,{113:1,175:1,177:1,323:1},1,[tKg+c]))):s2c(OW(s2c(b.k.vl(0),150),Xjh),174).Sd(Huh)?(d=oJe(Fzi,Gzi,d2c(MCd,{113:1,175:1,177:1,323:1},1,[s2c(OW(b.s,OSg),1)]))):(d=oJe(cSh,dSh,d2c(MCd,{113:1,175:1,177:1,323:1},1,[s2c(OW(b.s,OSg),1)])));return d}
function BLe(c,d,e,g){var b,j,k,n,o;n=new QUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Ahh,evtGroup:n.b,method:Bzi,millis:(new Date).getTime(),type:Ybh});o=eTd(c);try{YSd(o.b,tKg+mSd(o,cmh));YSd(o.b,tKg+mSd(o,Czi));YSd(o.b,fQg);YSd(o.b,tKg+mSd(o,mmh));YSd(o.b,tKg+mSd(o,Pkh));sSd(o,d);YSd(o.b,tKg+mSd(o,e));k=VSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Ahh,evtGroup:n.b,method:Bzi,millis:(new Date).getTime(),type:Rkh});fTd(c,(ETd(),DTd),Bzi,n,k,g)}catch(b){b=RDd(b);if(v2c(b,313)){j=b;gme(g,j)}else throw b}}
function r3e(b,c,d){n7();var e,g,i,j,k,n,o,p,q,r,s,t;PJb.call(this);aab(this,650,500);fLb(this.ub,Hzi);!!this.E&&SQ(HQ(this.E,M0g),Hzi);LJb(this,false);this.b=new F8b;fLb(this.b.ub,nJe(ODh,ODh));this.b.xb=false;u8(this.b,false);D8(this.b,Izi);Wzb(this.b,new $tc(0));aab(this.b,650,500);t=new GMb;GAb(this.b,t);p=new _Wd;q=new _Wd;for(n=c.k.Ud();n.$d();){k=s2c(n._d(),150);f2c(p.d,p.e++,k);KWd(q,s2c(OW(k,yjh),1))}i=new LBb;Wzb(i,new Src);i.hc=0;i.Jc&&IQ(ER(K7(i),uPg),false);i.xb=false;this.c=j9e(p);aab(this.c,650,200);GAb(i,this.c);GAb(this.b,i);s=new rdc;aab(s,620,100);if(!d){GAb(this.b,new HMb(Jzi+nJe(BSh,CSh)+Kzi));GAb(this.b,s)}j=p.e;lZ(this.c.I.g,new v3e(this,c,j,i,s,d,t));if(d){o=nJe(eSh,Lzi);GAb(this.b,new HMb(o));eLb(this.ub,(cSe(),aSe(),ZRe))}r=new xIb(nJe(FPh,FPh),new B3e(this,b,d,q,s,p));g=new xIb(nJe(HPh,HPh),new N3e(this));e=new zYb;e.E=(SJ(),PJ);iYb(e,r,e.Hb.e);iYb(e,g,e.Hb.e);GAb(this.b,e);EBb(this,e);this.uh(this.b,this.Hb.e)}
var Rzi='620',Szi='70%',Kzi=': <br />',Jzi='<br />',Mzi='<br /><br />',Lzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Tzi='AsyncLoader5',Uzi='DeleteItemWindow',Vzi='DeleteItemWindow$1',Wzi='DeleteItemWindow$2',Xzi='DeleteItemWindow$2$1',Yzi='DeleteItemWindow$3',Gzi='Do you really want to remove the selected PAGE {0}?',Ezi='Do you really want to remove the {0} selected resources?',Hzi='Informations',Bzi='JahiaContentManagementService_Proxy.markForDeletion',Izi='JahiaGxtDeleteItem',Qzi='This node is still used by:',Ozi='Those nodes are still used in:',Czi='markForDeletion',Dzi='message.remove.multiple.confirm',Nzi='message.remove.multiple.usage',Fzi='message.remove.single.page.confirm',Pzi='message.remove.single.usage',Azi='runCallbacks5';_=VGd.prototype=PGd.prototype=new JH;_.gC=function WGd(){return Bfd};_.nl=function $Gd(){UGd()};_.cM={};_=r3e.prototype=o3e.prototype=new gJb;_.gC=function s3e(){return xnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=v3e.prototype=t3e.prototype=new dib;_.gC=function w3e(){return tnd};_.cg=function x3e(b){var c,d,e;c=s2c(b.d,174);d=c.Nd();e=q3e(this.d,this.e);if(d>0){e+=Mzi+(this.e>1?nJe(Nzi,Ozi):nJe(Pzi,Qzi))}else{SAb(this.b.b,this.c);bab(this.i,Rzi,Szi);if(this.g){aab(this.b,-1,130);aab(this.b.b,-1,130)}}FMb(this.j,e);Lzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=B3e.prototype=y3e.prototype=new ojb;_.ig=function C3e(b){A3e(this,s2c(b,216))};_.gC=function D3e(){return vnd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=G3e.prototype=E3e.prototype=new dme;_.gC=function H3e(){return und};_.Vl=function I3e(b){this.b.em();b.ok();CQb(nJe(cvh,dvh),b.ok())};_.ye=function J3e(b){var c;this.b.em();c=null;v2c(this.b,354)?(c=s2c(this.b,354).d.u):v2c(this.b,355)&&(c=s2c(this.b,355));if(!!c&&SWd(this.c,s2c(OW(c.q.j,yjh),1),0)!=-1){this.b.gm(2);this.b.hm(null)}else{this.b.gm(63);this.b.hm(null)}};_.cM={};_.b=null;_.c=null;_=N3e.prototype=K3e.prototype=new ojb;_.ig=function O3e(b){M3e(this,s2c(b,216))};_.gC=function P3e(){return wnd};_.cM={188:1};_.b=null;var Bfd=U6d(z5h,Tzi),xnd=U6d(Hdi,Uzi),tnd=U6d(Hdi,Vzi),vnd=U6d(Hdi,Wzi),und=U6d(Hdi,Xzi),wnd=U6d(Hdi,Yzi);$entry(XGd)();