function nPc(){}
function kPc(){}
function jBd(){}
function dBd(){}
function x1e(){}
function F1e(){}
function D1e(){}
function H1e(){}
function N1e(){}
function T1e(){}
function K1e(b){this.b=b}
function J1e(b){XGb(b.b,null)}
function kXd(b,c){b.b.wl(b,c)}
function VUf(b){qHb(new B1e(b.b.p,b.b.p.p.s))}
function mPc(){mPc=Okg;lPc=new rOc(JZg,new nPc)}
function lXd(){hXd();this.b=new MXd(this);this.ad[jtg]=z_g}
function iBd(){var b;while(eBd){b=eBd;eBd=eBd.c;!eBd&&(fBd=null);VUf(b.b)}}
function z1e(b,c,d,e,g,i,j,k){rFe(TEe(),c,d,e,g,i,j,k,new V1e(b,c,d,e,g,i,j))}
function V1e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function Q1e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function lBd(){gBd=new jBd;JGc((GGc(),FGc),4);!!$stats&&$stats(yHc(Bai,YUg,-1,-1));gBd.cl();!!$stats&&$stats(yHc(Bai,O$g,-1,-1))}
function A1e(){$wnd.jQuery(Eai).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(Fai).val(b.x);$wnd.jQuery(Gai).val(b.y);$wnd.jQuery(Hai).val(b.w);$wnd.jQuery(Iai).val(b.h)}})}
function P1e(b){d_c(lXb(b.j),119).yl()>0&&d_c(lXb(b.c),119).yl()>0&&z1e(b.b,d_c($U(b.e,N0g),1),d_c(b.g.ce(),1),d_c(lXb(b.i),119).yl(),d_c(lXb(b.d),119).yl(),d_c(lXb(b.j),119).yl(),d_c(lXb(b.c),119).yl(),false)}
function rFe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new KPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:M$g,evtGroup:r.b,method:Cai,millis:(new Date).getTime(),type:YUg});s=$Nd(c);try{SNd(s.b,Jqg+gNd(s,v3g));SNd(s.b,Jqg+gNd(s,Dai));SNd(s.b,W3g);SNd(s.b,Jqg+gNd(s,e2g));SNd(s.b,Jqg+gNd(s,e2g));SNd(s.b,Jqg+gNd(s,f2g));SNd(s.b,Jqg+gNd(s,f2g));SNd(s.b,Jqg+gNd(s,f2g));SNd(s.b,Jqg+gNd(s,f2g));SNd(s.b,Jqg+gNd(s,O3g));SNd(s.b,Jqg+gNd(s,d));SNd(s.b,Jqg+gNd(s,e));SNd(s.b,Jqg+g);SNd(s.b,Jqg+i);SNd(s.b,Jqg+j);SNd(s.b,Jqg+k);SNd(s.b,n?qvg:_tg);q=PNd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:M$g,evtGroup:r.b,method:Cai,millis:(new Date).getTime(),type:g2g});_Nd(c,(yOd(),xOd),Cai,r,q,o)}catch(b){b=Ayd(b);if(!g_c(b,311))throw b}}
function B1e(b,c){r5();var d,e,g,i,j,k,n,o,p,q,r,s;sHb.call(this);Cxb(this,new npc);a8(this,712,550);this.b=b;jHb(this,cEe(Jai,Jai));this.Ac=Kai;!!this.sc&&(N5(this).id=Kai,undefined);j=new u6b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&QO(MP(N5(j),Nvg),false);p=new D$b;p.vi(Lai);i=d_c($U(c,fzg),1).lastIndexOf(aug);if(i>0){g=X4d(d_c($U(c,fzg),1),i);p.yi(U4d(d_c($U(c,fzg),1),g,Mai+g))}else{p.yi(d_c($U(c,fzg),1)+Mai)}EXb(p,cEe(Tfh,Tfh));oyb(j,p,j.Hb.e);r=new Z8b;GXb(r,Drg);r.Ac=Drg;!!r.sc&&(N5(r).id=Drg,undefined);W5(r);oyb(j,r,j.Hb.e);o=new Z8b;GXb(o,Crg);o.Ac=Crg;!!o.sc&&(N5(o).id=Crg,undefined);W5(o);oyb(j,o,j.Hb.e);s=new Z8b;EXb(s,cEe(Nai,Xjh));J6(s,Oai);GXb(s,Rrg);s.Ac=Rrg;!!s.sc&&(N5(s).id=Rrg,undefined);P6(s);B5(s);oyb(j,s,j.Hb.e);k=new Z8b;EXb(k,cEe(Pai,akh));J6(k,Qai);GXb(k,Qrg);k.Ac=Qrg;!!k.sc&&(N5(k).id=Qrg,undefined);P6(k);B5(k);oyb(j,k,j.Hb.e);n=new lXd;T4(n,new F1e,(mPc(),mPc(),lPc));n.ad.id=Rai;kXd(n,c.A);oyb(j,n,j.Hb.e);d=new oWb;e=new aGb(cEe(ifh,ifh),new K1e(this));q=new aGb(cEe(sfh,sfh),new Q1e(this,s,k,c,p,r,o));ZVb(d,q,d.Hb.e);ZVb(d,e,d.Hb.e);izb(this,(QH(),NH));hzb(this,d);pxb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var Eai='#cropbox',Iai='#height-input',Fai='#left-input',Gai='#top-input',Hai='#width-input',Tai='AsyncLoader4',Uai='ImageCrop',Vai='ImageCrop$1',Wai='ImageCrop$2',Xai='ImageCrop$3',Yai='ImageCrop$4',Cai='JahiaContentManagementService_Proxy.cropImage',Kai='JahiaGxtImageCrop',Mai='_crop',Dai='cropImage',Rai='cropbox',Sai='failure.crop.label',Jai='label.crop',Pai='label.height',Nai='label.width',Bai='runCallbacks4',Qai='stylehight',Oai='stylewidth';_=nPc.prototype=kPc.prototype=new yNc;_.kk=function oPc(b){d_c(b,288);A1e()};_.nk=function pPc(){return lPc};_.gC=function qPc(){return Yad};_.cM={};var lPc;_=jBd.prototype=dBd.prototype=new HF;_.gC=function kBd(){return ecd};_.cl=function oBd(){iBd()};_.cM={};_=lXd.prototype=gXd.prototype;_=rXd.prototype;_.wl=function CXd(b,c){b.b=new MXd(b);b.b.wl(b,c)};_=IXd.prototype;_.wl=function RXd(b,c){!!b.b&&(b.b.ul(b)[A_g]=Jqg,undefined);b.ad.src=c};_=B1e.prototype=x1e.prototype=new LGb;_.gC=function C1e(){return Hkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_=F1e.prototype=D1e.prototype=new HF;_.gC=function G1e(){return Dkd};_.cM={288:1,292:1};_=K1e.prototype=H1e.prototype=new Zgb;_.fg=function L1e(b){J1e(this,d_c(b,216))};_.gC=function M1e(){return Ekd};_.cM={188:1};_.b=null;_=Q1e.prototype=N1e.prototype=new Zgb;_.fg=function R1e(b){P1e(this,d_c(b,216))};_.gC=function S1e(){return Fkd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=V1e.prototype=T1e.prototype=new _ge;_.gC=function W1e(){return Gkd};_.Jl=function X1e(b){if(b!=null&&b.cM&&!!b.cM[354]){$wnd.confirm(cEe(fih,fih)+GTg+cEe(fzh,fzh))&&z1e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(cEe(Sai,Sai)+GTg+b.fk());cEe(Sai,Sai)}};_.ye=function Y1e(b){XGb(this.b,null);l4e(this.b.b,1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var Yad=Q1d(gOh,ECh),ecd=Q1d(vPh,Tai),Hkd=Q1d(VXh,Uai),Dkd=Q1d(VXh,Vai),Ekd=Q1d(VXh,Wai),Fkd=Q1d(VXh,Xai),Gkd=Q1d(VXh,Yai);$entry(lBd)();