function EBd(){}
function yBd(){}
function H_e(){}
function M_e(){}
function R_e(){}
function X_e(){}
function b0e(){}
function e0e(b){this.b=b}
function Z_e(b){this.b=b}
function d0e(b){XGb(b.b,null)}
function GWf(b){qHb(new K_e(b.b.p,b.b.p.p,b.b.b))}
function U_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function O_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function DBd(){var b;while(zBd){b=zBd;zBd=zBd.c;!zBd&&(ABd=null);GWf(b.b)}}
function T_e(b){var c,d;XGb(b.b,null);h4e(b.c,cEe(Iuh,Iuh));c=TEe();d=new Z_e(b.c);b.d?uFe(c,b.e,d):nGe(c,b.e,d_c(lXb(b.g),1),d)}
function GBd(){BBd=new EBd;JGc((GGc(),FGc),5);!!$stats&&$stats(yHc(Zai,YUg,-1,-1));BBd.cl();!!$stats&&$stats(yHc(Zai,O$g,-1,-1))}
function J_e(b,c){var d;c>1?(d=dEe(abi,bbi,Q$c(vxd,{113:1,175:1,177:1,321:1},1,[Jqg+c]))):d_c($U(d_c(b.k.jl(0),150),l1g),174).Sd(Dch)?(d=dEe(cbi,dbi,Q$c(vxd,{113:1,175:1,177:1,321:1},1,[d_c($U(b.s,fzg),1)]))):(d=dEe(zzh,Azh,Q$c(vxd,{113:1,175:1,177:1,321:1},1,[d_c($U(b.s,fzg),1)])));return d}
function nGe(c,d,e,g){var b,j,k,n,o;n=new KPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:M$g,evtGroup:n.b,method:$ai,millis:(new Date).getTime(),type:YUg});o=$Nd(c);try{SNd(o.b,Jqg+gNd(o,v3g));SNd(o.b,Jqg+gNd(o,_ai));SNd(o.b,wwg);SNd(o.b,Jqg+gNd(o,F3g));SNd(o.b,Jqg+gNd(o,e2g));mNd(o,d);SNd(o.b,Jqg+gNd(o,e));k=PNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:M$g,evtGroup:n.b,method:$ai,millis:(new Date).getTime(),type:g2g});_Nd(c,(yOd(),xOd),$ai,n,k,g)}catch(b){b=Ayd(b);if(g_c(b,311)){j=b;che(g,j)}else throw b}}
function K_e(b,c,d){r5();var e,g,i,j,k,n,o,p,q,r,s,t;sHb.call(this);a8(this,650,500);IIb(this.ub,ebi);!!this.E&&$O(PO(this.E,aJg),ebi);oHb(this,false);this.b=new u6b;IIb(this.b.ub,cEe(Qeh,Qeh));this.b.xb=false;x6(this.b,false);F6(this.b,fbi);Cxb(this.b,new Krc(0));a8(this.b,650,500);t=new fKb;jyb(this.b,t);p=new VRd;q=new VRd;for(n=c.k.Ud();n.$d();){k=d_c(n._d(),150);S$c(p.d,p.e++,k);ERd(q,d_c($U(k,N0g),1))}i=new ozb;Cxb(i,new npc);i.hc=0;i.Jc&&QO(MP(N5(i),Nvg),false);i.xb=false;this.c=y5e(p);a8(this.c,650,200);jyb(i,this.c);jyb(this.b,i);s=new gbc;a8(s,620,100);if(!d){jyb(this.b,new gKb(gbi+cEe(hAh,iAh)+hbi));jyb(this.b,s)}j=p.e;xX(this.c.I.g,new O_e(this,c,j,i,s,d,t));if(d){o=cEe(Bzh,ibi);jyb(this.b,new gKb(o));HIb(this.ub,(CMe(),AMe(),xMe))}r=new aGb(cEe(dxh,dxh),new U_e(this,b,d,q,s));g=new aGb(cEe(fxh,fxh),new e0e(this));e=new oWb;e.E=(QH(),NH);ZVb(e,r,e.Hb.e);ZVb(e,g,e.Hb.e);jyb(this.b,e);hzb(this,e);this.rh(this.b,this.Hb.e)}
var obi='620',pbi='70%',hbi=': <br />',gbi='<br />',jbi='<br /><br />',ibi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',qbi='AsyncLoader5',rbi='DeleteItemWindow',sbi='DeleteItemWindow$1',tbi='DeleteItemWindow$2',ubi='DeleteItemWindow$2$1',vbi='DeleteItemWindow$3',dbi='Do you really want to remove the selected PAGE {0}?',bbi='Do you really want to remove the {0} selected resources?',ebi='Informations',$ai='JahiaContentManagementService_Proxy.markForDeletion',fbi='JahiaGxtDeleteItem',nbi='This node is still used by:',lbi='Those nodes are still used in:',_ai='markForDeletion',abi='message.remove.multiple.confirm',kbi='message.remove.multiple.usage',cbi='message.remove.single.page.confirm',mbi='message.remove.single.usage',Zai='runCallbacks5';_=EBd.prototype=yBd.prototype=new HF;_.gC=function FBd(){return hcd};_.cl=function JBd(){DBd()};_.cM={};_=K_e.prototype=H_e.prototype=new LGb;_.gC=function L_e(){return qkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=O_e.prototype=M_e.prototype=new Vfb;_.gC=function P_e(){return mkd};_.ag=function Q_e(b){var c,d,e;c=d_c(b.d,174);d=c.Nd();e=J_e(this.d,this.e);if(d>0){e+=jbi+(this.e>1?cEe(kbi,lbi):cEe(mbi,nbi))}else{vyb(this.b.b,this.c);b8(this.i,obi,pbi);if(this.g){a8(this.b,-1,130);a8(this.b.b,-1,130)}}eKb(this.j,e);rxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=U_e.prototype=R_e.prototype=new Zgb;_.fg=function V_e(b){T_e(this,d_c(b,216))};_.gC=function W_e(){return okd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=Z_e.prototype=X_e.prototype=new _ge;_.gC=function $_e(){return nkd};_.Jl=function __e(b){g4e(this.b);b.fk();YNb(cEe($ch,PQg),b.fk())};_.ye=function a0e(b){g4e(this.b);l4e(this.b,63);p4e(this.b)};_.cM={};_.b=null;_=e0e.prototype=b0e.prototype=new Zgb;_.fg=function f0e(b){d0e(this,d_c(b,216))};_.gC=function g0e(){return pkd};_.cM={188:1};_.b=null;var hcd=Q1d(vPh,qbi),qkd=Q1d(VXh,rbi),mkd=Q1d(VXh,sbi),okd=Q1d(VXh,tbi),nkd=Q1d(VXh,ubi),pkd=Q1d(VXh,vbi);$entry(GBd)();