function cHd(){}
function YGd(){}
function Z3e(){}
function c4e(){}
function h4e(){}
function n4e(){}
function t4e(){}
function w4e(b){this.b=b}
function v4e(b){wJb(b.b,null)}
function p4e(b,c){this.b=b;this.c=c}
function bfg(b){RJb(new a4e(b.b.p,b.b.p.am(),b.b.b))}
function bHd(){var b;while(ZGd){b=ZGd;ZGd=ZGd.c;!ZGd&&($Gd=null);bfg(b.b)}}
function k4e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function e4e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function eHd(){_Gd=new cHd;DJc((AJc(),zJc),5);!!$stats&&$stats(sKc(KAi,Kch,-1,-1));_Gd.ll();!!$stats&&$stats(sKc(KAi,zih,-1,-1))}
function j4e(b){var c,d;wJb(b.b,null);b.c.dm(YJe(AOh,AOh));c=NKe();d=new p4e(b.c,b.e);b.d?oLe(c,b.g,d):kMe(c,b.g,A2c(AZb(b.i),1),d)}
function _3e(b,c){var d;c>1?(d=ZJe(NAi,OAi,l2c(VCd,{113:1,175:1,177:1,323:1},1,[cLg+c]))):A2c(TW(A2c(b.k.tl(0),150),ilh),174).Sd(Uvh)?(d=ZJe(PAi,QAi,l2c(VCd,{113:1,175:1,177:1,323:1},1,[A2c(TW(b.s,ATg),1)]))):(d=ZJe(nTh,oTh,l2c(VCd,{113:1,175:1,177:1,323:1},1,[A2c(TW(b.s,ATg),1)])));return d}
function kMe(c,d,e,g){var b,j,k,n,o;n=new kVd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xih,evtGroup:n.b,method:LAi,millis:(new Date).getTime(),type:Kch});o=ATd(c);try{sTd(o.b,cLg+ISd(o,pnh));sTd(o.b,cLg+ISd(o,MAi));sTd(o.b,RQg);sTd(o.b,cLg+ISd(o,znh));sTd(o.b,cLg+ISd(o,amh));OSd(o,d);sTd(o.b,cLg+ISd(o,e));k=pTd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:xih,evtGroup:n.b,method:LAi,millis:(new Date).getTime(),type:cmh});BTd(c,($Td(),ZTd),LAi,n,k,g)}catch(b){b=$Dd(b);if(D2c(b,313)){j=b;Rme(g,j)}else throw b}}
function a4e(b,c,d){s7();var e,g,i,j,k,n,o,p,q,r,s,t;TJb.call(this);fab(this,650,500);jLb(this.ub,RAi);!!this.E&&TQ(IQ(this.E,w1g),RAi);PJb(this,false);this.b=new J8b;jLb(this.b.ub,YJe($Eh,$Eh));this.b.xb=false;z8(this.b,false);I8(this.b,SAi);$zb(this.b,new cuc(0));fab(this.b,650,500);t=new KMb;KAb(this.b,t);p=new vXd;q=new vXd;for(n=c.k.Ud();n.$d();){k=A2c(n._d(),150);n2c(p.d,p.e++,k);eXd(q,A2c(TW(k,Lkh),1))}i=new PBb;$zb(i,new Wrc);i.hc=0;i.Jc&&JQ(FR(P7(i),fQg),false);i.xb=false;this.c=U9e(p);fab(this.c,650,200);KAb(i,this.c);KAb(this.b,i);s=new vdc;fab(s,620,100);if(!d){KAb(this.b,new LMb(TAi+YJe(MTh,NTh)+UAi));KAb(this.b,s)}j=p.e;qZ(this.c.I.g,new e4e(this,c,j,i,s,d,t));if(d){o=YJe(pTh,VAi);KAb(this.b,new LMb(o));iLb(this.ub,(NSe(),LSe(),ISe))}r=new BIb(YJe(QQh,QQh),new k4e(this,b,d,q,s,p));g=new BIb(YJe(SQh,SQh),new w4e(this));e=new DYb;e.E=(TJ(),QJ);mYb(e,r,e.Hb.e);mYb(e,g,e.Hb.e);KAb(this.b,e);IBb(this,e);this.uh(this.b,this.Hb.e)}
var _Ai='620',aBi='70%',UAi=': <br />',TAi='<br />',WAi='<br /><br />',VAi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',bBi='AsyncLoader5',cBi='DeleteItemWindow',dBi='DeleteItemWindow$1',eBi='DeleteItemWindow$2',fBi='DeleteItemWindow$2$1',gBi='DeleteItemWindow$3',QAi='Do you really want to remove the selected PAGE {0}?',OAi='Do you really want to remove the {0} selected resources?',RAi='Informations',LAi='JahiaContentManagementService_Proxy.markForDeletion',SAi='JahiaGxtDeleteItem',$Ai='This node is still used by:',YAi='Those nodes are still used in:',MAi='markForDeletion',NAi='message.remove.multiple.confirm',XAi='message.remove.multiple.usage',PAi='message.remove.single.page.confirm',ZAi='message.remove.single.usage',KAi='runCallbacks5';_=cHd.prototype=YGd.prototype=new KH;_.gC=function dHd(){return Gfd};_.ll=function hHd(){bHd()};_.cM={};_=a4e.prototype=Z3e.prototype=new kJb;_.gC=function b4e(){return Gnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=e4e.prototype=c4e.prototype=new iib;_.gC=function f4e(){return Cnd};_.cg=function g4e(b){var c,d,e;c=A2c(b.d,174);d=c.Nd();e=_3e(this.d,this.e);if(d>0){e+=WAi+(this.e>1?YJe(XAi,YAi):YJe(ZAi,$Ai))}else{WAb(this.b.b,this.c);gab(this.i,_Ai,aBi);if(this.g){fab(this.b,-1,130);fab(this.b.b,-1,130)}}JMb(this.j,e);Pzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=k4e.prototype=h4e.prototype=new tjb;_.ig=function l4e(b){j4e(this,A2c(b,216))};_.gC=function m4e(){return End};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=p4e.prototype=n4e.prototype=new Ome;_.gC=function q4e(){return Dnd};_.Tl=function r4e(b){this.b.cm();b.ok();GQb(YJe(pwh,qwh),b.ok())};_.ye=function s4e(b){var c;this.b.cm();c=null;D2c(this.b,354)?(c=A2c(this.b,354).d.u):D2c(this.b,355)&&(c=A2c(this.b,355));if(!!c&&mXd(this.c,A2c(TW(c.q.j,Lkh),1),0)!=-1){this.b.em(2);this.b.fm(null)}else{this.b.em(63);this.b.fm(null)}};_.cM={};_.b=null;_.c=null;_=w4e.prototype=t4e.prototype=new tjb;_.ig=function x4e(b){v4e(this,A2c(b,216))};_.gC=function y4e(){return Fnd};_.cM={188:1};_.b=null;var Gfd=D7d(H6h,bBi),Gnd=D7d(Tei,cBi),Cnd=D7d(Tei,dBi),End=D7d(Tei,eBi),Dnd=D7d(Tei,fBi),Fnd=D7d(Tei,gBi);$entry(eHd)();