function tGd(){}
function nGd(){}
function Q2e(){}
function V2e(){}
function $2e(){}
function e3e(){}
function k3e(){}
function n3e(b){this.b=b}
function m3e(b){pJb(b.b,null)}
function g3e(b,c){this.b=b;this.c=c}
function Udg(b){KJb(new T2e(b.b.p,b.b.p.$l(),b.b.b))}
function sGd(){var b;while(oGd){b=oGd;oGd=oGd.c;!oGd&&(pGd=null);Udg(b.b)}}
function b3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function X2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function vGd(){qGd=new tGd;wJc((tJc(),sJc),5);!!$stats&&$stats(lKc(Uyi,zbh,-1,-1));qGd.jl();!!$stats&&$stats(lKc(Uyi,Zgh,-1,-1))}
function a3e(b){var c,d;pJb(b.b,null);b.c.bm(PIe(MMh,MMh));c=EJe();d=new g3e(b.c,b.e);b.d?fKe(c,b.g,d):bLe(c,b.g,V1c(tZb(b.i),1),d)}
function S2e(b,c){var d;c>1?(d=QIe(Xyi,Yyi,G1c(kCd,{113:1,175:1,177:1,323:1},1,[VJg+c]))):V1c(LW(V1c(b.k.rl(0),150),sjh),174).Sd(cuh)?(d=QIe(Zyi,$yi,G1c(kCd,{113:1,175:1,177:1,323:1},1,[V1c(LW(b.s,oSg),1)]))):(d=QIe(zRh,ARh,G1c(kCd,{113:1,175:1,177:1,323:1},1,[V1c(LW(b.s,oSg),1)])));return d}
function bLe(c,d,e,g){var b,j,k,n,o;n=new qUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Xgh,evtGroup:n.b,method:Vyi,millis:(new Date).getTime(),type:zbh});o=GSd(c);try{ySd(o.b,VJg+ORd(o,zlh));ySd(o.b,VJg+ORd(o,Wyi));ySd(o.b,HPg);ySd(o.b,VJg+ORd(o,Jlh));ySd(o.b,VJg+ORd(o,kkh));URd(o,d);ySd(o.b,VJg+ORd(o,e));k=vSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Xgh,evtGroup:n.b,method:Vyi,millis:(new Date).getTime(),type:mkh});HSd(c,(eTd(),dTd),Vyi,n,k,g)}catch(b){b=pDd(b);if(Y1c(b,313)){j=b;Ile(g,j)}else throw b}}
function T2e(b,c,d){k7();var e,g,i,j,k,n,o,p,q,r,s,t;MJb.call(this);Z9(this,650,500);cLb(this.ub,_yi);!!this.E&&PQ(EQ(this.E,m0g),_yi);IJb(this,false);this.b=new C8b;cLb(this.b.ub,PIe(jDh,jDh));this.b.xb=false;r8(this.b,false);A8(this.b,azi);Tzb(this.b,new Xtc(0));Z9(this.b,650,500);t=new DMb;DAb(this.b,t);p=new BWd;q=new BWd;for(n=c.k.Ud();n.$d();){k=V1c(n._d(),150);I1c(p.d,p.e++,k);kWd(q,V1c(LW(k,Vih),1))}i=new IBb;Tzb(i,new Prc);i.hc=0;i.Jc&&FQ(BR(H7(i),WOg),false);i.xb=false;this.c=L8e(p);Z9(this.c,650,200);DAb(i,this.c);DAb(this.b,i);s=new odc;Z9(s,620,100);if(!d){DAb(this.b,new EMb(bzi+PIe(YRh,ZRh)+czi));DAb(this.b,s)}j=p.e;iZ(this.c.I.g,new X2e(this,c,j,i,s,d,t));if(d){o=PIe(BRh,dzi);DAb(this.b,new EMb(o));bLb(this.ub,(ERe(),CRe(),zRe))}r=new uIb(PIe(aPh,aPh),new b3e(this,b,d,q,s,p));g=new uIb(PIe(cPh,cPh),new n3e(this));e=new wYb;e.E=(PJ(),MJ);fYb(e,r,e.Hb.e);fYb(e,g,e.Hb.e);DAb(this.b,e);BBb(this,e);this.uh(this.b,this.Hb.e)}
var jzi='620',kzi='70%',czi=': <br />',bzi='<br />',ezi='<br /><br />',dzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',lzi='AsyncLoader5',mzi='DeleteItemWindow',nzi='DeleteItemWindow$1',ozi='DeleteItemWindow$2',pzi='DeleteItemWindow$2$1',qzi='DeleteItemWindow$3',$yi='Do you really want to remove the selected PAGE {0}?',Yyi='Do you really want to remove the {0} selected resources?',_yi='Informations',Vyi='JahiaContentManagementService_Proxy.markForDeletion',azi='JahiaGxtDeleteItem',izi='This node is still used by:',gzi='Those nodes are still used in:',Wyi='markForDeletion',Xyi='message.remove.multiple.confirm',fzi='message.remove.multiple.usage',Zyi='message.remove.single.page.confirm',hzi='message.remove.single.usage',Uyi='runCallbacks5';_=tGd.prototype=nGd.prototype=new GH;_.gC=function uGd(){return _ed};_.jl=function yGd(){sGd()};_.cM={};_=T2e.prototype=Q2e.prototype=new dJb;_.gC=function U2e(){return Xmd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=X2e.prototype=V2e.prototype=new aib;_.gC=function Y2e(){return Tmd};_.cg=function Z2e(b){var c,d,e;c=V1c(b.d,174);d=c.Nd();e=S2e(this.d,this.e);if(d>0){e+=ezi+(this.e>1?PIe(fzi,gzi):PIe(hzi,izi))}else{PAb(this.b.b,this.c);$9(this.i,jzi,kzi);if(this.g){Z9(this.b,-1,130);Z9(this.b.b,-1,130)}}CMb(this.j,e);Izb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=b3e.prototype=$2e.prototype=new ljb;_.ig=function c3e(b){a3e(this,V1c(b,216))};_.gC=function d3e(){return Vmd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=g3e.prototype=e3e.prototype=new Fle;_.gC=function h3e(){return Umd};_.Rl=function i3e(b){this.b.am();b.ok();zQb(PIe(zuh,Auh),b.ok())};_.ye=function j3e(b){var c;this.b.am();c=null;Y1c(this.b,354)?(c=V1c(this.b,354).d.u):Y1c(this.b,355)&&(c=V1c(this.b,355));if(!!c&&sWd(this.c,V1c(LW(c.q.j,Vih),1),0)!=-1){this.b.cm(2);this.b.dm(null)}else{this.b.cm(63);this.b.dm(null)}};_.cM={};_.b=null;_.c=null;_=n3e.prototype=k3e.prototype=new ljb;_.ig=function o3e(b){m3e(this,V1c(b,216))};_.gC=function p3e(){return Wmd};_.cM={188:1};_.b=null;var _ed=u6d(T4h,lzi),Xmd=u6d(_ci,mzi),Tmd=u6d(_ci,nzi),Vmd=u6d(_ci,ozi),Umd=u6d(_ci,pzi),Wmd=u6d(_ci,qzi);$entry(vGd)();