function org_jahia_ajax_gwt_module_edit_Edit(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',lc='.cache.html',_='/',Vb='0136BCAEEABF865459588BACD6AEE4D8',Wb='38429D6FBFD95F522DD7E6B95A5C67F8',Yb='3AAC80A9B387C19E844A5534D312AF85',$b='3B7A2DECF8716EB64968C5063633C6D0',_b='3C4D1FC511AFB27E5F089E0FAFACDCCC',ac='76021764552860E9888A9C87C3FFEDB3',kc=':',ob='::',nc='<script defer="defer">org_jahia_ajax_gwt_module_edit_Edit.onInjectionDone(\'org.jahia.ajax.gwt.module.edit.Edit\')<\/script>',hb='<script id="',rb='=',$='?',bc='A65EA2ADA0A8B99FC2D9C3F4E37D7504',cc='ABAA52B1875850E47E9C10A7383ED438',dc='BCE9493497594CF996F4F6E8997892C6',tb='Bad handler "',ec='CF611F87F27E2490AB059C9C936152F3',fc='DE35B8C87828C08621DCDB7F35C592B6',mc='DOMContentLoaded',gc='E7FC8F27E0667E14AEA2BFE708A3D9EC',hc='EDA98A8DBC5EC4EACD753E802320712A',ic='F1EB5180D1F353DB3D6ADB62FBBF3AB1',jc='FA18091593197429A38F52FE642F06F0',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_org.jahia.ajax.gwt.module.edit.Edit',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Xb='de',Cb='en',Y='end',Zb='fr',Pb='gecko',Qb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Tb='hosted.html?org_jahia_ajax_gwt_module_edit_Edit',Ob='ie6',Nb='ie8',xb='iframe',ab='img',yb="javascript:''",Sb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',Q='org.jahia.ajax.gwt.module.edit.Edit',eb='org.jahia.ajax.gwt.module.edit.Edit.nocache.js',nb='org.jahia.ajax.gwt.module.edit.Edit::',zb='position:absolute;width:0;height:0;border:none',Lb='safari',db='script',Ub='selectingPermutation',R='startup',fb='undefined',Rb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}org_jahia_ajax_gwt_module_edit_Edit=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={de:0,'default':1,en:2,fr:3};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Jb)!=-1){return Jb}else if(b.indexOf(Kb)!=-1){return Lb}else if(b.indexOf(Mb)!=-1){if(document.documentMode>=8){return Nb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Ob}}}}else if(b.indexOf(Pb)!=-1){return Qb}return Rb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};org_jahia_ajax_gwt_module_edit_Edit.onScriptLoad=function(){if(I){q=true;B()}};org_jahia_ajax_gwt_module_edit_Edit.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Tb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Ub});if(!A()){try{G([Cb,Lb],Vb);G([Cb,Ob],Wb);G([Xb,Nb],Yb);G([Zb,Nb],$b);G([Xb,Qb],_b);G([Xb,Jb],ac);G([Xb,Lb],bc);G([Zb,Qb],cc);G([Cb,Qb],dc);G([Zb,Ob],ec);G([Xb,Ob],fc);G([Cb,Jb],gc);G([Zb,Jb],hc);G([Cb,Nb],ic);G([Zb,Lb],jc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(kc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+lc}catch(a){return}}var N;function O(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(mc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(mc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:T});m.write(nc)}
org_jahia_ajax_gwt_module_edit_Edit();