function YFd(){}
function SFd(){}
function H2e(){}
function M2e(){}
function R2e(){}
function X2e(){}
function b3e(){}
function e3e(b){this.b=b}
function d3e(b){tJb(b.b,null)}
function Z2e(b,c){this.b=b;this.c=c}
function Ldg(b){OJb(new K2e(b.b.p,b.b.p.Rl(),b.b.b))}
function XFd(){var b;while(TFd){b=TFd;TFd=TFd.c;!TFd&&(UFd=null);Ldg(b.b)}}
function U2e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function O2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function $Fd(){VFd=new YFd;zJc((wJc(),vJc),5);!!$stats&&$stats(oKc(Zxi,xbh,-1,-1));VFd.al();!!$stats&&$stats(oKc(Zxi,kgh,-1,-1))}
function T2e(b){var c,d;tJb(b.b,null);b.c.Ul(GIe(ULh,ULh));c=vJe();d=new Z2e(b.c,b.e);b.d?YJe(c,b.g,d):UKe(c,b.g,x1c(xZb(b.i),1),d)}
function J2e(b,c){var d;c>1?(d=HIe(ayi,byi,i1c(PBd,{113:1,175:1,177:1,323:1},1,[MJg+c]))):x1c(QW(x1c(b.k.il(0),150),Fih),174).Sd(pth)?(d=HIe(cyi,dyi,i1c(PBd,{113:1,175:1,177:1,323:1},1,[x1c(QW(b.s,eSg),1)]))):(d=HIe(FQh,GQh,i1c(PBd,{113:1,175:1,177:1,323:1},1,[x1c(QW(b.s,eSg),1)])));return d}
function UKe(c,d,e,g){var b,j,k,n,o;n=new dUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:igh,evtGroup:n.b,method:$xi,millis:(new Date).getTime(),type:xbh});o=tSd(c);try{lSd(o.b,MJg+BRd(o,Mkh));lSd(o.b,MJg+BRd(o,_xi));lSd(o.b,zPg);lSd(o.b,MJg+BRd(o,Wkh));lSd(o.b,MJg+BRd(o,xjh));HRd(o,d);lSd(o.b,MJg+BRd(o,e));k=iSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:igh,evtGroup:n.b,method:$xi,millis:(new Date).getTime(),type:zjh});uSd(c,(TSd(),SSd),$xi,n,k,g)}catch(b){b=UCd(b);if(A1c(b,313)){j=b;zle(g,j)}else throw b}}
function K2e(b,c,d){p7();var e,g,i,j,k,n,o,p,q,r,s,t;QJb.call(this);cab(this,650,500);gLb(this.ub,eyi);!!this.E&&QQ(FQ(this.E,k0g),eyi);MJb(this,false);this.b=new G8b;gLb(this.b.ub,GIe(uCh,uCh));this.b.xb=false;w8(this.b,false);F8(this.b,fyi);Xzb(this.b,new _tc(0));cab(this.b,650,500);t=new HMb;HAb(this.b,t);p=new oWd;q=new oWd;for(n=c.k.Ud();n.$d();){k=x1c(n._d(),150);k1c(p.d,p.e++,k);ZVd(q,x1c(QW(k,gih),1))}i=new MBb;Xzb(i,new Trc);i.hc=0;i.Jc&&GQ(CR(M7(i),POg),false);i.xb=false;this.c=C8e(p);cab(this.c,650,200);HAb(i,this.c);HAb(this.b,i);s=new sdc;cab(s,620,100);if(!d){HAb(this.b,new IMb(gyi+GIe(cRh,dRh)+hyi));HAb(this.b,s)}j=p.e;nZ(this.c.I.g,new O2e(this,c,j,i,s,d,t));if(d){o=GIe(HQh,iyi);HAb(this.b,new IMb(o));fLb(this.ub,(vRe(),tRe(),qRe))}r=new yIb(GIe(iOh,iOh),new U2e(this,b,d,q,s,p));g=new yIb(GIe(jOh,jOh),new e3e(this));e=new AYb;e.E=(QJ(),NJ);jYb(e,r,e.Hb.e);jYb(e,g,e.Hb.e);HAb(this.b,e);FBb(this,e);this.uh(this.b,this.Hb.e)}
var oyi='620',pyi='70%',hyi=': <br />',gyi='<br />',jyi='<br /><br />',iyi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',qyi='AsyncLoader5',ryi='DeleteItemWindow',syi='DeleteItemWindow$1',tyi='DeleteItemWindow$2',uyi='DeleteItemWindow$2$1',vyi='DeleteItemWindow$3',dyi='Do you really want to remove the selected PAGE {0}?',byi='Do you really want to remove the {0} selected resources?',eyi='Informations',$xi='JahiaContentManagementService_Proxy.markForDeletion',fyi='JahiaGxtDeleteItem',nyi='This node is still used by:',lyi='Those nodes are still used in:',_xi='markForDeletion',ayi='message.remove.multiple.confirm',kyi='message.remove.multiple.usage',cyi='message.remove.single.page.confirm',myi='message.remove.single.usage',Zxi='runCallbacks5';_=YFd.prototype=SFd.prototype=new HH;_.gC=function ZFd(){return Ced};_.al=function bGd(){XFd()};_.cM={};_=K2e.prototype=H2e.prototype=new hJb;_.gC=function L2e(){return Amd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=O2e.prototype=M2e.prototype=new fib;_.gC=function P2e(){return wmd};_.cg=function Q2e(b){var c,d,e;c=x1c(b.d,174);d=c.Nd();e=J2e(this.d,this.e);if(d>0){e+=jyi+(this.e>1?GIe(kyi,lyi):GIe(myi,nyi))}else{TAb(this.b.b,this.c);dab(this.i,oyi,pyi);if(this.g){cab(this.b,-1,130);cab(this.b.b,-1,130)}}GMb(this.j,e);Mzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=U2e.prototype=R2e.prototype=new qjb;_.ig=function V2e(b){T2e(this,x1c(b,216))};_.gC=function W2e(){return ymd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=Z2e.prototype=X2e.prototype=new wle;_.gC=function $2e(){return xmd};_.Il=function _2e(b){this.b.Tl();b.ok();DQb(GIe(Mth,Nth),b.ok())};_.ye=function a3e(b){var c;this.b.Tl();c=null;A1c(this.b,354)?(c=x1c(this.b,354).d.u):A1c(this.b,355)&&(c=x1c(this.b,355));if(!!c&&fWd(this.c,x1c(QW(c.q.j,gih),1),0)!=-1){this.b.Vl(2);this.b.Wl(null)}else{this.b.Vl(63);this.b.Wl(null)}};_.cM={};_.b=null;_.c=null;_=e3e.prototype=b3e.prototype=new qjb;_.ig=function f3e(b){d3e(this,x1c(b,216))};_.gC=function g3e(){return zmd};_.cM={188:1};_.b=null;var Ced=l6d(Y3h,qyi),Amd=l6d(gci,ryi),wmd=l6d(gci,syi),ymd=l6d(gci,tyi),xmd=l6d(gci,uyi),zmd=l6d(gci,vyi);$entry($Fd)();