function ISc(){}
function FSc(){}
function HGd(){}
function BGd(){}
function N5e(){}
function V5e(){}
function T5e(){}
function X5e(){}
function b6e(){}
function h6e(){}
function $5e(b){this.b=b}
function Z5e(b){wJb(b.b,null)}
function odg(b){RJb(new R5e(b.b.p,b.b.p._l().s))}
function HSc(){HSc=lFg;GSc=new MRc(whh,new ISc)}
function GGd(){var b;while(CGd){b=CGd;CGd=CGd.c;!CGd&&(DGd=null);odg(b.b)}}
function P5e(b,c,d,e,g,i,j,k){jLe(LKe(),c,d,e,g,i,j,k,new j6e(b,c,d,e,g,i,j))}
function j6e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function e6e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function JGd(){EGd=new HGd;DJc((AJc(),zJc),4);!!$stats&&$stats(sKc(qAi,Ich,-1,-1));EGd.kl();!!$stats&&$stats(sKc(qAi,Bih,-1,-1))}
function Q5e(){$wnd.jQuery(tAi).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(uAi).val(b.x);$wnd.jQuery(vAi).val(b.y);$wnd.jQuery(wAi).val(b.w);$wnd.jQuery(xAi).val(b.h)}})}
function d6e(b){y2c(AZb(b.j),119).Hl()>0&&y2c(AZb(b.c),119).Hl()>0&&P5e(b.b,y2c(TW(b.e,Nkh),1),y2c(b.g.ce(),1),y2c(AZb(b.i),119).Hl(),y2c(AZb(b.d),119).Hl(),y2c(AZb(b.j),119).Hl(),y2c(AZb(b.c),119).Hl(),false)}
function jLe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new iVd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:zih,evtGroup:r.b,method:rAi,millis:(new Date).getTime(),type:Ich});s=yTd(c);try{qTd(s.b,aLg+GSd(s,rnh));qTd(s.b,aLg+GSd(s,sAi));qTd(s.b,Nnh);qTd(s.b,aLg+GSd(s,cmh));qTd(s.b,aLg+GSd(s,cmh));qTd(s.b,aLg+GSd(s,dmh));qTd(s.b,aLg+GSd(s,dmh));qTd(s.b,aLg+GSd(s,dmh));qTd(s.b,aLg+GSd(s,dmh));qTd(s.b,aLg+GSd(s,Inh));qTd(s.b,aLg+GSd(s,d));qTd(s.b,aLg+GSd(s,e));qTd(s.b,aLg+g);qTd(s.b,aLg+i);qTd(s.b,aLg+j);qTd(s.b,aLg+k);qTd(s.b,n?HPg:qOg);q=nTd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:zih,evtGroup:r.b,method:rAi,millis:(new Date).getTime(),type:emh});zTd(c,(YTd(),XTd),rAi,r,q,o)}catch(b){b=YDd(b);if(!B2c(b,313))throw b}}
function R5e(b,c){s7();var d,e,g,i,j,k,n,o,p,q,r,s;TJb.call(this);$zb(this,new Wrc);fab(this,712,550);this.b=b;KJb(this,WJe(yAi,yAi));this.Ac=zAi;!!this.sc&&(P7(this).id=zAi,undefined);j=new J8b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&JQ(FR(P7(j),dQg),false);p=new S0b;p.Ei(AAi);i=y2c(TW(c,wTg),1).lastIndexOf(rOg);if(i>0){g=Iae(y2c(TW(c,wTg),1),i);p.Hi(Fae(y2c(TW(c,wTg),1),g,BAi+g))}else{p.Hi(y2c(TW(c,wTg),1)+BAi)}TZb(p,WJe(Zyh,Zyh));PAb(j,p,j.Hb.e);r=new mbc;VZb(r,TLg);r.Ac=TLg;!!r.sc&&(P7(r).id=TLg,undefined);Y7(r);PAb(j,r,j.Hb.e);o=new mbc;VZb(o,SLg);o.Ac=SLg;!!o.sc&&(P7(o).id=SLg,undefined);Y7(o);PAb(j,o,j.Hb.e);s=new mbc;TZb(s,WJe(CAi,yCh));M8(s,DAi);VZb(s,fMg);s.Ac=fMg;!!s.sc&&(P7(s).id=fMg,undefined);S8(s);C7(s);PAb(j,s,j.Hb.e);k=new mbc;TZb(k,WJe(EAi,DCh));M8(k,FAi);VZb(k,eMg);k.Ac=eMg;!!k.sc&&(P7(k).id=eMg,undefined);S8(k);C7(k);PAb(j,k,j.Hb.e);n=new M0d;U6(n,new V5e,(HSc(),HSc(),GSc));n.ad.id=GAi;L0d(n,c.A);PAb(j,n,j.Hb.e);d=new DYb;e=new BIb(WJe(pyh,pyh),new $5e(this));q=new BIb(WJe(zyh,zyh),new e6e(this,s,k,c,p,r,o));mYb(d,q,d.Hb.e);mYb(d,e,d.Hb.e);JBb(this,(TJ(),QJ));IBb(this,d);Nzb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var tAi='#cropbox',xAi='#height-input',uAi='#left-input',vAi='#top-input',wAi='#width-input',IAi='AsyncLoader4',JAi='ImageCrop',KAi='ImageCrop$1',LAi='ImageCrop$2',MAi='ImageCrop$3',NAi='ImageCrop$4',rAi='JahiaContentManagementService_Proxy.cropImage',zAi='JahiaGxtImageCrop',BAi='_crop',sAi='cropImage',GAi='cropbox',HAi='failure.crop.label',yAi='label.crop',EAi='label.height',CAi='label.width',qAi='runCallbacks4',FAi='stylehight',DAi='stylewidth';_=ISc.prototype=FSc.prototype=new TQc;_.tk=function JSc(b){y2c(b,290);Q5e()};_.wk=function KSc(){return GSc};_.gC=function LSc(){return ted};_.cM={};var GSc;_=HGd.prototype=BGd.prototype=new KH;_.gC=function IGd(){return Bfd};_.kl=function MGd(){GGd()};_.cM={};_=R5e.prototype=N5e.prototype=new kJb;_.gC=function S5e(){return Vnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_=V5e.prototype=T5e.prototype=new KH;_.gC=function W5e(){return Rnd};_.cM={290:1,294:1};_=$5e.prototype=X5e.prototype=new tjb;_.ig=function _5e(b){Z5e(this,y2c(b,216))};_.gC=function a6e(){return Snd};_.cM={188:1};_.b=null;_=e6e.prototype=b6e.prototype=new tjb;_.ig=function f6e(b){d6e(this,y2c(b,216))};_.gC=function g6e(){return Tnd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=j6e.prototype=h6e.prototype=new Mme;_.gC=function k6e(){return Und};_.Sl=function l6e(b){if(b!=null&&b.cM&&!!b.cM[353]){$wnd.confirm(WJe(lBh,lBh)+qbh+WJe(XSh,XSh))&&P5e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(WJe(HAi,HAi)+qbh+b.ok());WJe(HAi,HAi)}};_.ye=function m6e(b){wJb(this.b,null);this.b.b.dm(1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var ted=B7d(t5h,eWh),Bfd=B7d(J6h,IAi),Vnd=B7d(Vei,JAi),Rnd=B7d(Vei,KAi),Snd=B7d(Vei,LAi),Tnd=B7d(Vei,MAi),Und=B7d(Vei,NAi);$entry(JGd)();