function aHd(){}
function WGd(){}
function X3e(){}
function a4e(){}
function f4e(){}
function l4e(){}
function r4e(){}
function u4e(b){this.b=b}
function t4e(b){wJb(b.b,null)}
function n4e(b,c){this.b=b;this.c=c}
function _eg(b){RJb(new $3e(b.b.p,b.b.p._l(),b.b.b))}
function _Gd(){var b;while(XGd){b=XGd;XGd=XGd.c;!XGd&&(YGd=null);_eg(b.b)}}
function i4e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function c4e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function cHd(){ZGd=new aHd;DJc((AJc(),zJc),5);!!$stats&&$stats(sKc(OAi,Ich,-1,-1));ZGd.kl();!!$stats&&$stats(sKc(OAi,Bih,-1,-1))}
function h4e(b){var c,d;wJb(b.b,null);b.c.cm(WJe(COh,COh));c=LKe();d=new n4e(b.c,b.e);b.d?mLe(c,b.g,d):iMe(c,b.g,y2c(AZb(b.i),1),d)}
function Z3e(b,c){var d;c>1?(d=XJe(RAi,SAi,j2c(TCd,{113:1,175:1,177:1,323:1},1,[aLg+c]))):y2c(TW(y2c(b.k.sl(0),150),klh),174).Sd(Wvh)?(d=XJe(TAi,UAi,j2c(TCd,{113:1,175:1,177:1,323:1},1,[y2c(TW(b.s,wTg),1)]))):(d=XJe(pTh,qTh,j2c(TCd,{113:1,175:1,177:1,323:1},1,[y2c(TW(b.s,wTg),1)])));return d}
function iMe(c,d,e,g){var b,j,k,n,o;n=new iVd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:zih,evtGroup:n.b,method:PAi,millis:(new Date).getTime(),type:Ich});o=yTd(c);try{qTd(o.b,aLg+GSd(o,rnh));qTd(o.b,aLg+GSd(o,QAi));qTd(o.b,PQg);qTd(o.b,aLg+GSd(o,Bnh));qTd(o.b,aLg+GSd(o,cmh));MSd(o,d);qTd(o.b,aLg+GSd(o,e));k=nTd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:zih,evtGroup:n.b,method:PAi,millis:(new Date).getTime(),type:emh});zTd(c,(YTd(),XTd),PAi,n,k,g)}catch(b){b=YDd(b);if(B2c(b,313)){j=b;Pme(g,j)}else throw b}}
function $3e(b,c,d){s7();var e,g,i,j,k,n,o,p,q,r,s,t;TJb.call(this);fab(this,650,500);jLb(this.ub,VAi);!!this.E&&TQ(IQ(this.E,u1g),VAi);PJb(this,false);this.b=new J8b;jLb(this.b.ub,WJe(bFh,bFh));this.b.xb=false;z8(this.b,false);I8(this.b,WAi);$zb(this.b,new cuc(0));fab(this.b,650,500);t=new KMb;KAb(this.b,t);p=new tXd;q=new tXd;for(n=c.k.Ud();n.$d();){k=y2c(n._d(),150);l2c(p.d,p.e++,k);cXd(q,y2c(TW(k,Nkh),1))}i=new PBb;$zb(i,new Wrc);i.hc=0;i.Jc&&JQ(FR(P7(i),dQg),false);i.xb=false;this.c=S9e(p);fab(this.c,650,200);KAb(i,this.c);KAb(this.b,i);s=new vdc;fab(s,620,100);if(!d){KAb(this.b,new LMb(XAi+WJe(OTh,PTh)+YAi));KAb(this.b,s)}j=p.e;qZ(this.c.I.g,new c4e(this,c,j,i,s,d,t));if(d){o=WJe(rTh,ZAi);KAb(this.b,new LMb(o));iLb(this.ub,(LSe(),JSe(),GSe))}r=new BIb(WJe(SQh,SQh),new i4e(this,b,d,q,s,p));g=new BIb(WJe(UQh,UQh),new u4e(this));e=new DYb;e.E=(TJ(),QJ);mYb(e,r,e.Hb.e);mYb(e,g,e.Hb.e);KAb(this.b,e);IBb(this,e);this.uh(this.b,this.Hb.e)}
var dBi='620',eBi='70%',YAi=': <br />',XAi='<br />',$Ai='<br /><br />',ZAi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',fBi='AsyncLoader5',gBi='DeleteItemWindow',hBi='DeleteItemWindow$1',iBi='DeleteItemWindow$2',jBi='DeleteItemWindow$2$1',kBi='DeleteItemWindow$3',UAi='Do you really want to remove the selected PAGE {0}?',SAi='Do you really want to remove the {0} selected resources?',VAi='Informations',PAi='JahiaContentManagementService_Proxy.markForDeletion',WAi='JahiaGxtDeleteItem',cBi='This node is still used by:',aBi='Those nodes are still used in:',QAi='markForDeletion',RAi='message.remove.multiple.confirm',_Ai='message.remove.multiple.usage',TAi='message.remove.single.page.confirm',bBi='message.remove.single.usage',OAi='runCallbacks5';_=aHd.prototype=WGd.prototype=new KH;_.gC=function bHd(){return Efd};_.kl=function fHd(){_Gd()};_.cM={};_=$3e.prototype=X3e.prototype=new kJb;_.gC=function _3e(){return End};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=c4e.prototype=a4e.prototype=new iib;_.gC=function d4e(){return And};_.cg=function e4e(b){var c,d,e;c=y2c(b.d,174);d=c.Nd();e=Z3e(this.d,this.e);if(d>0){e+=$Ai+(this.e>1?WJe(_Ai,aBi):WJe(bBi,cBi))}else{WAb(this.b.b,this.c);gab(this.i,dBi,eBi);if(this.g){fab(this.b,-1,130);fab(this.b.b,-1,130)}}JMb(this.j,e);Pzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=i4e.prototype=f4e.prototype=new tjb;_.ig=function j4e(b){h4e(this,y2c(b,216))};_.gC=function k4e(){return Cnd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=n4e.prototype=l4e.prototype=new Mme;_.gC=function o4e(){return Bnd};_.Sl=function p4e(b){this.b.bm();b.ok();GQb(WJe(rwh,swh),b.ok())};_.ye=function q4e(b){var c;this.b.bm();c=null;B2c(this.b,354)?(c=y2c(this.b,354).d.u):B2c(this.b,355)&&(c=y2c(this.b,355));if(!!c&&kXd(this.c,y2c(TW(c.q.j,Nkh),1),0)!=-1){this.b.dm(2);this.b.em(null)}else{this.b.dm(63);this.b.em(null)}};_.cM={};_.b=null;_.c=null;_=u4e.prototype=r4e.prototype=new tjb;_.ig=function v4e(b){t4e(this,y2c(b,216))};_.gC=function w4e(){return Dnd};_.cM={188:1};_.b=null;var Efd=B7d(J6h,fBi),End=B7d(Vei,gBi),And=B7d(Vei,hBi),Cnd=B7d(Vei,iBi),Bnd=B7d(Vei,jBi),Dnd=B7d(Vei,kBi);$entry(cHd)();