function dPc(){}
function aPc(){}
function a1e(){}
function G0e(){}
function O0e(){}
function M0e(){}
function Q0e(){}
function W0e(){}
function xAd(){}
function rAd(){}
function T0e(b){this.b=b}
function S0e(b){TGb(b.b,null)}
function xWd(b,c){b.b.kl(b,c)}
function cUf(b){mHb(new K0e(b.b.p,b.b.p.p.s))}
function cPc(){cPc=Xjg;bPc=new hOc(SXg,new dPc)}
function yWd(){uWd();this.b=new ZWd(this);this.ad[ssg]=qZg}
function wAd(){var b;while(sAd){b=sAd;sAd=sAd.c;!sAd&&(tAd=null);cUf(b.b)}}
function I0e(b,c,d,e,g,i,j,k){AEe(aEe(),c,d,e,g,i,j,k,new c1e(b,c,d,e,g,i,j))}
function c1e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function Z0e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function zAd(){uAd=new xAd;GGc((DGc(),CGc),4);!!$stats&&$stats(vHc(m8h,gUg,-1,-1));uAd.Sk();!!$stats&&$stats(vHc(m8h,EYg,-1,-1))}
function J0e(){$wnd.jQuery(p8h).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(q8h).val(b.x);$wnd.jQuery(r8h).val(b.y);$wnd.jQuery(s8h).val(b.w);$wnd.jQuery(t8h).val(b.h)}})}
function Y0e(b){s$c(hXb(b.j),119).ml()>0&&s$c(hXb(b.c),119).ml()>0&&I0e(b.b,s$c(VU(b.e,D$g),1),s$c(b.g.ce(),1),s$c(hXb(b.i),119).ml(),s$c(hXb(b.d),119).ml(),s$c(hXb(b.j),119).ml(),s$c(hXb(b.c),119).ml(),false)}
function AEe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new OOd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:CYg,evtGroup:r.b,method:n8h,millis:(new Date).getTime(),type:gUg});s=cNd(c);try{WMd(s.b,Spg+kMd(s,l1g));WMd(s.b,Spg+kMd(s,o8h));WMd(s.b,M1g);WMd(s.b,Spg+kMd(s,W_g));WMd(s.b,Spg+kMd(s,W_g));WMd(s.b,Spg+kMd(s,X_g));WMd(s.b,Spg+kMd(s,X_g));WMd(s.b,Spg+kMd(s,X_g));WMd(s.b,Spg+kMd(s,X_g));WMd(s.b,Spg+kMd(s,E1g));WMd(s.b,Spg+kMd(s,d));WMd(s.b,Spg+kMd(s,e));WMd(s.b,Spg+g);WMd(s.b,Spg+i);WMd(s.b,Spg+j);WMd(s.b,Spg+k);WMd(s.b,n?yug:itg);q=TMd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:CYg,evtGroup:r.b,method:n8h,millis:(new Date).getTime(),type:Y_g});dNd(c,(CNd(),BNd),n8h,r,q,o)}catch(b){b=Oxd(b);if(!v$c(b,311))throw b}}
function K0e(b,c){m5();var d,e,g,i,j,k,n,o,p,q,r,s;oHb.call(this);yxb(this,new jpc);X7(this,712,550);this.b=b;fHb(this,lDe(u8h,u8h));this.Ac=v8h;!!this.sc&&(I5(this).id=v8h,undefined);j=new q6b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&PO(LP(I5(j),Uug),false);p=new z$b;p.vi(w8h);i=s$c(VU(c,jyg),1).lastIndexOf(jtg);if(i>0){g=e4d(s$c(VU(c,jyg),1),i);p.yi(b4d(s$c(VU(c,jyg),1),g,x8h+g))}else{p.yi(s$c(VU(c,jyg),1)+x8h)}AXb(p,lDe(Idh,Idh));kyb(j,p,j.Hb.e);r=new V8b;CXb(r,Mqg);r.Ac=Mqg;!!r.sc&&(I5(r).id=Mqg,undefined);R5(r);kyb(j,r,j.Hb.e);o=new V8b;CXb(o,Lqg);o.Ac=Lqg;!!o.sc&&(I5(o).id=Lqg,undefined);R5(o);kyb(j,o,j.Hb.e);s=new V8b;AXb(s,lDe(y8h,Nhh));E6(s,z8h);CXb(s,$qg);s.Ac=$qg;!!s.sc&&(I5(s).id=$qg,undefined);K6(s);w5(s);kyb(j,s,j.Hb.e);k=new V8b;AXb(k,lDe(A8h,Shh));E6(k,B8h);CXb(k,Zqg);k.Ac=Zqg;!!k.sc&&(I5(k).id=Zqg,undefined);K6(k);w5(k);kyb(j,k,j.Hb.e);n=new yWd;O4(n,new O0e,(cPc(),cPc(),bPc));n.ad.id=C8h;xWd(n,c.A);kyb(j,n,j.Hb.e);d=new kWb;e=new YFb(lDe(Zch,Zch),new T0e(this));q=new YFb(lDe(hdh,hdh),new Z0e(this,s,k,c,p,r,o));VVb(d,q,d.Hb.e);VVb(d,e,d.Hb.e);ezb(this,(PH(),MH));dzb(this,d);lxb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var p8h='#cropbox',t8h='#height-input',q8h='#left-input',r8h='#top-input',s8h='#width-input',E8h='AsyncLoader4',F8h='ImageCrop',G8h='ImageCrop$1',H8h='ImageCrop$2',I8h='ImageCrop$3',J8h='ImageCrop$4',n8h='JahiaContentManagementService_Proxy.cropImage',v8h='JahiaGxtImageCrop',x8h='_crop',o8h='cropImage',C8h='cropbox',D8h='failure.crop.label',u8h='label.crop',A8h='label.height',y8h='label.width',m8h='runCallbacks4',B8h='stylehight',z8h='stylewidth';_=dPc.prototype=aPc.prototype=new oNc;_.jk=function ePc(b){s$c(b,288);J0e()};_.mk=function fPc(){return bPc};_.gC=function gPc(){return lad};_.cM={};var bPc;_=xAd.prototype=rAd.prototype=new GF;_.gC=function yAd(){return sbd};_.Sk=function CAd(){wAd()};_.cM={};_=yWd.prototype=tWd.prototype;_=EWd.prototype;_.kl=function PWd(b,c){b.b=new ZWd(b);b.b.kl(b,c)};_=VWd.prototype;_.kl=function cXd(b,c){!!b.b&&(b.b.il(b)[rZg]=Spg,undefined);b.ad.src=c};_=K0e.prototype=G0e.prototype=new HGb;_.gC=function L0e(){return Vjd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_=O0e.prototype=M0e.prototype=new GF;_.gC=function P0e(){return Rjd};_.cM={288:1,292:1};_=T0e.prototype=Q0e.prototype=new Ugb;_.fg=function U0e(b){S0e(this,s$c(b,216))};_.gC=function V0e(){return Sjd};_.cM={188:1};_.b=null;_=Z0e.prototype=W0e.prototype=new Ugb;_.fg=function $0e(b){Y0e(this,s$c(b,216))};_.gC=function _0e(){return Tjd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=c1e.prototype=a1e.prototype=new ige;_.gC=function d1e(){return Ujd};_.xl=function e1e(b){if(b!=null&&b.cM&&!!b.cM[354]){$wnd.confirm(lDe(Xfh,Xfh)+QSg+lDe(Twh,Twh))&&I0e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(lDe(D8h,D8h)+QSg+b.fk());lDe(D8h,D8h)}};_.ye=function f1e(b){TGb(this.b,null);u3e(this.b.b,1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var lad=Z0d(ULh,pAh),sbd=Z0d(gNh,E8h),Vjd=Z0d(GVh,F8h),Rjd=Z0d(GVh,G8h),Sjd=Z0d(GVh,H8h),Tjd=Z0d(GVh,I8h),Ujd=Z0d(GVh,J8h);$entry(zAd)();