function SAd(){}
function MAd(){}
function Q$e(){}
function V$e(){}
function $$e(){}
function e_e(){}
function k_e(){}
function g_e(b){this.b=b}
function n_e(b){this.b=b}
function m_e(b){TGb(b.b,null)}
function PVf(b){mHb(new T$e(b.b.p,b.b.p.p,b.b.b))}
function b_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function X$e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function RAd(){var b;while(NAd){b=NAd;NAd=NAd.c;!NAd&&(OAd=null);PVf(b.b)}}
function a_e(b){var c,d;TGb(b.b,null);q3e(b.c,lDe(wsh,wsh));c=aEe();d=new g_e(b.c);b.d?DEe(c,b.e,d):wFe(c,b.e,s$c(hXb(b.g),1),d)}
function UAd(){PAd=new SAd;GGc((DGc(),CGc),5);!!$stats&&$stats(vHc(K8h,gUg,-1,-1));PAd.Sk();!!$stats&&$stats(vHc(K8h,EYg,-1,-1))}
function S$e(b,c){var d;c>1?(d=mDe(N8h,O8h,d$c(Jwd,{113:1,175:1,177:1,321:1},1,[Spg+c]))):s$c(VU(s$c(b.k.Zk(0),150),b_g),174).Sd(tah)?(d=mDe(P8h,Q8h,d$c(Jwd,{113:1,175:1,177:1,321:1},1,[s$c(VU(b.s,jyg),1)]))):(d=mDe(lxh,mxh,d$c(Jwd,{113:1,175:1,177:1,321:1},1,[s$c(VU(b.s,jyg),1)])));return d}
function wFe(c,d,e,g){var b,j,k,n,o;n=new OOd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:CYg,evtGroup:n.b,method:L8h,millis:(new Date).getTime(),type:gUg});o=cNd(c);try{WMd(o.b,Spg+kMd(o,l1g));WMd(o.b,Spg+kMd(o,M8h));WMd(o.b,Evg);WMd(o.b,Spg+kMd(o,v1g));WMd(o.b,Spg+kMd(o,W_g));qMd(o,d);WMd(o.b,Spg+kMd(o,e));k=TMd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:CYg,evtGroup:n.b,method:L8h,millis:(new Date).getTime(),type:Y_g});dNd(c,(CNd(),BNd),L8h,n,k,g)}catch(b){b=Oxd(b);if(v$c(b,311)){j=b;lge(g,j)}else throw b}}
function T$e(b,c,d){m5();var e,g,i,j,k,n,o,p,q,r,s,t;oHb.call(this);X7(this,650,500);EIb(this.ub,R8h);!!this.E&&ZO(OO(this.E,oIg),R8h);kHb(this,false);this.b=new q6b;EIb(this.b.ub,lDe(Fch,Fch));this.b.xb=false;s6(this.b,false);A6(this.b,S8h);yxb(this.b,new Grc(0));X7(this.b,650,500);t=new bKb;fyb(this.b,t);p=new ZQd;q=new ZQd;for(n=c.k.Ud();n.$d();){k=s$c(n._d(),150);f$c(p.d,p.e++,k);IQd(q,s$c(VU(k,D$g),1))}i=new kzb;yxb(i,new jpc);i.hc=0;i.Jc&&PO(LP(I5(i),Uug),false);i.xb=false;this.c=H4e(p);X7(this.c,650,200);fyb(i,this.c);fyb(this.b,i);s=new cbc;X7(s,620,100);if(!d){fyb(this.b,new cKb(T8h+lDe(Vxh,Wxh)+U8h));fyb(this.b,s)}j=p.e;sX(this.c.I.g,new X$e(this,c,j,i,s,d,t));if(d){o=lDe(nxh,V8h);fyb(this.b,new cKb(o));DIb(this.ub,(LLe(),JLe(),GLe))}r=new YFb(lDe(Tuh,Tuh),new b_e(this,b,d,q,s));g=new YFb(lDe(Uuh,Uuh),new n_e(this));e=new kWb;e.E=(PH(),MH);VVb(e,r,e.Hb.e);VVb(e,g,e.Hb.e);fyb(this.b,e);dzb(this,e);this.rh(this.b,this.Hb.e)}
var _8h='620',a9h='70%',U8h=': <br />',T8h='<br />',W8h='<br /><br />',V8h='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',b9h='AsyncLoader5',c9h='DeleteItemWindow',d9h='DeleteItemWindow$1',e9h='DeleteItemWindow$2',f9h='DeleteItemWindow$2$1',g9h='DeleteItemWindow$3',Q8h='Do you really want to remove the selected PAGE {0}?',O8h='Do you really want to remove the {0} selected resources?',R8h='Informations',L8h='JahiaContentManagementService_Proxy.markForDeletion',S8h='JahiaGxtDeleteItem',$8h='This node is still used by:',Y8h='Those nodes are still used in:',M8h='markForDeletion',N8h='message.remove.multiple.confirm',X8h='message.remove.multiple.usage',P8h='message.remove.single.page.confirm',Z8h='message.remove.single.usage',K8h='runCallbacks5';_=SAd.prototype=MAd.prototype=new GF;_.gC=function TAd(){return vbd};_.Sk=function XAd(){RAd()};_.cM={};_=T$e.prototype=Q$e.prototype=new HGb;_.gC=function U$e(){return Ejd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=X$e.prototype=V$e.prototype=new Qfb;_.gC=function Y$e(){return Ajd};_.ag=function Z$e(b){var c,d,e;c=s$c(b.d,174);d=c.Nd();e=S$e(this.d,this.e);if(d>0){e+=W8h+(this.e>1?lDe(X8h,Y8h):lDe(Z8h,$8h))}else{ryb(this.b.b,this.c);Y7(this.i,_8h,a9h);if(this.g){X7(this.b,-1,130);X7(this.b.b,-1,130)}}aKb(this.j,e);nxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=b_e.prototype=$$e.prototype=new Ugb;_.fg=function c_e(b){a_e(this,s$c(b,216))};_.gC=function d_e(){return Cjd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=g_e.prototype=e_e.prototype=new ige;_.gC=function h_e(){return Bjd};_.xl=function i_e(b){p3e(this.b);b.fk();UNb(lDe(Qah,$Pg),b.fk())};_.ye=function j_e(b){p3e(this.b);u3e(this.b,63);y3e(this.b)};_.cM={};_.b=null;_=n_e.prototype=k_e.prototype=new Ugb;_.fg=function o_e(b){m_e(this,s$c(b,216))};_.gC=function p_e(){return Djd};_.cM={188:1};_.b=null;var vbd=Z0d(gNh,b9h),Ejd=Z0d(GVh,c9h),Ajd=Z0d(GVh,d9h),Cjd=Z0d(GVh,e9h),Bjd=Z0d(GVh,f9h),Djd=Z0d(GVh,g9h);$entry(UAd)();