function CBd(){}
function wBd(){}
function F_e(){}
function K_e(){}
function P_e(){}
function V_e(){}
function __e(){}
function X_e(b){this.b=b}
function c0e(b){this.b=b}
function b0e(b){XGb(b.b,null)}
function EWf(b){qHb(new I_e(b.b.p,b.b.p.p,b.b.b))}
function S_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function M_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function BBd(){var b;while(xBd){b=xBd;xBd=xBd.c;!xBd&&(yBd=null);EWf(b.b)}}
function R_e(b){var c,d;XGb(b.b,null);f4e(b.c,aEe(Muh,Muh));c=REe();d=new X_e(b.c);b.d?sFe(c,b.e,d):lGe(c,b.e,b_c(lXb(b.g),1),d)}
function EBd(){zBd=new CBd;JGc((GGc(),FGc),5);!!$stats&&$stats(yHc(bbi,VUg,-1,-1));zBd.bl();!!$stats&&$stats(yHc(bbi,P$g,-1,-1))}
function H_e(b,c){var d;c>1?(d=bEe(ebi,fbi,O$c(txd,{113:1,175:1,177:1,321:1},1,[Hqg+c]))):b_c($U(b_c(b.k.il(0),150),m1g),174).Sd(Ech)?(d=bEe(gbi,hbi,O$c(txd,{113:1,175:1,177:1,321:1},1,[b_c($U(b.s,bzg),1)]))):(d=bEe(Dzh,Ezh,O$c(txd,{113:1,175:1,177:1,321:1},1,[b_c($U(b.s,bzg),1)])));return d}
function lGe(c,d,e,g){var b,j,k,n,o;n=new IPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:N$g,evtGroup:n.b,method:cbi,millis:(new Date).getTime(),type:VUg});o=YNd(c);try{QNd(o.b,Hqg+eNd(o,w3g));QNd(o.b,Hqg+eNd(o,dbi));QNd(o.b,uwg);QNd(o.b,Hqg+eNd(o,G3g));QNd(o.b,Hqg+eNd(o,f2g));kNd(o,d);QNd(o.b,Hqg+eNd(o,e));k=NNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:N$g,evtGroup:n.b,method:cbi,millis:(new Date).getTime(),type:h2g});ZNd(c,(wOd(),vOd),cbi,n,k,g)}catch(b){b=yyd(b);if(e_c(b,311)){j=b;ahe(g,j)}else throw b}}
function I_e(b,c,d){r5();var e,g,i,j,k,n,o,p,q,r,s,t;sHb.call(this);a8(this,650,500);IIb(this.ub,ibi);!!this.E&&$O(PO(this.E,$Ig),ibi);oHb(this,false);this.b=new u6b;IIb(this.b.ub,aEe(Seh,Seh));this.b.xb=false;x6(this.b,false);F6(this.b,jbi);Cxb(this.b,new Krc(0));a8(this.b,650,500);t=new fKb;jyb(this.b,t);p=new TRd;q=new TRd;for(n=c.k.Ud();n.$d();){k=b_c(n._d(),150);Q$c(p.d,p.e++,k);CRd(q,b_c($U(k,O0g),1))}i=new ozb;Cxb(i,new npc);i.hc=0;i.Jc&&QO(MP(N5(i),Lvg),false);i.xb=false;this.c=w5e(p);a8(this.c,650,200);jyb(i,this.c);jyb(this.b,i);s=new gbc;a8(s,620,100);if(!d){jyb(this.b,new gKb(kbi+aEe(lAh,mAh)+lbi));jyb(this.b,s)}j=p.e;xX(this.c.I.g,new M_e(this,c,j,i,s,d,t));if(d){o=aEe(Fzh,mbi);jyb(this.b,new gKb(o));HIb(this.ub,(AMe(),yMe(),vMe))}r=new aGb(aEe(hxh,hxh),new S_e(this,b,d,q,s));g=new aGb(aEe(jxh,jxh),new c0e(this));e=new oWb;e.E=(QH(),NH);ZVb(e,r,e.Hb.e);ZVb(e,g,e.Hb.e);jyb(this.b,e);hzb(this,e);this.rh(this.b,this.Hb.e)}
var sbi='620',tbi='70%',lbi=': <br />',kbi='<br />',nbi='<br /><br />',mbi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',ubi='AsyncLoader5',vbi='DeleteItemWindow',wbi='DeleteItemWindow$1',xbi='DeleteItemWindow$2',ybi='DeleteItemWindow$2$1',zbi='DeleteItemWindow$3',hbi='Do you really want to remove the selected PAGE {0}?',fbi='Do you really want to remove the {0} selected resources?',ibi='Informations',cbi='JahiaContentManagementService_Proxy.markForDeletion',jbi='JahiaGxtDeleteItem',rbi='This node is still used by:',pbi='Those nodes are still used in:',dbi='markForDeletion',ebi='message.remove.multiple.confirm',obi='message.remove.multiple.usage',gbi='message.remove.single.page.confirm',qbi='message.remove.single.usage',bbi='runCallbacks5';_=CBd.prototype=wBd.prototype=new HF;_.gC=function DBd(){return fcd};_.bl=function HBd(){BBd()};_.cM={};_=I_e.prototype=F_e.prototype=new LGb;_.gC=function J_e(){return okd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=M_e.prototype=K_e.prototype=new Vfb;_.gC=function N_e(){return kkd};_.ag=function O_e(b){var c,d,e;c=b_c(b.d,174);d=c.Nd();e=H_e(this.d,this.e);if(d>0){e+=nbi+(this.e>1?aEe(obi,pbi):aEe(qbi,rbi))}else{vyb(this.b.b,this.c);b8(this.i,sbi,tbi);if(this.g){a8(this.b,-1,130);a8(this.b.b,-1,130)}}eKb(this.j,e);rxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=S_e.prototype=P_e.prototype=new Zgb;_.fg=function T_e(b){R_e(this,b_c(b,216))};_.gC=function U_e(){return mkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=X_e.prototype=V_e.prototype=new Zge;_.gC=function Y_e(){return lkd};_.Il=function Z_e(b){e4e(this.b);b.fk();YNb(aEe(_ch,adh),b.fk())};_.ye=function $_e(b){e4e(this.b);j4e(this.b,63);n4e(this.b)};_.cM={};_.b=null;_=c0e.prototype=__e.prototype=new Zgb;_.fg=function d0e(b){b0e(this,b_c(b,216))};_.gC=function e0e(){return nkd};_.cM={188:1};_.b=null;var fcd=O1d(zPh,ubi),okd=O1d(ZXh,vbi),kkd=O1d(ZXh,wbi),mkd=O1d(ZXh,xbi),lkd=O1d(ZXh,ybi),nkd=O1d(ZXh,zbi);$entry(EBd)();