function vBd(){}
function pBd(){}
function p_e(){}
function k_e(){}
function u_e(){}
function A_e(){}
function G_e(){}
function C_e(b){this.b=b}
function J_e(b){this.b=b}
function I_e(b){SGb(b.b,null)}
function jWf(b){lHb(new n_e(b.b.p,b.b.p.p,b.b.b))}
function x_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function r_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function uBd(){var b;while(qBd){b=qBd;qBd=qBd.c;!qBd&&(rBd=null);jWf(b.b)}}
function w_e(b){var c,d;SGb(b.b,null);M3e(b.c,HDe(Wth,Wth));c=wEe();d=new C_e(b.c);b.d?ZEe(c,b.e,d):SFe(c,b.e,Y$c(gXb(b.g),1),d)}
function xBd(){sBd=new vBd;FGc((CGc(),BGc),5);!!$stats&&$stats(uHc(jai,yUg,-1,-1));sBd.al();!!$stats&&$stats(uHc(jai,ZZg,-1,-1))}
function m_e(b,c){var d;c>1?(d=IDe(mai,nai,J$c(mxd,{113:1,175:1,177:1,321:1},1,[mqg+c]))):Y$c(UU(Y$c(b.k.hl(0),150),w0g),174).Sd(Obh)?(d=IDe(oai,pai,J$c(mxd,{113:1,175:1,177:1,321:1},1,[Y$c(UU(b.s,Hyg),1)]))):(d=IDe(Nyh,Oyh,J$c(mxd,{113:1,175:1,177:1,321:1},1,[Y$c(UU(b.s,Hyg),1)])));return d}
function SFe(c,d,e,g){var b,j,k,n,o;n=new rPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:XZg,evtGroup:n.b,method:kai,millis:(new Date).getTime(),type:yUg});o=HNd(c);try{zNd(o.b,mqg+PMd(o,G2g));zNd(o.b,mqg+PMd(o,lai));zNd(o.b,$vg);zNd(o.b,mqg+PMd(o,Q2g));zNd(o.b,mqg+PMd(o,p1g));VMd(o,d);zNd(o.b,mqg+PMd(o,e));k=wNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:XZg,evtGroup:n.b,method:kai,millis:(new Date).getTime(),type:r1g});INd(c,(fOd(),eOd),kai,n,k,g)}catch(b){b=ryd(b);if(_$c(b,311)){j=b;Hge(g,j)}else throw b}}
function n_e(b,c,d){l5();var e,g,i,j,k,n,o,p,q,r,s,t;nHb.call(this);W7(this,650,500);DIb(this.ub,qai);!!this.E&&YO(NO(this.E,EIg),qai);jHb(this,false);this.b=new p6b;DIb(this.b.ub,HDe(aeh,aeh));this.b.xb=false;r6(this.b,false);z6(this.b,rai);xxb(this.b,new Frc(0));W7(this.b,650,500);t=new aKb;eyb(this.b,t);p=new CRd;q=new CRd;for(n=c.k.Ud();n.$d();){k=Y$c(n._d(),150);L$c(p.d,p.e++,k);lRd(q,Y$c(UU(k,Y_g),1))}i=new jzb;xxb(i,new ipc);i.hc=0;i.Jc&&OO(KP(H5(i),ovg),false);i.xb=false;this.c=b5e(p);W7(this.c,650,200);eyb(i,this.c);eyb(this.b,i);s=new bbc;W7(s,620,100);if(!d){eyb(this.b,new bKb(sai+HDe(vzh,wzh)+tai));eyb(this.b,s)}j=p.e;rX(this.c.I.g,new r_e(this,c,j,i,s,d,t));if(d){o=HDe(Pyh,uai);eyb(this.b,new bKb(o));CIb(this.ub,(fMe(),dMe(),aMe))}r=new XFb(HDe(rwh,rwh),new x_e(this,b,d,q,s));g=new XFb(HDe(twh,twh),new J_e(this));e=new jWb;e.E=(OH(),LH);UVb(e,r,e.Hb.e);UVb(e,g,e.Hb.e);eyb(this.b,e);czb(this,e);this.rh(this.b,this.Hb.e)}
var Aai='620',Bai='70%',tai=': <br />',sai='<br />',vai='<br /><br />',uai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Cai='AsyncLoader5',Dai='DeleteItemWindow',Eai='DeleteItemWindow$1',Fai='DeleteItemWindow$2',Gai='DeleteItemWindow$2$1',Hai='DeleteItemWindow$3',pai='Do you really want to remove the selected PAGE {0}?',nai='Do you really want to remove the {0} selected resources?',qai='Informations',kai='JahiaContentManagementService_Proxy.markForDeletion',rai='JahiaGxtDeleteItem',zai='This node is still used by:',xai='Those nodes are still used in:',lai='markForDeletion',mai='message.remove.multiple.confirm',wai='message.remove.multiple.usage',oai='message.remove.single.page.confirm',yai='message.remove.single.usage',jai='runCallbacks5';_=vBd.prototype=pBd.prototype=new FF;_.gC=function wBd(){return acd};_.al=function ABd(){uBd()};_.cM={};_=n_e.prototype=k_e.prototype=new GGb;_.gC=function o_e(){return hkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=r_e.prototype=p_e.prototype=new Pfb;_.gC=function s_e(){return dkd};_.ag=function t_e(b){var c,d,e;c=Y$c(b.d,174);d=c.Nd();e=m_e(this.d,this.e);if(d>0){e+=vai+(this.e>1?HDe(wai,xai):HDe(yai,zai))}else{qyb(this.b.b,this.c);X7(this.i,Aai,Bai);if(this.g){W7(this.b,-1,130);W7(this.b.b,-1,130)}}_Jb(this.j,e);mxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=x_e.prototype=u_e.prototype=new Tgb;_.fg=function y_e(b){w_e(this,Y$c(b,216))};_.gC=function z_e(){return fkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=C_e.prototype=A_e.prototype=new Ege;_.gC=function D_e(){return ekd};_.Hl=function E_e(b){L3e(this.b);b.fk();TNb(HDe(jch,kch),b.fk())};_.ye=function F_e(b){L3e(this.b);Q3e(this.b,63);U3e(this.b)};_.cM={};_.b=null;_=J_e.prototype=G_e.prototype=new Tgb;_.fg=function K_e(b){I_e(this,Y$c(b,216))};_.gC=function L_e(){return gkd};_.cM={188:1};_.b=null;var acd=t1d(JOh,Cai),hkd=t1d(fXh,Dai),dkd=t1d(fXh,Eai),fkd=t1d(fXh,Fai),ekd=t1d(fXh,Gai),gkd=t1d(fXh,Hai);$entry(xBd)();