function IPc(){}
function FPc(){}
function DBd(){}
function xBd(){}
function B1e(){}
function J1e(){}
function H1e(){}
function L1e(){}
function R1e(){}
function X1e(){}
function O1e(b){this.b=b}
function N1e(b){VGb(b.b,null)}
function sXd(b,c){b.b.yl(b,c)}
function ZUf(b){oHb(new F1e(b.b.p,b.b.p.p.s))}
function HPc(){HPc=Skg;GPc=new MOc(RZg,new IPc)}
function tXd(){pXd();this.b=new UXd(this);this.ad[ntg]=o_g}
function CBd(){var b;while(yBd){b=yBd;yBd=yBd.c;!yBd&&(zBd=null);ZUf(b.b)}}
function D1e(b,c,d,e,g,i,j,k){vFe(XEe(),c,d,e,g,i,j,k,new Z1e(b,c,d,e,g,i,j))}
function Z1e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function U1e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function FBd(){ABd=new DBd;IGc((FGc(),EGc),4);!!$stats&&$stats(xHc(uai,YUg,-1,-1));ABd.el();!!$stats&&$stats(xHc(uai,D$g,-1,-1))}
function E1e(){$wnd.jQuery(xai).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(yai).val(b.x);$wnd.jQuery(zai).val(b.y);$wnd.jQuery(Aai).val(b.w);$wnd.jQuery(Bai).val(b.h)}})}
function T1e(b){w_c(jXb(b.j),119).Al()>0&&w_c(jXb(b.c),119).Al()>0&&D1e(b.b,w_c(XU(b.e,C0g),1),w_c(b.g.ce(),1),w_c(jXb(b.i),119).Al(),w_c(jXb(b.d),119).Al(),w_c(jXb(b.j),119).Al(),w_c(jXb(b.c),119).Al(),false)}
function vFe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new SPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:B$g,evtGroup:r.b,method:vai,millis:(new Date).getTime(),type:YUg});s=gOd(c);try{$Nd(s.b,Nqg+oNd(s,k3g));$Nd(s.b,Nqg+oNd(s,wai));$Nd(s.b,L3g);$Nd(s.b,Nqg+oNd(s,V1g));$Nd(s.b,Nqg+oNd(s,V1g));$Nd(s.b,Nqg+oNd(s,W1g));$Nd(s.b,Nqg+oNd(s,W1g));$Nd(s.b,Nqg+oNd(s,W1g));$Nd(s.b,Nqg+oNd(s,W1g));$Nd(s.b,Nqg+oNd(s,D3g));$Nd(s.b,Nqg+oNd(s,d));$Nd(s.b,Nqg+oNd(s,e));$Nd(s.b,Nqg+g);$Nd(s.b,Nqg+i);$Nd(s.b,Nqg+j);$Nd(s.b,Nqg+k);$Nd(s.b,n?tvg:dug);q=XNd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:B$g,evtGroup:r.b,method:vai,millis:(new Date).getTime(),type:X1g});hOd(c,(GOd(),FOd),vai,r,q,o)}catch(b){b=Uyd(b);if(!z_c(b,311))throw b}}
function F1e(b,c){o5();var d,e,g,i,j,k,n,o,p,q,r,s;qHb.call(this);Axb(this,new lpc);Z7(this,712,550);this.b=b;hHb(this,gEe(Cai,Cai));this.Ac=Dai;!!this.sc&&(K5(this).id=Dai,undefined);j=new s6b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&RO(NP(K5(j),Pvg),false);p=new B$b;p.vi(Eai);i=w_c(XU(c,gzg),1).lastIndexOf(eug);if(i>0){g=_4d(w_c(XU(c,gzg),1),i);p.yi(Y4d(w_c(XU(c,gzg),1),g,Fai+g))}else{p.yi(w_c(XU(c,gzg),1)+Fai)}CXb(p,gEe(Jfh,Jfh));myb(j,p,j.Hb.e);r=new X8b;EXb(r,Hrg);r.Ac=Hrg;!!r.sc&&(K5(r).id=Hrg,undefined);T5(r);myb(j,r,j.Hb.e);o=new X8b;EXb(o,Grg);o.Ac=Grg;!!o.sc&&(K5(o).id=Grg,undefined);T5(o);myb(j,o,j.Hb.e);s=new X8b;CXb(s,gEe(Gai,Ojh));G6(s,Hai);EXb(s,Vrg);s.Ac=Vrg;!!s.sc&&(K5(s).id=Vrg,undefined);M6(s);y5(s);myb(j,s,j.Hb.e);k=new X8b;CXb(k,gEe(Iai,Tjh));G6(k,Jai);EXb(k,Urg);k.Ac=Urg;!!k.sc&&(K5(k).id=Urg,undefined);M6(k);y5(k);myb(j,k,j.Hb.e);n=new tXd;Q4(n,new J1e,(HPc(),HPc(),GPc));n.ad.id=Kai;sXd(n,c.A);myb(j,n,j.Hb.e);d=new mWb;e=new $Fb(gEe($eh,$eh),new O1e(this));q=new $Fb(gEe(ifh,ifh),new U1e(this,s,k,c,p,r,o));XVb(d,q,d.Hb.e);XVb(d,e,d.Hb.e);gzb(this,(RH(),OH));fzb(this,d);nxb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var xai='#cropbox',Bai='#height-input',yai='#left-input',zai='#top-input',Aai='#width-input',Mai='AsyncLoader4',Nai='ImageCrop',Oai='ImageCrop$1',Pai='ImageCrop$2',Qai='ImageCrop$3',Rai='ImageCrop$4',vai='JahiaContentManagementService_Proxy.cropImage',Dai='JahiaGxtImageCrop',Fai='_crop',wai='cropImage',Kai='cropbox',Lai='failure.crop.label',Cai='label.crop',Iai='label.height',Gai='label.width',uai='runCallbacks4',Jai='stylehight',Hai='stylewidth';_=IPc.prototype=FPc.prototype=new TNc;_.nk=function JPc(b){w_c(b,288);E1e()};_.qk=function KPc(){return GPc};_.gC=function LPc(){return sbd};_.cM={};var GPc;_=DBd.prototype=xBd.prototype=new IF;_.gC=function EBd(){return Acd};_.el=function IBd(){CBd()};_.cM={};_=tXd.prototype=oXd.prototype;_=zXd.prototype;_.yl=function KXd(b,c){b.b=new UXd(b);b.b.yl(b,c)};_=QXd.prototype;_.yl=function ZXd(b,c){!!b.b&&(b.b.wl(b)[p_g]=Nqg,undefined);b.ad.src=c};_=F1e.prototype=B1e.prototype=new JGb;_.gC=function G1e(){return _kd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_=J1e.prototype=H1e.prototype=new IF;_.gC=function K1e(){return Xkd};_.cM={288:1,292:1};_=O1e.prototype=L1e.prototype=new Wgb;_.fg=function P1e(b){N1e(this,w_c(b,216))};_.gC=function Q1e(){return Ykd};_.cM={188:1};_.b=null;_=U1e.prototype=R1e.prototype=new Wgb;_.fg=function V1e(b){T1e(this,w_c(b,216))};_.gC=function W1e(){return Zkd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=Z1e.prototype=X1e.prototype=new dhe;_.gC=function $1e(){return $kd};_.Ll=function _1e(b){if(b!=null&&b.cM&&!!b.cM[354]){$wnd.confirm(gEe(Yhh,Yhh)+GTg+gEe(Zyh,Zyh))&&D1e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(gEe(Lai,Lai)+GTg+b.fk());gEe(Lai,Lai)}};_.ye=function a2e(b){VGb(this.b,null);p4e(this.b.b,1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var sbd=U1d(bOh,vCh),Acd=U1d(qPh,Mai),_kd=U1d(OXh,Nai),Xkd=U1d(OXh,Oai),Ykd=U1d(OXh,Pai),Zkd=U1d(OXh,Qai),$kd=U1d(OXh,Rai);$entry(FBd)();