function YBd(){}
function SBd(){}
function L_e(){}
function Q_e(){}
function V_e(){}
function __e(){}
function f0e(){}
function b0e(b){this.b=b}
function i0e(b){this.b=b}
function h0e(b){VGb(b.b,null)}
function KWf(b){oHb(new O_e(b.b.p,b.b.p.p,b.b.b))}
function Y_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function S_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function XBd(){var b;while(TBd){b=TBd;TBd=TBd.c;!TBd&&(UBd=null);KWf(b.b)}}
function X_e(b){var c,d;VGb(b.b,null);l4e(b.c,gEe(Auh,Auh));c=XEe();d=new b0e(b.c);b.d?yFe(c,b.e,d):rGe(c,b.e,w_c(jXb(b.g),1),d)}
function $Bd(){VBd=new YBd;IGc((FGc(),EGc),5);!!$stats&&$stats(xHc(Sai,YUg,-1,-1));VBd.el();!!$stats&&$stats(xHc(Sai,D$g,-1,-1))}
function N_e(b,c){var d;c>1?(d=hEe(Vai,Wai,h_c(Pxd,{113:1,175:1,177:1,321:1},1,[Nqg+c]))):w_c(XU(w_c(b.k.ll(0),150),a1g),174).Sd(sch)?(d=hEe(Xai,Yai,h_c(Pxd,{113:1,175:1,177:1,321:1},1,[w_c(XU(b.s,gzg),1)]))):(d=hEe(rzh,szh,h_c(Pxd,{113:1,175:1,177:1,321:1},1,[w_c(XU(b.s,gzg),1)])));return d}
function rGe(c,d,e,g){var b,j,k,n,o;n=new SPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:B$g,evtGroup:n.b,method:Tai,millis:(new Date).getTime(),type:YUg});o=gOd(c);try{$Nd(o.b,Nqg+oNd(o,k3g));$Nd(o.b,Nqg+oNd(o,Uai));$Nd(o.b,zwg);$Nd(o.b,Nqg+oNd(o,u3g));$Nd(o.b,Nqg+oNd(o,V1g));uNd(o,d);$Nd(o.b,Nqg+oNd(o,e));k=XNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:B$g,evtGroup:n.b,method:Tai,millis:(new Date).getTime(),type:X1g});hOd(c,(GOd(),FOd),Tai,n,k,g)}catch(b){b=Uyd(b);if(z_c(b,311)){j=b;ghe(g,j)}else throw b}}
function O_e(b,c,d){o5();var e,g,i,j,k,n,o,p,q,r,s,t;qHb.call(this);Z7(this,650,500);GIb(this.ub,Zai);!!this.E&&_O(QO(this.E,dJg),Zai);mHb(this,false);this.b=new s6b;GIb(this.b.ub,gEe(Geh,Geh));this.b.xb=false;u6(this.b,false);C6(this.b,$ai);Axb(this.b,new Irc(0));Z7(this.b,650,500);t=new dKb;hyb(this.b,t);p=new bSd;q=new bSd;for(n=c.k.Ud();n.$d();){k=w_c(n._d(),150);j_c(p.d,p.e++,k);MRd(q,w_c(XU(k,C0g),1))}i=new mzb;Axb(i,new lpc);i.hc=0;i.Jc&&RO(NP(K5(i),Pvg),false);i.xb=false;this.c=C5e(p);Z7(this.c,650,200);hyb(i,this.c);hyb(this.b,i);s=new ebc;Z7(s,620,100);if(!d){hyb(this.b,new eKb(_ai+gEe(_zh,aAh)+abi));hyb(this.b,s)}j=p.e;uX(this.c.I.g,new S_e(this,c,j,i,s,d,t));if(d){o=gEe(tzh,bbi);hyb(this.b,new eKb(o));FIb(this.ub,(GMe(),EMe(),BMe))}r=new $Fb(gEe(Xwh,Xwh),new Y_e(this,b,d,q,s));g=new $Fb(gEe(Zwh,Zwh),new i0e(this));e=new mWb;e.E=(RH(),OH);XVb(e,r,e.Hb.e);XVb(e,g,e.Hb.e);hyb(this.b,e);fzb(this,e);this.rh(this.b,this.Hb.e)}
var hbi='620',ibi='70%',abi=': <br />',_ai='<br />',cbi='<br /><br />',bbi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',jbi='AsyncLoader5',kbi='DeleteItemWindow',lbi='DeleteItemWindow$1',mbi='DeleteItemWindow$2',nbi='DeleteItemWindow$2$1',obi='DeleteItemWindow$3',Yai='Do you really want to remove the selected PAGE {0}?',Wai='Do you really want to remove the {0} selected resources?',Zai='Informations',Tai='JahiaContentManagementService_Proxy.markForDeletion',$ai='JahiaGxtDeleteItem',gbi='This node is still used by:',ebi='Those nodes are still used in:',Uai='markForDeletion',Vai='message.remove.multiple.confirm',dbi='message.remove.multiple.usage',Xai='message.remove.single.page.confirm',fbi='message.remove.single.usage',Sai='runCallbacks5';_=YBd.prototype=SBd.prototype=new IF;_.gC=function ZBd(){return Dcd};_.el=function bCd(){XBd()};_.cM={};_=O_e.prototype=L_e.prototype=new JGb;_.gC=function P_e(){return Kkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=S_e.prototype=Q_e.prototype=new Sfb;_.gC=function T_e(){return Gkd};_.ag=function U_e(b){var c,d,e;c=w_c(b.d,174);d=c.Nd();e=N_e(this.d,this.e);if(d>0){e+=cbi+(this.e>1?gEe(dbi,ebi):gEe(fbi,gbi))}else{tyb(this.b.b,this.c);$7(this.i,hbi,ibi);if(this.g){Z7(this.b,-1,130);Z7(this.b.b,-1,130)}}cKb(this.j,e);pxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=Y_e.prototype=V_e.prototype=new Wgb;_.fg=function Z_e(b){X_e(this,w_c(b,216))};_.gC=function $_e(){return Ikd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=b0e.prototype=__e.prototype=new dhe;_.gC=function c0e(){return Hkd};_.Ll=function d0e(b){k4e(this.b);b.fk();WNb(gEe(Pch,Qch),b.fk())};_.ye=function e0e(b){k4e(this.b);p4e(this.b,63);t4e(this.b)};_.cM={};_.b=null;_=i0e.prototype=f0e.prototype=new Wgb;_.fg=function j0e(b){h0e(this,w_c(b,216))};_.gC=function k0e(){return Jkd};_.cM={188:1};_.b=null;var Dcd=U1d(qPh,jbi),Kkd=U1d(OXh,kbi),Gkd=U1d(OXh,lbi),Ikd=U1d(OXh,mbi),Hkd=U1d(OXh,nbi),Jkd=U1d(OXh,obi);$entry($Bd)();