function zGd(){}
function tGd(){}
function u3e(){}
function z3e(){}
function E3e(){}
function K3e(){}
function Q3e(){}
function T3e(b){this.b=b}
function S3e(b){vJb(b.b,null)}
function M3e(b,c){this.b=b;this.c=c}
function yeg(b){QJb(new x3e(b.b.p,b.b.p.Rl(),b.b.b))}
function yGd(){var b;while(uGd){b=uGd;uGd=uGd.c;!uGd&&(vGd=null);yeg(b.b)}}
function H3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function B3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function BGd(){wGd=new zGd;CJc((zJc(),yJc),5);!!$stats&&$stats(rKc(czi,kch,-1,-1));wGd.al();!!$stats&&$stats(rKc(czi,Zgh,-1,-1))}
function G3e(b){var c,d;vJb(b.b,null);b.c.Ul(tJe(XMh,XMh));c=iKe();d=new M3e(b.c,b.e);b.d?LKe(c,b.g,d):HLe(c,b.g,Y1c(zZb(b.i),1),d)}
function w3e(b,c){var d;c>1?(d=uJe(fzi,gzi,J1c(qCd,{113:1,175:1,177:1,323:1},1,[zKg+c]))):Y1c(SW(Y1c(b.k.il(0),150),Ijh),174).Sd(suh)?(d=uJe(hzi,izi,J1c(qCd,{113:1,175:1,177:1,323:1},1,[Y1c(SW(b.s,TSg),1)]))):(d=uJe(IRh,JRh,J1c(qCd,{113:1,175:1,177:1,323:1},1,[Y1c(SW(b.s,TSg),1)])));return d}
function HLe(c,d,e,g){var b,j,k,n,o;n=new HUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Xgh,evtGroup:n.b,method:dzi,millis:(new Date).getTime(),type:kch});o=XSd(c);try{PSd(o.b,zKg+dSd(o,Plh));PSd(o.b,zKg+dSd(o,ezi));PSd(o.b,mQg);PSd(o.b,zKg+dSd(o,Zlh));PSd(o.b,zKg+dSd(o,Akh));jSd(o,d);PSd(o.b,zKg+dSd(o,e));k=MSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Xgh,evtGroup:n.b,method:dzi,millis:(new Date).getTime(),type:Ckh});YSd(c,(vTd(),uTd),dzi,n,k,g)}catch(b){b=vDd(b);if(_1c(b,313)){j=b;mme(g,j)}else throw b}}
function x3e(b,c,d){r7();var e,g,i,j,k,n,o,p,q,r,s,t;SJb.call(this);eab(this,650,500);iLb(this.ub,jzi);!!this.E&&SQ(HQ(this.E,Z0g),jzi);OJb(this,false);this.b=new I8b;iLb(this.b.ub,tJe(xDh,xDh));this.b.xb=false;y8(this.b,false);H8(this.b,kzi);Zzb(this.b,new buc(0));eab(this.b,650,500);t=new JMb;JAb(this.b,t);p=new SWd;q=new SWd;for(n=c.k.Ud();n.$d();){k=Y1c(n._d(),150);L1c(p.d,p.e++,k);BWd(q,Y1c(SW(k,jjh),1))}i=new OBb;Zzb(i,new Vrc);i.hc=0;i.Jc&&IQ(ER(O7(i),CPg),false);i.xb=false;this.c=p9e(p);eab(this.c,650,200);JAb(i,this.c);JAb(this.b,i);s=new udc;eab(s,620,100);if(!d){JAb(this.b,new KMb(lzi+tJe(fSh,gSh)+mzi));JAb(this.b,s)}j=p.e;pZ(this.c.I.g,new B3e(this,c,j,i,s,d,t));if(d){o=tJe(KRh,nzi);JAb(this.b,new KMb(o));hLb(this.ub,(iSe(),gSe(),dSe))}r=new AIb(tJe(lPh,lPh),new H3e(this,b,d,q,s,p));g=new AIb(tJe(mPh,mPh),new T3e(this));e=new CYb;e.E=(SJ(),PJ);lYb(e,r,e.Hb.e);lYb(e,g,e.Hb.e);JAb(this.b,e);HBb(this,e);this.uh(this.b,this.Hb.e)}
var tzi='620',uzi='70%',mzi=': <br />',lzi='<br />',ozi='<br /><br />',nzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',vzi='AsyncLoader5',wzi='DeleteItemWindow',xzi='DeleteItemWindow$1',yzi='DeleteItemWindow$2',zzi='DeleteItemWindow$2$1',Azi='DeleteItemWindow$3',izi='Do you really want to remove the selected PAGE {0}?',gzi='Do you really want to remove the {0} selected resources?',jzi='Informations',dzi='JahiaContentManagementService_Proxy.markForDeletion',kzi='JahiaGxtDeleteItem',szi='This node is still used by:',qzi='Those nodes are still used in:',ezi='markForDeletion',fzi='message.remove.multiple.confirm',pzi='message.remove.multiple.usage',hzi='message.remove.single.page.confirm',rzi='message.remove.single.usage',czi='runCallbacks5';_=zGd.prototype=tGd.prototype=new JH;_.gC=function AGd(){return bfd};_.al=function EGd(){yGd()};_.cM={};_=x3e.prototype=u3e.prototype=new jJb;_.gC=function y3e(){return bnd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=B3e.prototype=z3e.prototype=new hib;_.gC=function C3e(){return Zmd};_.cg=function D3e(b){var c,d,e;c=Y1c(b.d,174);d=c.Nd();e=w3e(this.d,this.e);if(d>0){e+=ozi+(this.e>1?tJe(pzi,qzi):tJe(rzi,szi))}else{VAb(this.b.b,this.c);fab(this.i,tzi,uzi);if(this.g){eab(this.b,-1,130);eab(this.b.b,-1,130)}}IMb(this.j,e);Ozb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=H3e.prototype=E3e.prototype=new sjb;_.ig=function I3e(b){G3e(this,Y1c(b,216))};_.gC=function J3e(){return _md};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=M3e.prototype=K3e.prototype=new jme;_.gC=function N3e(){return $md};_.Il=function O3e(b){this.b.Tl();b.ok();FQb(tJe(Puh,Quh),b.ok())};_.ye=function P3e(b){var c;this.b.Tl();c=null;_1c(this.b,354)?(c=Y1c(this.b,354).d.u):_1c(this.b,355)&&(c=Y1c(this.b,355));if(!!c&&JWd(this.c,Y1c(SW(c.q.j,jjh),1),0)!=-1){this.b.Vl(2);this.b.Wl(null)}else{this.b.Vl(63);this.b.Wl(null)}};_.cM={};_.b=null;_.c=null;_=T3e.prototype=Q3e.prototype=new sjb;_.ig=function U3e(b){S3e(this,Y1c(b,216))};_.gC=function V3e(){return and};_.cM={188:1};_.b=null;var bfd=$6d(_4h,vzi),bnd=$6d(ldi,wzi),Zmd=$6d(ldi,xzi),_md=$6d(ldi,yzi),$md=$6d(ldi,zzi),and=$6d(ldi,Azi);$entry(BGd)();