function UAd(){}
function OAd(){}
function O$e(){}
function J$e(){}
function T$e(){}
function Z$e(){}
function d_e(){}
function g_e(b){this.b=b}
function _$e(b){this.b=b}
function f_e(b){RGb(b.b,null)}
function IVf(b){kHb(new M$e(b.b.p,b.b.p.p,b.b.b))}
function W$e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function Q$e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function TAd(){var b;while(PAd){b=PAd;PAd=PAd.c;!PAd&&(QAd=null);IVf(b.b)}}
function V$e(b){var c,d;RGb(b.b,null);j3e(b.c,eDe(nsh,nsh));c=VDe();d=new _$e(b.c);b.d?wEe(c,b.e,d):pFe(c,b.e,w$c(fXb(b.g),1),d)}
function WAd(){RAd=new UAd;EGc((BGc(),AGc),5);!!$stats&&$stats(tHc(z8h,aUg,-1,-1));RAd.Sk();!!$stats&&$stats(tHc(z8h,vYg,-1,-1))}
function L$e(b,c){var d;c>1?(d=fDe(C8h,D8h,h$c(Lwd,{113:1,175:1,177:1,321:1},1,[Lpg+c]))):w$c(TU(w$c(b.k.Zk(0),150),U$g),174).Sd(kah)?(d=fDe(E8h,F8h,h$c(Lwd,{113:1,175:1,177:1,321:1},1,[w$c(TU(b.s,cyg),1)]))):(d=fDe(cxh,dxh,h$c(Lwd,{113:1,175:1,177:1,321:1},1,[w$c(TU(b.s,cyg),1)])));return d}
function pFe(c,d,e,g){var b,j,k,n,o;n=new QOd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:tYg,evtGroup:n.b,method:A8h,millis:(new Date).getTime(),type:aUg});o=eNd(c);try{YMd(o.b,Lpg+mMd(o,c1g));YMd(o.b,Lpg+mMd(o,B8h));YMd(o.b,xvg);YMd(o.b,Lpg+mMd(o,m1g));YMd(o.b,Lpg+mMd(o,N_g));sMd(o,d);YMd(o.b,Lpg+mMd(o,e));k=VMd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:tYg,evtGroup:n.b,method:A8h,millis:(new Date).getTime(),type:P_g});fNd(c,(ENd(),DNd),A8h,n,k,g)}catch(b){b=Qxd(b);if(z$c(b,311)){j=b;ege(g,j)}else throw b}}
function M$e(b,c,d){k5();var e,g,i,j,k,n,o,p,q,r,s,t;mHb.call(this);V7(this,650,500);CIb(this.ub,G8h);!!this.E&&XO(MO(this.E,hIg),G8h);iHb(this,false);this.b=new o6b;CIb(this.b.ub,eDe(wch,wch));this.b.xb=false;q6(this.b,false);y6(this.b,H8h);wxb(this.b,new Erc(0));V7(this.b,650,500);t=new _Jb;dyb(this.b,t);p=new _Qd;q=new _Qd;for(n=c.k.Ud();n.$d();){k=w$c(n._d(),150);j$c(p.d,p.e++,k);KQd(q,w$c(TU(k,u$g),1))}i=new izb;wxb(i,new hpc);i.hc=0;i.Jc&&NO(JP(G5(i),Nug),false);i.xb=false;this.c=A4e(p);V7(this.c,650,200);dyb(i,this.c);dyb(this.b,i);s=new abc;V7(s,620,100);if(!d){dyb(this.b,new aKb(I8h+eDe(Mxh,Nxh)+J8h));dyb(this.b,s)}j=p.e;qX(this.c.I.g,new Q$e(this,c,j,i,s,d,t));if(d){o=eDe(exh,K8h);dyb(this.b,new aKb(o));BIb(this.ub,(ELe(),CLe(),zLe))}r=new WFb(eDe(Kuh,Kuh),new W$e(this,b,d,q,s));g=new WFb(eDe(Luh,Luh),new g_e(this));e=new iWb;e.E=(NH(),KH);TVb(e,r,e.Hb.e);TVb(e,g,e.Hb.e);dyb(this.b,e);bzb(this,e);this.rh(this.b,this.Hb.e)}
var Q8h='620',R8h='70%',J8h=': <br />',I8h='<br />',L8h='<br /><br />',K8h='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',S8h='AsyncLoader5',T8h='DeleteItemWindow',U8h='DeleteItemWindow$1',V8h='DeleteItemWindow$2',W8h='DeleteItemWindow$2$1',X8h='DeleteItemWindow$3',F8h='Do you really want to remove the selected PAGE {0}?',D8h='Do you really want to remove the {0} selected resources?',G8h='Informations',A8h='JahiaContentManagementService_Proxy.markForDeletion',H8h='JahiaGxtDeleteItem',P8h='This node is still used by:',N8h='Those nodes are still used in:',B8h='markForDeletion',C8h='message.remove.multiple.confirm',M8h='message.remove.multiple.usage',E8h='message.remove.single.page.confirm',O8h='message.remove.single.usage',z8h='runCallbacks5';_=UAd.prototype=OAd.prototype=new EF;_.gC=function VAd(){return zbd};_.Sk=function ZAd(){TAd()};_.cM={};_=M$e.prototype=J$e.prototype=new FGb;_.gC=function N$e(){return Gjd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=Q$e.prototype=O$e.prototype=new Ofb;_.gC=function R$e(){return Cjd};_.ag=function S$e(b){var c,d,e;c=w$c(b.d,174);d=c.Nd();e=L$e(this.d,this.e);if(d>0){e+=L8h+(this.e>1?eDe(M8h,N8h):eDe(O8h,P8h))}else{pyb(this.b.b,this.c);W7(this.i,Q8h,R8h);if(this.g){V7(this.b,-1,130);V7(this.b.b,-1,130)}}$Jb(this.j,e);lxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=W$e.prototype=T$e.prototype=new Sgb;_.fg=function X$e(b){V$e(this,w$c(b,216))};_.gC=function Y$e(){return Ejd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=_$e.prototype=Z$e.prototype=new bge;_.gC=function a_e(){return Djd};_.xl=function b_e(b){i3e(this.b);b.fk();SNb(eDe(Hah,UPg),b.fk())};_.ye=function c_e(b){i3e(this.b);n3e(this.b,63);r3e(this.b)};_.cM={};_.b=null;_=g_e.prototype=d_e.prototype=new Sgb;_.fg=function h_e(b){f_e(this,w$c(b,216))};_.gC=function i_e(){return Fjd};_.cM={188:1};_.b=null;var zbd=S0d(ZMh,S8h),Gjd=S0d(vVh,T8h),Cjd=S0d(vVh,U8h),Ejd=S0d(vVh,V8h),Djd=S0d(vVh,W8h),Fjd=S0d(vVh,X8h);$entry(WAd)();