function fCd(){}
function _Bd(){}
function u0e(){}
function z0e(){}
function E0e(){}
function K0e(){}
function Q0e(){}
function M0e(b){this.b=b}
function T0e(b){this.b=b}
function S0e(b){ZGb(b.b,null)}
function tXf(b){sHb(new x0e(b.b.p,b.b.p.p,b.b.b))}
function H0e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function B0e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function eCd(){var b;while(aCd){b=aCd;aCd=aCd.c;!aCd&&(bCd=null);tXf(b.b)}}
function G0e(b){var c,d;ZGb(b.b,null);W4e(b.c,REe(Lvh,Lvh));c=GFe();d=new M0e(b.c);b.d?hGe(c,b.e,d):aHe(c,b.e,E_c(nXb(b.g),1),d)}
function hCd(){cCd=new fCd;MGc((JGc(),IGc),5);!!$stats&&$stats(BHc(cci,LVg,-1,-1));cCd.cl();!!$stats&&$stats(BHc(cci,B_g,-1,-1))}
function w0e(b,c){var d;c>1?(d=SEe(fci,gci,p_c(Yxd,{113:1,175:1,177:1,321:1},1,[wrg+c]))):E_c(aV(E_c(b.k.jl(0),150),o2g),174).Sd(Gdh)?(d=SEe(hci,ici,p_c(Yxd,{113:1,175:1,177:1,321:1},1,[E_c(aV(b.s,Uzg),1)]))):(d=SEe(CAh,DAh,p_c(Yxd,{113:1,175:1,177:1,321:1},1,[E_c(aV(b.s,Uzg),1)])));return d}
function aHe(c,d,e,g){var b,j,k,n,o;n=new mQd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:z_g,evtGroup:n.b,method:dci,millis:(new Date).getTime(),type:LVg});o=COd(c);try{uOd(o.b,wrg+KNd(o,y4g));uOd(o.b,wrg+KNd(o,eci));uOd(o.b,jxg);uOd(o.b,wrg+KNd(o,I4g));uOd(o.b,wrg+KNd(o,h3g));QNd(o,d);uOd(o.b,wrg+KNd(o,e));k=rOd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:z_g,evtGroup:n.b,method:dci,millis:(new Date).getTime(),type:j3g});DOd(c,(aPd(),_Od),dci,n,k,g)}catch(b){b=bzd(b);if(H_c(b,311)){j=b;Rhe(g,j)}else throw b}}
function x0e(b,c,d){t5();var e,g,i,j,k,n,o,p,q,r,s,t;uHb.call(this);c8(this,650,500);KIb(this.ub,jci);!!this.E&&aP(RO(this.E,PJg),jci);qHb(this,false);this.b=new w6b;KIb(this.b.ub,REe(Tfh,Tfh));this.b.xb=false;z6(this.b,false);H6(this.b,kci);Exb(this.b,new Mrc(0));c8(this.b,650,500);t=new hKb;lyb(this.b,t);p=new xSd;q=new xSd;for(n=c.k.Ud();n.$d();){k=E_c(n._d(),150);r_c(p.d,p.e++,k);gSd(q,E_c(aV(k,Q1g),1))}i=new qzb;Exb(i,new ppc);i.hc=0;i.Jc&&SO(OP(P5(i),Awg),false);i.xb=false;this.c=l6e(p);c8(this.c,650,200);lyb(i,this.c);lyb(this.b,i);s=new ibc;c8(s,620,100);if(!d){lyb(this.b,new iKb(lci+REe(kBh,lBh)+mci));lyb(this.b,s)}j=p.e;zX(this.c.I.g,new B0e(this,c,j,i,s,d,t));if(d){o=REe(EAh,nci);lyb(this.b,new iKb(o));JIb(this.ub,(pNe(),nNe(),kNe))}r=new cGb(REe(gyh,gyh),new H0e(this,b,d,q,s));g=new cGb(REe(iyh,iyh),new T0e(this));e=new qWb;e.E=(SH(),PH);_Vb(e,r,e.Hb.e);_Vb(e,g,e.Hb.e);lyb(this.b,e);jzb(this,e);this.rh(this.b,this.Hb.e)}
var tci='620',uci='70%',mci=': <br />',lci='<br />',oci='<br /><br />',nci='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',vci='AsyncLoader5',wci='DeleteItemWindow',xci='DeleteItemWindow$1',yci='DeleteItemWindow$2',zci='DeleteItemWindow$2$1',Aci='DeleteItemWindow$3',ici='Do you really want to remove the selected PAGE {0}?',gci='Do you really want to remove the {0} selected resources?',jci='Informations',dci='JahiaContentManagementService_Proxy.markForDeletion',kci='JahiaGxtDeleteItem',sci='This node is still used by:',qci='Those nodes are still used in:',eci='markForDeletion',fci='message.remove.multiple.confirm',pci='message.remove.multiple.usage',hci='message.remove.single.page.confirm',rci='message.remove.single.usage',cci='runCallbacks5';_=fCd.prototype=_Bd.prototype=new JF;_.gC=function gCd(){return Icd};_.cl=function kCd(){eCd()};_.cM={};_=x0e.prototype=u0e.prototype=new NGb;_.gC=function y0e(){return Tkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=B0e.prototype=z0e.prototype=new Xfb;_.gC=function C0e(){return Pkd};_.ag=function D0e(b){var c,d,e;c=E_c(b.d,174);d=c.Nd();e=w0e(this.d,this.e);if(d>0){e+=oci+(this.e>1?REe(pci,qci):REe(rci,sci))}else{xyb(this.b.b,this.c);d8(this.i,tci,uci);if(this.g){c8(this.b,-1,130);c8(this.b.b,-1,130)}}gKb(this.j,e);txb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=H0e.prototype=E0e.prototype=new _gb;_.fg=function I0e(b){G0e(this,E_c(b,216))};_.gC=function J0e(){return Rkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=M0e.prototype=K0e.prototype=new Ohe;_.gC=function N0e(){return Qkd};_.Jl=function O0e(b){V4e(this.b);b.fk();$Nb(REe(beh,CRg),b.fk())};_.ye=function P0e(b){V4e(this.b);$4e(this.b,63);c5e(this.b)};_.cM={};_.b=null;_=T0e.prototype=Q0e.prototype=new _gb;_.fg=function U0e(b){S0e(this,E_c(b,216))};_.gC=function V0e(){return Skd};_.cM={188:1};_.b=null;var Icd=D2d(yQh,vci),Tkd=D2d($Yh,wci),Pkd=D2d($Yh,xci),Rkd=D2d($Yh,yci),Qkd=D2d($Yh,zci),Skd=D2d($Yh,Aci);$entry(hCd)();