function dSc(){}
function aSc(){}
function aGd(){}
function WFd(){}
function I4e(){}
function Q4e(){}
function O4e(){}
function S4e(){}
function Y4e(){}
function c5e(){}
function V4e(b){this.b=b}
function U4e(b){pJb(b.b,null)}
function jcg(b){KJb(new M4e(b.b.p,b.b.p._l().s))}
function cSc(){cSc=gEg;bSc=new hRc(jgh,new dSc)}
function _Fd(){var b;while(XFd){b=XFd;XFd=XFd.c;!XFd&&(YFd=null);jcg(b.b)}}
function K4e(b,c,d,e,g,i,j,k){eKe(GJe(),c,d,e,g,i,j,k,new e5e(b,c,d,e,g,i,j))}
function e5e(b,c,d,e,g,i,j){this.b=b;this.e=c;this.g=d;this.i=e;this.d=g;this.j=i;this.c=j}
function _4e(b,c,d,e,g,i,j){this.b=b;this.j=c;this.c=d;this.e=e;this.g=g;this.i=i;this.d=j}
function cGd(){ZFd=new aGd;wJc((tJc(),sJc),4);!!$stats&&$stats(lKc(syi,Bbh,-1,-1));ZFd.kl();!!$stats&&$stats(lKc(syi,Xgh,-1,-1))}
function L4e(){$wnd.jQuery(vyi).Jcrop({boxWidth:700,boxHeight:400,onSelect:function(b){$wnd.jQuery(wyi).val(b.x);$wnd.jQuery(xyi).val(b.y);$wnd.jQuery(yyi).val(b.w);$wnd.jQuery(zyi).val(b.h)}})}
function $4e(b){X1c(tZb(b.j),119).Hl()>0&&X1c(tZb(b.c),119).Hl()>0&&K4e(b.b,X1c(LW(b.e,Tih),1),X1c(b.g.ce(),1),X1c(tZb(b.i),119).Hl(),X1c(tZb(b.d),119).Hl(),X1c(tZb(b.j),119).Hl(),X1c(tZb(b.c),119).Hl(),false)}
function eKe(c,d,e,g,i,j,k,n,o){var b,q,r,s;r=new sUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Vgh,evtGroup:r.b,method:tyi,millis:(new Date).getTime(),type:Bbh});s=ISd(c);try{ASd(s.b,XJg+QRd(s,xlh));ASd(s.b,XJg+QRd(s,uyi));ASd(s.b,Tlh);ASd(s.b,XJg+QRd(s,ikh));ASd(s.b,XJg+QRd(s,ikh));ASd(s.b,XJg+QRd(s,jkh));ASd(s.b,XJg+QRd(s,jkh));ASd(s.b,XJg+QRd(s,jkh));ASd(s.b,XJg+QRd(s,jkh));ASd(s.b,XJg+QRd(s,Olh));ASd(s.b,XJg+QRd(s,d));ASd(s.b,XJg+QRd(s,e));ASd(s.b,XJg+g);ASd(s.b,XJg+i);ASd(s.b,XJg+j);ASd(s.b,XJg+k);ASd(s.b,n?BOg:lNg);q=xSd(s);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Vgh,evtGroup:r.b,method:tyi,millis:(new Date).getTime(),type:kkh});JSd(c,(gTd(),fTd),tyi,r,q,o)}catch(b){b=rDd(b);if(!$1c(b,313))throw b}}
function M4e(b,c){k7();var d,e,g,i,j,k,n,o,p,q,r,s;MJb.call(this);Tzb(this,new Prc);Z9(this,712,550);this.b=b;DJb(this,RIe(Ayi,Ayi));this.Ac=Byi;!!this.sc&&(H7(this).id=Byi,undefined);j=new C8b;j.tb=false;j.xb=false;j.hc=0;j.Jc&&FQ(BR(H7(j),YOg),false);p=new L0b;p.Ei(Cyi);i=X1c(LW(c,sSg),1).lastIndexOf(mNg);if(i>0){g=D9d(X1c(LW(c,sSg),1),i);p.Hi(A9d(X1c(LW(c,sSg),1),g,Dyi+g))}else{p.Hi(X1c(LW(c,sSg),1)+Dyi)}MZb(p,RIe(dxh,dxh));IAb(j,p,j.Hb.e);r=new fbc;OZb(r,OKg);r.Ac=OKg;!!r.sc&&(H7(r).id=OKg,undefined);Q7(r);IAb(j,r,j.Hb.e);o=new fbc;OZb(o,NKg);o.Ac=NKg;!!o.sc&&(H7(o).id=NKg,undefined);Q7(o);IAb(j,o,j.Hb.e);s=new fbc;MZb(s,RIe(Eyi,DAh));E8(s,Fyi);OZb(s,aLg);s.Ac=aLg;!!s.sc&&(H7(s).id=aLg,undefined);K8(s);u7(s);IAb(j,s,j.Hb.e);k=new fbc;MZb(k,RIe(Gyi,IAh));E8(k,Hyi);OZb(k,_Kg);k.Ac=_Kg;!!k.sc&&(H7(k).id=_Kg,undefined);K8(k);u7(k);IAb(j,k,j.Hb.e);n=new W_d;M6(n,new Q4e,(cSc(),cSc(),bSc));n.ad.id=Iyi;V_d(n,c.A);IAb(j,n,j.Hb.e);d=new wYb;e=new uIb(RIe(vwh,vwh),new V4e(this));q=new uIb(RIe(Fwh,Fwh),new _4e(this,s,k,c,p,r,o));fYb(d,q,d.Hb.e);fYb(d,e,d.Hb.e);CBb(this,(PJ(),MJ));BBb(this,d);Gzb(this,j,this.Hb.e);this.N=true;this.xb=true;this.r=false}
var vyi='#cropbox',zyi='#height-input',wyi='#left-input',xyi='#top-input',yyi='#width-input',Kyi='AsyncLoader4',Lyi='ImageCrop',Myi='ImageCrop$1',Nyi='ImageCrop$2',Oyi='ImageCrop$3',Pyi='ImageCrop$4',tyi='JahiaContentManagementService_Proxy.cropImage',Byi='JahiaGxtImageCrop',Dyi='_crop',uyi='cropImage',Iyi='cropbox',Jyi='failure.crop.label',Ayi='label.crop',Gyi='label.height',Eyi='label.width',syi='runCallbacks4',Hyi='stylehight',Fyi='stylewidth';_=dSc.prototype=aSc.prototype=new oQc;_.sk=function eSc(b){X1c(b,290);L4e()};_.vk=function fSc(){return bSc};_.gC=function gSc(){return Sdd};_.cM={};var bSc;_=aGd.prototype=WFd.prototype=new GH;_.gC=function bGd(){return $ed};_.kl=function fGd(){_Fd()};_.cM={};_=M4e.prototype=I4e.prototype=new dJb;_.gC=function N4e(){return ond};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_=Q4e.prototype=O4e.prototype=new GH;_.gC=function R4e(){return knd};_.cM={290:1,294:1};_=V4e.prototype=S4e.prototype=new ljb;_.ig=function W4e(b){U4e(this,X1c(b,216))};_.gC=function X4e(){return lnd};_.cM={188:1};_.b=null;_=_4e.prototype=Y4e.prototype=new ljb;_.ig=function a5e(b){$4e(this,X1c(b,216))};_.gC=function b5e(){return mnd};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=null;_.g=null;_.i=null;_.j=null;_=e5e.prototype=c5e.prototype=new Hle;_.gC=function f5e(){return nnd};_.Sl=function g5e(b){if(b!=null&&b.cM&&!!b.cM[353]){$wnd.confirm(RIe(qzh,qzh)+jah+RIe(dRh,dRh))&&K4e(this.b,this.e,this.g,this.i,this.d,this.j,this.c,true)}else{$wnd.alert(RIe(Jyi,Jyi)+jah+b.ok());RIe(Jyi,Jyi)}};_.ye=function h5e(b){pJb(this.b,null);this.b.b.dm(1)};_.cM={};_.b=null;_.c=0;_.d=0;_.e=null;_.g=null;_.i=0;_.j=0;var Sdd=w6d(B3h,lUh),$ed=w6d(R4h,Kyi),ond=w6d(Zci,Lyi),knd=w6d(Zci,Myi),lnd=w6d(Zci,Nyi),mnd=w6d(Zci,Oyi),nnd=w6d(Zci,Pyi);$entry(cGd)();