function vGd(){}
function pGd(){}
function S2e(){}
function X2e(){}
function a3e(){}
function g3e(){}
function m3e(){}
function p3e(b){this.b=b}
function o3e(b){pJb(b.b,null)}
function i3e(b,c){this.b=b;this.c=c}
function Wdg(b){KJb(new V2e(b.b.p,b.b.p._l(),b.b.b))}
function uGd(){var b;while(qGd){b=qGd;qGd=qGd.c;!qGd&&(rGd=null);Wdg(b.b)}}
function d3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function Z2e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function xGd(){sGd=new vGd;wJc((tJc(),sJc),5);!!$stats&&$stats(lKc(Qyi,Bbh,-1,-1));sGd.kl();!!$stats&&$stats(lKc(Qyi,Xgh,-1,-1))}
function c3e(b){var c,d;pJb(b.b,null);b.c.cm(RIe(KMh,KMh));c=GJe();d=new i3e(b.c,b.e);b.d?hKe(c,b.g,d):dLe(c,b.g,X1c(tZb(b.i),1),d)}
function U2e(b,c){var d;c>1?(d=SIe(Tyi,Uyi,I1c(mCd,{113:1,175:1,177:1,323:1},1,[XJg+c]))):X1c(LW(X1c(b.k.sl(0),150),qjh),174).Sd(auh)?(d=SIe(Vyi,Wyi,I1c(mCd,{113:1,175:1,177:1,323:1},1,[X1c(LW(b.s,sSg),1)]))):(d=SIe(xRh,yRh,I1c(mCd,{113:1,175:1,177:1,323:1},1,[X1c(LW(b.s,sSg),1)])));return d}
function dLe(c,d,e,g){var b,j,k,n,o;n=new sUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Vgh,evtGroup:n.b,method:Ryi,millis:(new Date).getTime(),type:Bbh});o=ISd(c);try{ASd(o.b,XJg+QRd(o,xlh));ASd(o.b,XJg+QRd(o,Syi));ASd(o.b,JPg);ASd(o.b,XJg+QRd(o,Hlh));ASd(o.b,XJg+QRd(o,ikh));WRd(o,d);ASd(o.b,XJg+QRd(o,e));k=xSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:Vgh,evtGroup:n.b,method:Ryi,millis:(new Date).getTime(),type:kkh});JSd(c,(gTd(),fTd),Ryi,n,k,g)}catch(b){b=rDd(b);if($1c(b,313)){j=b;Kle(g,j)}else throw b}}
function V2e(b,c,d){k7();var e,g,i,j,k,n,o,p,q,r,s,t;MJb.call(this);Z9(this,650,500);cLb(this.ub,Xyi);!!this.E&&PQ(EQ(this.E,o0g),Xyi);IJb(this,false);this.b=new C8b;cLb(this.b.ub,RIe(gDh,gDh));this.b.xb=false;r8(this.b,false);A8(this.b,Yyi);Tzb(this.b,new Xtc(0));Z9(this.b,650,500);t=new DMb;DAb(this.b,t);p=new DWd;q=new DWd;for(n=c.k.Ud();n.$d();){k=X1c(n._d(),150);K1c(p.d,p.e++,k);mWd(q,X1c(LW(k,Tih),1))}i=new IBb;Tzb(i,new Prc);i.hc=0;i.Jc&&FQ(BR(H7(i),YOg),false);i.xb=false;this.c=N8e(p);Z9(this.c,650,200);DAb(i,this.c);DAb(this.b,i);s=new odc;Z9(s,620,100);if(!d){DAb(this.b,new EMb(Zyi+RIe(WRh,XRh)+$yi));DAb(this.b,s)}j=p.e;iZ(this.c.I.g,new Z2e(this,c,j,i,s,d,t));if(d){o=RIe(zRh,_yi);DAb(this.b,new EMb(o));bLb(this.ub,(GRe(),ERe(),BRe))}r=new uIb(RIe($Oh,$Oh),new d3e(this,b,d,q,s,p));g=new uIb(RIe(aPh,aPh),new p3e(this));e=new wYb;e.E=(PJ(),MJ);fYb(e,r,e.Hb.e);fYb(e,g,e.Hb.e);DAb(this.b,e);BBb(this,e);this.uh(this.b,this.Hb.e)}
var fzi='620',gzi='70%',$yi=': <br />',Zyi='<br />',azi='<br /><br />',_yi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',hzi='AsyncLoader5',izi='DeleteItemWindow',jzi='DeleteItemWindow$1',kzi='DeleteItemWindow$2',lzi='DeleteItemWindow$2$1',mzi='DeleteItemWindow$3',Wyi='Do you really want to remove the selected PAGE {0}?',Uyi='Do you really want to remove the {0} selected resources?',Xyi='Informations',Ryi='JahiaContentManagementService_Proxy.markForDeletion',Yyi='JahiaGxtDeleteItem',ezi='This node is still used by:',czi='Those nodes are still used in:',Syi='markForDeletion',Tyi='message.remove.multiple.confirm',bzi='message.remove.multiple.usage',Vyi='message.remove.single.page.confirm',dzi='message.remove.single.usage',Qyi='runCallbacks5';_=vGd.prototype=pGd.prototype=new GH;_.gC=function wGd(){return bfd};_.kl=function AGd(){uGd()};_.cM={};_=V2e.prototype=S2e.prototype=new dJb;_.gC=function W2e(){return Zmd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=Z2e.prototype=X2e.prototype=new aib;_.gC=function $2e(){return Vmd};_.cg=function _2e(b){var c,d,e;c=X1c(b.d,174);d=c.Nd();e=U2e(this.d,this.e);if(d>0){e+=azi+(this.e>1?RIe(bzi,czi):RIe(dzi,ezi))}else{PAb(this.b.b,this.c);$9(this.i,fzi,gzi);if(this.g){Z9(this.b,-1,130);Z9(this.b.b,-1,130)}}CMb(this.j,e);Izb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=d3e.prototype=a3e.prototype=new ljb;_.ig=function e3e(b){c3e(this,X1c(b,216))};_.gC=function f3e(){return Xmd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=i3e.prototype=g3e.prototype=new Hle;_.gC=function j3e(){return Wmd};_.Sl=function k3e(b){this.b.bm();b.ok();zQb(RIe(xuh,yuh),b.ok())};_.ye=function l3e(b){var c;this.b.bm();c=null;$1c(this.b,354)?(c=X1c(this.b,354).d.u):$1c(this.b,355)&&(c=X1c(this.b,355));if(!!c&&uWd(this.c,X1c(LW(c.q.j,Tih),1),0)!=-1){this.b.dm(2);this.b.em(null)}else{this.b.dm(63);this.b.em(null)}};_.cM={};_.b=null;_.c=null;_=p3e.prototype=m3e.prototype=new ljb;_.ig=function q3e(b){o3e(this,X1c(b,216))};_.gC=function r3e(){return Ymd};_.cM={188:1};_.b=null;var bfd=w6d(R4h,hzi),Zmd=w6d(Zci,izi),Vmd=w6d(Zci,jzi),Xmd=w6d(Zci,kzi),Wmd=w6d(Zci,lzi),Ymd=w6d(Zci,mzi);$entry(xGd)();