function CBd(){}
function wBd(){}
function R_e(){}
function W_e(){}
function __e(){}
function f0e(){}
function l0e(){}
function h0e(b){this.b=b}
function o0e(b){this.b=b}
function n0e(b){YGb(b.b,null)}
function QWf(b){rHb(new U_e(b.b.p,b.b.p.p,b.b.b))}
function c0e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function Y_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function BBd(){var b;while(xBd){b=xBd;xBd=xBd.c;!xBd&&(yBd=null);QWf(b.b)}}
function b0e(b){var c,d;YGb(b.b,null);r4e(b.c,mEe(guh,guh));c=bFe();d=new h0e(b.c);b.d?EFe(c,b.e,d):xGe(c,b.e,a_c(mXb(b.g),1),d)}
function EBd(){zBd=new CBd;LGc((IGc(),HGc),5);!!$stats&&$stats(AHc(wai,kVg,-1,-1));zBd.Tk();!!$stats&&$stats(AHc(wai,$Zg,-1,-1))}
function T_e(b,c){var d;c>1?(d=nEe(zai,Aai,N$c(txd,{113:1,175:1,177:1,321:1},1,[Tqg+c]))):a_c(_U(a_c(b.k.$k(0),150),N0g),174).Sd(dch)?(d=nEe(Bai,Cai,N$c(txd,{113:1,175:1,177:1,321:1},1,[a_c(_U(b.s,lzg),1)]))):(d=nEe(Xyh,Yyh,N$c(txd,{113:1,175:1,177:1,321:1},1,[a_c(_U(b.s,lzg),1)])));return d}
function xGe(c,d,e,g){var b,j,k,n,o;n=new JPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:YZg,evtGroup:n.b,method:xai,millis:(new Date).getTime(),type:kVg});o=ZNd(c);try{RNd(o.b,Tqg+fNd(o,X2g));RNd(o.b,Tqg+fNd(o,yai));RNd(o.b,Gwg);RNd(o.b,Tqg+fNd(o,f3g));RNd(o.b,Tqg+fNd(o,G1g));lNd(o,d);RNd(o.b,Tqg+fNd(o,e));k=ONd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:YZg,evtGroup:n.b,method:xai,millis:(new Date).getTime(),type:I1g});$Nd(c,(xOd(),wOd),xai,n,k,g)}catch(b){b=yyd(b);if(d_c(b,311)){j=b;mhe(g,j)}else throw b}}
function U_e(b,c,d){s5();var e,g,i,j,k,n,o,p,q,r,s,t;tHb.call(this);b8(this,650,500);JIb(this.ub,Dai);!!this.E&&_O(QO(this.E,qJg),Dai);pHb(this,false);this.b=new v6b;JIb(this.b.ub,mEe(peh,peh));this.b.xb=false;y6(this.b,false);G6(this.b,Eai);Dxb(this.b,new Lrc(0));b8(this.b,650,500);t=new gKb;kyb(this.b,t);p=new URd;q=new URd;for(n=c.k.Ud();n.$d();){k=a_c(n._d(),150);P$c(p.d,p.e++,k);DRd(q,a_c(_U(k,n0g),1))}i=new pzb;Dxb(i,new opc);i.hc=0;i.Jc&&RO(NP(O5(i),Xvg),false);i.xb=false;this.c=I5e(p);b8(this.c,650,200);kyb(i,this.c);kyb(this.b,i);s=new hbc;b8(s,620,100);if(!d){kyb(this.b,new hKb(Fai+mEe(Fzh,Gzh)+Gai));kyb(this.b,s)}j=p.e;yX(this.c.I.g,new Y_e(this,c,j,i,s,d,t));if(d){o=mEe(Zyh,Hai);kyb(this.b,new hKb(o));IIb(this.ub,(MMe(),KMe(),HMe))}r=new bGb(mEe(Dwh,Dwh),new c0e(this,b,d,q,s));g=new bGb(mEe(Ewh,Ewh),new o0e(this));e=new pWb;e.E=(RH(),OH);$Vb(e,r,e.Hb.e);$Vb(e,g,e.Hb.e);kyb(this.b,e);izb(this,e);this.rh(this.b,this.Hb.e)}
var Nai='620',Oai='70%',Gai=': <br />',Fai='<br />',Iai='<br /><br />',Hai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Pai='AsyncLoader5',Qai='DeleteItemWindow',Rai='DeleteItemWindow$1',Sai='DeleteItemWindow$2',Tai='DeleteItemWindow$2$1',Uai='DeleteItemWindow$3',Cai='Do you really want to remove the selected PAGE {0}?',Aai='Do you really want to remove the {0} selected resources?',Dai='Informations',xai='JahiaContentManagementService_Proxy.markForDeletion',Eai='JahiaGxtDeleteItem',Mai='This node is still used by:',Kai='Those nodes are still used in:',yai='markForDeletion',zai='message.remove.multiple.confirm',Jai='message.remove.multiple.usage',Bai='message.remove.single.page.confirm',Lai='message.remove.single.usage',wai='runCallbacks5';_=CBd.prototype=wBd.prototype=new IF;_.gC=function DBd(){return dcd};_.Tk=function HBd(){BBd()};_.cM={};_=U_e.prototype=R_e.prototype=new MGb;_.gC=function V_e(){return okd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=Y_e.prototype=W_e.prototype=new Wfb;_.gC=function Z_e(){return kkd};_.ag=function $_e(b){var c,d,e;c=a_c(b.d,174);d=c.Nd();e=T_e(this.d,this.e);if(d>0){e+=Iai+(this.e>1?mEe(Jai,Kai):mEe(Lai,Mai))}else{wyb(this.b.b,this.c);c8(this.i,Nai,Oai);if(this.g){b8(this.b,-1,130);b8(this.b.b,-1,130)}}fKb(this.j,e);sxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=c0e.prototype=__e.prototype=new $gb;_.fg=function d0e(b){b0e(this,a_c(b,216))};_.gC=function e0e(){return mkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=h0e.prototype=f0e.prototype=new jhe;_.gC=function i0e(){return lkd};_.yl=function j0e(b){q4e(this.b);b.fk();ZNb(mEe(Ach,cRg),b.fk())};_.ye=function k0e(b){q4e(this.b);v4e(this.b,63);z4e(this.b)};_.cM={};_.b=null;_=o0e.prototype=l0e.prototype=new $gb;_.fg=function p0e(b){n0e(this,a_c(b,216))};_.gC=function q0e(){return nkd};_.cM={188:1};_.b=null;var dcd=$1d(SOh,Pai),okd=$1d(sXh,Qai),kkd=$1d(sXh,Rai),mkd=$1d(sXh,Sai),lkd=$1d(sXh,Tai),nkd=$1d(sXh,Uai);$entry(EBd)();