function vBd(){}
function pBd(){}
function i_e(){}
function n_e(){}
function s_e(){}
function y_e(){}
function E_e(){}
function A_e(b){this.b=b}
function H_e(b){this.b=b}
function G_e(b){UGb(b.b,null)}
function hWf(b){nHb(new l_e(b.b.p,b.b.p.p,b.b.b))}
function v_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function p_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function uBd(){var b;while(qBd){b=qBd;qBd=qBd.c;!qBd&&(rBd=null);hWf(b.b)}}
function u_e(b){var c,d;UGb(b.b,null);K3e(b.c,FDe(Tsh,Tsh));c=uEe();d=new A_e(b.c);b.d?XEe(c,b.e,d):QFe(c,b.e,W$c(iXb(b.g),1),d)}
function xBd(){sBd=new vBd;HGc((EGc(),DGc),5);!!$stats&&$stats(wHc(g9h,AUg,-1,-1));sBd.Wk();!!$stats&&$stats(wHc(g9h,_Yg,-1,-1))}
function k_e(b,c){var d;c>1?(d=GDe(j9h,k9h,H$c(mxd,{113:1,175:1,177:1,321:1},1,[kqg+c]))):W$c(WU(W$c(b.k.bl(0),150),y_g),174).Sd(Qah)?(d=GDe(l9h,m9h,H$c(mxd,{113:1,175:1,177:1,321:1},1,[W$c(WU(b.s,Dyg),1)]))):(d=GDe(Ixh,Jxh,H$c(mxd,{113:1,175:1,177:1,321:1},1,[W$c(WU(b.s,Dyg),1)])));return d}
function QFe(c,d,e,g){var b,j,k,n,o;n=new pPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:ZYg,evtGroup:n.b,method:h9h,millis:(new Date).getTime(),type:AUg});o=FNd(c);try{xNd(o.b,kqg+NMd(o,I1g));xNd(o.b,kqg+NMd(o,i9h));xNd(o.b,Yvg);xNd(o.b,kqg+NMd(o,S1g));xNd(o.b,kqg+NMd(o,r0g));TMd(o,d);xNd(o.b,kqg+NMd(o,e));k=uNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:ZYg,evtGroup:n.b,method:h9h,millis:(new Date).getTime(),type:t0g});GNd(c,(dOd(),cOd),h9h,n,k,g)}catch(b){b=ryd(b);if(Z$c(b,311)){j=b;Fge(g,j)}else throw b}}
function l_e(b,c,d){n5();var e,g,i,j,k,n,o,p,q,r,s,t;pHb.call(this);Y7(this,650,500);FIb(this.ub,n9h);!!this.E&&$O(PO(this.E,IIg),n9h);lHb(this,false);this.b=new r6b;FIb(this.b.ub,FDe(adh,adh));this.b.xb=false;t6(this.b,false);B6(this.b,o9h);zxb(this.b,new Hrc(0));Y7(this.b,650,500);t=new cKb;gyb(this.b,t);p=new ARd;q=new ARd;for(n=c.k.Ud();n.$d();){k=W$c(n._d(),150);J$c(p.d,p.e++,k);jRd(q,W$c(WU(k,$$g),1))}i=new lzb;zxb(i,new kpc);i.hc=0;i.Jc&&QO(MP(J5(i),mvg),false);i.xb=false;this.c=_4e(p);Y7(this.c,650,200);gyb(i,this.c);gyb(this.b,i);s=new dbc;Y7(s,620,100);if(!d){gyb(this.b,new dKb(p9h+FDe(qyh,ryh)+q9h));gyb(this.b,s)}j=p.e;tX(this.c.I.g,new p_e(this,c,j,i,s,d,t));if(d){o=FDe(Kxh,r9h);gyb(this.b,new dKb(o));EIb(this.ub,(dMe(),bMe(),$Le))}r=new ZFb(FDe(ovh,ovh),new v_e(this,b,d,q,s));g=new ZFb(FDe(pvh,pvh),new H_e(this));e=new lWb;e.E=(QH(),NH);WVb(e,r,e.Hb.e);WVb(e,g,e.Hb.e);gyb(this.b,e);ezb(this,e);this.rh(this.b,this.Hb.e)}
var x9h='620',y9h='70%',q9h=': <br />',p9h='<br />',s9h='<br /><br />',r9h='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',z9h='AsyncLoader5',A9h='DeleteItemWindow',B9h='DeleteItemWindow$1',C9h='DeleteItemWindow$2',D9h='DeleteItemWindow$2$1',E9h='DeleteItemWindow$3',m9h='Do you really want to remove the selected PAGE {0}?',k9h='Do you really want to remove the {0} selected resources?',n9h='Informations',h9h='JahiaContentManagementService_Proxy.markForDeletion',o9h='JahiaGxtDeleteItem',w9h='This node is still used by:',u9h='Those nodes are still used in:',i9h='markForDeletion',j9h='message.remove.multiple.confirm',t9h='message.remove.multiple.usage',l9h='message.remove.single.page.confirm',v9h='message.remove.single.usage',g9h='runCallbacks5';_=vBd.prototype=pBd.prototype=new HF;_.gC=function wBd(){return acd};_.Wk=function ABd(){uBd()};_.cM={};_=l_e.prototype=i_e.prototype=new IGb;_.gC=function m_e(){return hkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=p_e.prototype=n_e.prototype=new Rfb;_.gC=function q_e(){return dkd};_.ag=function r_e(b){var c,d,e;c=W$c(b.d,174);d=c.Nd();e=k_e(this.d,this.e);if(d>0){e+=s9h+(this.e>1?FDe(t9h,u9h):FDe(v9h,w9h))}else{syb(this.b.b,this.c);Z7(this.i,x9h,y9h);if(this.g){Y7(this.b,-1,130);Y7(this.b.b,-1,130)}}bKb(this.j,e);oxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=v_e.prototype=s_e.prototype=new Vgb;_.fg=function w_e(b){u_e(this,W$c(b,216))};_.gC=function x_e(){return fkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=A_e.prototype=y_e.prototype=new Cge;_.gC=function B_e(){return ekd};_.Bl=function C_e(b){J3e(this.b);b.fk();VNb(FDe(lbh,sQg),b.fk())};_.ye=function D_e(b){J3e(this.b);O3e(this.b,63);S3e(this.b)};_.cM={};_.b=null;_=H_e.prototype=E_e.prototype=new Vgb;_.fg=function I_e(b){G_e(this,W$c(b,216))};_.gC=function J_e(){return gkd};_.cM={188:1};_.b=null;var acd=r1d(GNh,z9h),hkd=r1d(cWh,A9h),dkd=r1d(cWh,B9h),fkd=r1d(cWh,C9h),ekd=r1d(cWh,D9h),gkd=r1d(cWh,E9h);$entry(xBd)();