function sGd(){}
function mGd(){}
function m3e(){}
function b3e(){}
function g3e(){}
function s3e(){}
function Y2e(){}
function v3e(b){this.b=b}
function u3e(b){rJb(b.b,null)}
function o3e(b,c){this.b=b;this.c=c}
function aeg(b){MJb(new _2e(b.b.p,b.b.p._l(),b.b.b))}
function rGd(){var b;while(nGd){b=nGd;nGd=nGd.c;!nGd&&(oGd=null);aeg(b.b)}}
function j3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function d3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function uGd(){pGd=new sGd;yJc((vJc(),uJc),5);!!$stats&&$stats(nKc($yi,Gbh,-1,-1));pGd.kl();!!$stats&&$stats(nKc($yi,dhh,-1,-1))}
function i3e(b){var c,d;rJb(b.b,null);b.c.cm(XIe(SMh,SMh));c=MJe();d=new o3e(b.c,b.e);b.d?nKe(c,b.g,d):jLe(c,b.g,S1c(vZb(b.i),1),d)}
function $2e(b,c){var d;c>1?(d=YIe(bzi,czi,D1c(jCd,{113:1,175:1,177:1,323:1},1,[bKg+c]))):S1c(NW(S1c(b.k.sl(0),150),yjh),174).Sd(iuh)?(d=YIe(dzi,ezi,D1c(jCd,{113:1,175:1,177:1,323:1},1,[S1c(NW(b.s,ySg),1)]))):(d=YIe(FRh,GRh,D1c(jCd,{113:1,175:1,177:1,323:1},1,[S1c(NW(b.s,ySg),1)])));return d}
function jLe(c,d,e,g){var b,j,k,n,o;n=new pUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:bhh,evtGroup:n.b,method:_yi,millis:(new Date).getTime(),type:Gbh});o=FSd(c);try{xSd(o.b,bKg+NRd(o,Flh));xSd(o.b,bKg+NRd(o,azi));xSd(o.b,PPg);xSd(o.b,bKg+NRd(o,Plh));xSd(o.b,bKg+NRd(o,qkh));TRd(o,d);xSd(o.b,bKg+NRd(o,e));k=uSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:bhh,evtGroup:n.b,method:_yi,millis:(new Date).getTime(),type:skh});GSd(c,(dTd(),cTd),_yi,n,k,g)}catch(b){b=oDd(b);if(V1c(b,313)){j=b;Qle(g,j)}else throw b}}
function _2e(b,c,d){m7();var e,g,i,j,k,n,o,p,q,r,s,t;OJb.call(this);_9(this,650,500);eLb(this.ub,fzi);!!this.E&&RQ(GQ(this.E,u0g),fzi);KJb(this,false);this.b=new E8b;eLb(this.b.ub,XIe(oDh,oDh));this.b.xb=false;t8(this.b,false);C8(this.b,gzi);Vzb(this.b,new Ztc(0));_9(this.b,650,500);t=new FMb;FAb(this.b,t);p=new AWd;q=new AWd;for(n=c.k.Ud();n.$d();){k=S1c(n._d(),150);F1c(p.d,p.e++,k);jWd(q,S1c(NW(k,_ih),1))}i=new KBb;Vzb(i,new Rrc);i.hc=0;i.Jc&&HQ(DR(J7(i),cPg),false);i.xb=false;this.c=T8e(p);_9(this.c,650,200);FAb(i,this.c);FAb(this.b,i);s=new qdc;_9(s,620,100);if(!d){FAb(this.b,new GMb(hzi+XIe(cSh,dSh)+izi));FAb(this.b,s)}j=p.e;kZ(this.c.I.g,new d3e(this,c,j,i,s,d,t));if(d){o=XIe(HRh,jzi);FAb(this.b,new GMb(o));dLb(this.ub,(MRe(),KRe(),HRe))}r=new wIb(XIe(gPh,gPh),new j3e(this,b,d,q,s,p));g=new wIb(XIe(iPh,iPh),new v3e(this));e=new yYb;e.E=(RJ(),OJ);hYb(e,r,e.Hb.e);hYb(e,g,e.Hb.e);FAb(this.b,e);DBb(this,e);this.uh(this.b,this.Hb.e)}
var pzi='620',qzi='70%',izi=': <br />',hzi='<br />',kzi='<br /><br />',jzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',rzi='AsyncLoader5',szi='DeleteItemWindow',tzi='DeleteItemWindow$1',uzi='DeleteItemWindow$2',vzi='DeleteItemWindow$2$1',wzi='DeleteItemWindow$3',ezi='Do you really want to remove the selected PAGE {0}?',czi='Do you really want to remove the {0} selected resources?',fzi='Informations',_yi='JahiaContentManagementService_Proxy.markForDeletion',gzi='JahiaGxtDeleteItem',ozi='This node is still used by:',mzi='Those nodes are still used in:',azi='markForDeletion',bzi='message.remove.multiple.confirm',lzi='message.remove.multiple.usage',dzi='message.remove.single.page.confirm',nzi='message.remove.single.usage',$yi='runCallbacks5';_=sGd.prototype=mGd.prototype=new IH;_.gC=function tGd(){return Yed};_.kl=function xGd(){rGd()};_.cM={};_=_2e.prototype=Y2e.prototype=new fJb;_.gC=function a3e(){return Wmd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=d3e.prototype=b3e.prototype=new cib;_.gC=function e3e(){return Smd};_.cg=function f3e(b){var c,d,e;c=S1c(b.d,174);d=c.Nd();e=$2e(this.d,this.e);if(d>0){e+=kzi+(this.e>1?XIe(lzi,mzi):XIe(nzi,ozi))}else{RAb(this.b.b,this.c);aab(this.i,pzi,qzi);if(this.g){_9(this.b,-1,130);_9(this.b.b,-1,130)}}EMb(this.j,e);Kzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=j3e.prototype=g3e.prototype=new njb;_.ig=function k3e(b){i3e(this,S1c(b,216))};_.gC=function l3e(){return Umd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=o3e.prototype=m3e.prototype=new Nle;_.gC=function p3e(){return Tmd};_.Sl=function q3e(b){this.b.bm();b.ok();BQb(XIe(Fuh,Guh),b.ok())};_.ye=function r3e(b){var c;this.b.bm();c=null;V1c(this.b,354)?(c=S1c(this.b,354).d.u):V1c(this.b,355)&&(c=S1c(this.b,355));if(!!c&&rWd(this.c,S1c(NW(c.q.j,_ih),1),0)!=-1){this.b.dm(2);this.b.em(null)}else{this.b.dm(63);this.b.em(null)}};_.cM={};_.b=null;_.c=null;_=v3e.prototype=s3e.prototype=new njb;_.ig=function w3e(b){u3e(this,S1c(b,216))};_.gC=function x3e(){return Vmd};_.cM={188:1};_.b=null;var Yed=C6d(Z4h,rzi),Wmd=C6d(hdi,szi),Smd=C6d(hdi,tzi),Umd=C6d(hdi,uzi),Tmd=C6d(hdi,vzi),Vmd=C6d(hdi,wzi);$entry(uGd)();