function _Ad(){}
function VAd(){}
function c_e(){}
function h_e(){}
function m_e(){}
function s_e(){}
function y_e(){}
function u_e(b){this.b=b}
function B_e(b){this.b=b}
function A_e(b){WGb(b.b,null)}
function bWf(b){pHb(new f_e(b.b.p,b.b.p.p,b.b.b))}
function p_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function j_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function $Ad(){var b;while(WAd){b=WAd;WAd=WAd.c;!WAd&&(XAd=null);bWf(b.b)}}
function o_e(b){var c,d;WGb(b.b,null);E3e(b.c,zDe(dth,dth));c=oEe();d=new u_e(b.c);b.d?REe(c,b.e,d):KFe(c,b.e,B$c(kXb(b.g),1),d)}
function bBd(){YAd=new _Ad;IGc((FGc(),EGc),5);!!$stats&&$stats(xHc(r9h,xUg,-1,-1));YAd.Tk();!!$stats&&$stats(xHc(r9h,lZg,-1,-1))}
function e_e(b,c){var d;c>1?(d=ADe(u9h,v9h,m$c(Swd,{113:1,175:1,177:1,321:1},1,[eqg+c]))):B$c(ZU(B$c(b.k.$k(0),150),K_g),174).Sd(abh)?(d=ADe(w9h,x9h,m$c(Swd,{113:1,175:1,177:1,321:1},1,[B$c(ZU(b.s,yyg),1)]))):(d=ADe(Uxh,Vxh,m$c(Swd,{113:1,175:1,177:1,321:1},1,[B$c(ZU(b.s,yyg),1)])));return d}
function KFe(c,d,e,g){var b,j,k,n,o;n=new fPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:jZg,evtGroup:n.b,method:s9h,millis:(new Date).getTime(),type:xUg});o=vNd(c);try{nNd(o.b,eqg+DMd(o,U1g));nNd(o.b,eqg+DMd(o,t9h));nNd(o.b,Tvg);nNd(o.b,eqg+DMd(o,c2g));nNd(o.b,eqg+DMd(o,D0g));JMd(o,d);nNd(o.b,eqg+DMd(o,e));k=kNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:jZg,evtGroup:n.b,method:s9h,millis:(new Date).getTime(),type:F0g});wNd(c,(VNd(),UNd),s9h,n,k,g)}catch(b){b=Xxd(b);if(E$c(b,311)){j=b;zge(g,j)}else throw b}}
function f_e(b,c,d){q5();var e,g,i,j,k,n,o,p,q,r,s,t;rHb.call(this);_7(this,650,500);HIb(this.ub,y9h);!!this.E&&ZO(OO(this.E,DIg),y9h);nHb(this,false);this.b=new t6b;HIb(this.b.ub,zDe(mdh,mdh));this.b.xb=false;w6(this.b,false);E6(this.b,z9h);Bxb(this.b,new Jrc(0));_7(this.b,650,500);t=new eKb;iyb(this.b,t);p=new qRd;q=new qRd;for(n=c.k.Ud();n.$d();){k=B$c(n._d(),150);o$c(p.d,p.e++,k);_Qd(q,B$c(ZU(k,k_g),1))}i=new nzb;Bxb(i,new mpc);i.hc=0;i.Jc&&PO(LP(M5(i),ivg),false);i.xb=false;this.c=V4e(p);_7(this.c,650,200);iyb(i,this.c);iyb(this.b,i);s=new fbc;_7(s,620,100);if(!d){iyb(this.b,new fKb(A9h+zDe(Cyh,Dyh)+B9h));iyb(this.b,s)}j=p.e;wX(this.c.I.g,new j_e(this,c,j,i,s,d,t));if(d){o=zDe(Wxh,C9h);iyb(this.b,new fKb(o));GIb(this.ub,(ZLe(),XLe(),ULe))}r=new _Fb(zDe(Avh,Avh),new p_e(this,b,d,q,s));g=new _Fb(zDe(Bvh,Bvh),new B_e(this));e=new nWb;e.E=(PH(),MH);YVb(e,r,e.Hb.e);YVb(e,g,e.Hb.e);iyb(this.b,e);gzb(this,e);this.rh(this.b,this.Hb.e)}
var I9h='620',J9h='70%',B9h=': <br />',A9h='<br />',D9h='<br /><br />',C9h='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',K9h='AsyncLoader5',L9h='DeleteItemWindow',M9h='DeleteItemWindow$1',N9h='DeleteItemWindow$2',O9h='DeleteItemWindow$2$1',P9h='DeleteItemWindow$3',x9h='Do you really want to remove the selected PAGE {0}?',v9h='Do you really want to remove the {0} selected resources?',y9h='Informations',s9h='JahiaContentManagementService_Proxy.markForDeletion',z9h='JahiaGxtDeleteItem',H9h='This node is still used by:',F9h='Those nodes are still used in:',t9h='markForDeletion',u9h='message.remove.multiple.confirm',E9h='message.remove.multiple.usage',w9h='message.remove.single.page.confirm',G9h='message.remove.single.usage',r9h='runCallbacks5';_=_Ad.prototype=VAd.prototype=new GF;_.gC=function aBd(){return Ebd};_.Tk=function eBd(){$Ad()};_.cM={};_=f_e.prototype=c_e.prototype=new KGb;_.gC=function g_e(){return Njd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=j_e.prototype=h_e.prototype=new Ufb;_.gC=function k_e(){return Jjd};_.ag=function l_e(b){var c,d,e;c=B$c(b.d,174);d=c.Nd();e=e_e(this.d,this.e);if(d>0){e+=D9h+(this.e>1?zDe(E9h,F9h):zDe(G9h,H9h))}else{uyb(this.b.b,this.c);a8(this.i,I9h,J9h);if(this.g){_7(this.b,-1,130);_7(this.b.b,-1,130)}}dKb(this.j,e);qxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=p_e.prototype=m_e.prototype=new Ygb;_.fg=function q_e(b){o_e(this,B$c(b,216))};_.gC=function r_e(){return Ljd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=u_e.prototype=s_e.prototype=new wge;_.gC=function v_e(){return Kjd};_.yl=function w_e(b){D3e(this.b);b.fk();XNb(zDe(xbh,pQg),b.fk())};_.ye=function x_e(b){D3e(this.b);I3e(this.b,63);M3e(this.b)};_.cM={};_.b=null;_=B_e.prototype=y_e.prototype=new Ygb;_.fg=function C_e(b){A_e(this,B$c(b,216))};_.gC=function D_e(){return Mjd};_.cM={188:1};_.b=null;var Ebd=l1d(PNh,K9h),Njd=l1d(nWh,L9h),Jjd=l1d(nWh,M9h),Ljd=l1d(nWh,N9h),Kjd=l1d(nWh,O9h),Mjd=l1d(nWh,P9h);$entry(bBd)();