function XGd(){}
function RGd(){}
function q3e(){}
function v3e(){}
function A3e(){}
function G3e(){}
function M3e(){}
function P3e(b){this.b=b}
function O3e(b){sJb(b.b,null)}
function I3e(b,c){this.b=b;this.c=c}
function ueg(b){NJb(new t3e(b.b.p,b.b.p.dm(),b.b.b))}
function WGd(){var b;while(SGd){b=SGd;SGd=SGd.c;!SGd&&(TGd=null);ueg(b.b)}}
function D3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function x3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function ZGd(){UGd=new XGd;zJc((wJc(),vJc),5);!!$stats&&$stats(oKc(wzi,$bh,-1,-1));UGd.ol();!!$stats&&$stats(oKc(wzi,Ahh,-1,-1))}
function C3e(b){var c,d;sJb(b.b,null);b.c.gm(pJe(nNh,nNh));c=eKe();d=new I3e(b.c,b.e);b.d?HKe(c,b.g,d):DLe(c,b.g,u2c(wZb(b.i),1),d)}
function s3e(b,c){var d;c>1?(d=qJe(zzi,Azi,f2c(OCd,{113:1,175:1,177:1,323:1},1,[vKg+c]))):u2c(OW(u2c(b.k.wl(0),150),Vjh),174).Sd(Fuh)?(d=qJe(Bzi,Czi,f2c(OCd,{113:1,175:1,177:1,323:1},1,[u2c(OW(b.s,SSg),1)]))):(d=qJe(aSh,bSh,f2c(OCd,{113:1,175:1,177:1,323:1},1,[u2c(OW(b.s,SSg),1)])));return d}
function DLe(c,d,e,g){var b,j,k,n,o;n=new SUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:yhh,evtGroup:n.b,method:xzi,millis:(new Date).getTime(),type:$bh});o=gTd(c);try{$Sd(o.b,vKg+oSd(o,amh));$Sd(o.b,vKg+oSd(o,yzi));$Sd(o.b,hQg);$Sd(o.b,vKg+oSd(o,kmh));$Sd(o.b,vKg+oSd(o,Nkh));uSd(o,d);$Sd(o.b,vKg+oSd(o,e));k=XSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:yhh,evtGroup:n.b,method:xzi,millis:(new Date).getTime(),type:Pkh});hTd(c,(GTd(),FTd),xzi,n,k,g)}catch(b){b=TDd(b);if(x2c(b,313)){j=b;ime(g,j)}else throw b}}
function t3e(b,c,d){n7();var e,g,i,j,k,n,o,p,q,r,s,t;PJb.call(this);aab(this,650,500);fLb(this.ub,Dzi);!!this.E&&SQ(HQ(this.E,O0g),Dzi);LJb(this,false);this.b=new F8b;fLb(this.b.ub,pJe(LDh,LDh));this.b.xb=false;u8(this.b,false);D8(this.b,Ezi);Wzb(this.b,new $tc(0));aab(this.b,650,500);t=new GMb;GAb(this.b,t);p=new bXd;q=new bXd;for(n=c.k.Ud();n.$d();){k=u2c(n._d(),150);h2c(p.d,p.e++,k);MWd(q,u2c(OW(k,wjh),1))}i=new LBb;Wzb(i,new Src);i.hc=0;i.Jc&&IQ(ER(K7(i),wPg),false);i.xb=false;this.c=l9e(p);aab(this.c,650,200);GAb(i,this.c);GAb(this.b,i);s=new rdc;aab(s,620,100);if(!d){GAb(this.b,new HMb(Fzi+pJe(zSh,ASh)+Gzi));GAb(this.b,s)}j=p.e;lZ(this.c.I.g,new x3e(this,c,j,i,s,d,t));if(d){o=pJe(cSh,Hzi);GAb(this.b,new HMb(o));eLb(this.ub,(eSe(),cSe(),_Re))}r=new xIb(pJe(DPh,DPh),new D3e(this,b,d,q,s,p));g=new xIb(pJe(FPh,FPh),new P3e(this));e=new zYb;e.E=(SJ(),PJ);iYb(e,r,e.Hb.e);iYb(e,g,e.Hb.e);GAb(this.b,e);EBb(this,e);this.uh(this.b,this.Hb.e)}
var Nzi='620',Ozi='70%',Gzi=': <br />',Fzi='<br />',Izi='<br /><br />',Hzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Pzi='AsyncLoader5',Qzi='DeleteItemWindow',Rzi='DeleteItemWindow$1',Szi='DeleteItemWindow$2',Tzi='DeleteItemWindow$2$1',Uzi='DeleteItemWindow$3',Czi='Do you really want to remove the selected PAGE {0}?',Azi='Do you really want to remove the {0} selected resources?',Dzi='Informations',xzi='JahiaContentManagementService_Proxy.markForDeletion',Ezi='JahiaGxtDeleteItem',Mzi='This node is still used by:',Kzi='Those nodes are still used in:',yzi='markForDeletion',zzi='message.remove.multiple.confirm',Jzi='message.remove.multiple.usage',Bzi='message.remove.single.page.confirm',Lzi='message.remove.single.usage',wzi='runCallbacks5';_=XGd.prototype=RGd.prototype=new JH;_.gC=function YGd(){return Dfd};_.ol=function aHd(){WGd()};_.cM={};_=t3e.prototype=q3e.prototype=new gJb;_.gC=function u3e(){return znd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=x3e.prototype=v3e.prototype=new dib;_.gC=function y3e(){return vnd};_.cg=function z3e(b){var c,d,e;c=u2c(b.d,174);d=c.Nd();e=s3e(this.d,this.e);if(d>0){e+=Izi+(this.e>1?pJe(Jzi,Kzi):pJe(Lzi,Mzi))}else{SAb(this.b.b,this.c);bab(this.i,Nzi,Ozi);if(this.g){aab(this.b,-1,130);aab(this.b.b,-1,130)}}FMb(this.j,e);Lzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=D3e.prototype=A3e.prototype=new ojb;_.ig=function E3e(b){C3e(this,u2c(b,216))};_.gC=function F3e(){return xnd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=I3e.prototype=G3e.prototype=new fme;_.gC=function J3e(){return wnd};_.Wl=function K3e(b){this.b.fm();b.ok();CQb(pJe(avh,bvh),b.ok())};_.ye=function L3e(b){var c;this.b.fm();c=null;x2c(this.b,354)?(c=u2c(this.b,354).d.u):x2c(this.b,355)&&(c=u2c(this.b,355));if(!!c&&UWd(this.c,u2c(OW(c.q.j,wjh),1),0)!=-1){this.b.hm(2);this.b.im(null)}else{this.b.hm(63);this.b.im(null)}};_.cM={};_.b=null;_.c=null;_=P3e.prototype=M3e.prototype=new ojb;_.ig=function Q3e(b){O3e(this,u2c(b,216))};_.gC=function R3e(){return ynd};_.cM={188:1};_.b=null;var Dfd=W6d(x5h,Pzi),znd=W6d(Fdi,Qzi),vnd=W6d(Fdi,Rzi),xnd=W6d(Fdi,Szi),wnd=W6d(Fdi,Tzi),ynd=W6d(Fdi,Uzi);$entry(ZGd)();