function qGd(){}
function kGd(){}
function k3e(){}
function e3e(){}
function q3e(){}
function W2e(){}
function _2e(){}
function t3e(b){this.b=b}
function s3e(b){rJb(b.b,null)}
function m3e(b,c){this.b=b;this.c=c}
function $dg(b){MJb(new Z2e(b.b.p,b.b.p.$l(),b.b.b))}
function pGd(){var b;while(lGd){b=lGd;lGd=lGd.c;!lGd&&(mGd=null);$dg(b.b)}}
function h3e(b,c,d,e,g,i){this.b=b;this.c=c;this.d=d;this.g=e;this.i=g;this.e=i}
function b3e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function sGd(){nGd=new qGd;yJc((vJc(),uJc),5);!!$stats&&$stats(nKc(czi,Ebh,-1,-1));nGd.jl();!!$stats&&$stats(nKc(czi,fhh,-1,-1))}
function g3e(b){var c,d;rJb(b.b,null);b.c.bm(VIe(UMh,UMh));c=KJe();d=new m3e(b.c,b.e);b.d?lKe(c,b.g,d):hLe(c,b.g,Q1c(vZb(b.i),1),d)}
function Y2e(b,c){var d;c>1?(d=WIe(fzi,gzi,B1c(hCd,{113:1,175:1,177:1,323:1},1,[_Jg+c]))):Q1c(NW(Q1c(b.k.rl(0),150),Ajh),174).Sd(kuh)?(d=WIe(hzi,izi,B1c(hCd,{113:1,175:1,177:1,323:1},1,[Q1c(NW(b.s,uSg),1)]))):(d=WIe(HRh,IRh,B1c(hCd,{113:1,175:1,177:1,323:1},1,[Q1c(NW(b.s,uSg),1)])));return d}
function hLe(c,d,e,g){var b,j,k,n,o;n=new nUd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:dhh,evtGroup:n.b,method:dzi,millis:(new Date).getTime(),type:Ebh});o=DSd(c);try{vSd(o.b,_Jg+LRd(o,Hlh));vSd(o.b,_Jg+LRd(o,ezi));vSd(o.b,NPg);vSd(o.b,_Jg+LRd(o,Rlh));vSd(o.b,_Jg+LRd(o,skh));RRd(o,d);vSd(o.b,_Jg+LRd(o,e));k=sSd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:dhh,evtGroup:n.b,method:dzi,millis:(new Date).getTime(),type:ukh});ESd(c,(bTd(),aTd),dzi,n,k,g)}catch(b){b=mDd(b);if(T1c(b,313)){j=b;Ole(g,j)}else throw b}}
function Z2e(b,c,d){m7();var e,g,i,j,k,n,o,p,q,r,s,t;OJb.call(this);_9(this,650,500);eLb(this.ub,jzi);!!this.E&&RQ(GQ(this.E,s0g),jzi);KJb(this,false);this.b=new E8b;eLb(this.b.ub,VIe(rDh,rDh));this.b.xb=false;t8(this.b,false);C8(this.b,kzi);Vzb(this.b,new Ztc(0));_9(this.b,650,500);t=new FMb;FAb(this.b,t);p=new yWd;q=new yWd;for(n=c.k.Ud();n.$d();){k=Q1c(n._d(),150);D1c(p.d,p.e++,k);hWd(q,Q1c(NW(k,bjh),1))}i=new KBb;Vzb(i,new Rrc);i.hc=0;i.Jc&&HQ(DR(J7(i),aPg),false);i.xb=false;this.c=R8e(p);_9(this.c,650,200);FAb(i,this.c);FAb(this.b,i);s=new qdc;_9(s,620,100);if(!d){FAb(this.b,new GMb(lzi+VIe(eSh,fSh)+mzi));FAb(this.b,s)}j=p.e;kZ(this.c.I.g,new b3e(this,c,j,i,s,d,t));if(d){o=VIe(JRh,nzi);FAb(this.b,new GMb(o));dLb(this.ub,(KRe(),IRe(),FRe))}r=new wIb(VIe(iPh,iPh),new h3e(this,b,d,q,s,p));g=new wIb(VIe(kPh,kPh),new t3e(this));e=new yYb;e.E=(RJ(),OJ);hYb(e,r,e.Hb.e);hYb(e,g,e.Hb.e);FAb(this.b,e);DBb(this,e);this.uh(this.b,this.Hb.e)}
var tzi='620',uzi='70%',mzi=': <br />',lzi='<br />',ozi='<br /><br />',nzi='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',vzi='AsyncLoader5',wzi='DeleteItemWindow',xzi='DeleteItemWindow$1',yzi='DeleteItemWindow$2',zzi='DeleteItemWindow$2$1',Azi='DeleteItemWindow$3',izi='Do you really want to remove the selected PAGE {0}?',gzi='Do you really want to remove the {0} selected resources?',jzi='Informations',dzi='JahiaContentManagementService_Proxy.markForDeletion',kzi='JahiaGxtDeleteItem',szi='This node is still used by:',qzi='Those nodes are still used in:',ezi='markForDeletion',fzi='message.remove.multiple.confirm',pzi='message.remove.multiple.usage',hzi='message.remove.single.page.confirm',rzi='message.remove.single.usage',czi='runCallbacks5';_=qGd.prototype=kGd.prototype=new IH;_.gC=function rGd(){return Wed};_.jl=function vGd(){pGd()};_.cM={};_=Z2e.prototype=W2e.prototype=new fJb;_.gC=function $2e(){return Umd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,75:1,79:1,98:1,99:1,105:1,108:1,109:1,270:1};_.b=null;_.c=null;_=b3e.prototype=_2e.prototype=new cib;_.gC=function c3e(){return Qmd};_.cg=function d3e(b){var c,d,e;c=Q1c(b.d,174);d=c.Nd();e=Y2e(this.d,this.e);if(d>0){e+=ozi+(this.e>1?VIe(pzi,qzi):VIe(rzi,szi))}else{RAb(this.b.b,this.c);aab(this.i,tzi,uzi);if(this.g){_9(this.b,-1,130);_9(this.b.b,-1,130)}}EMb(this.j,e);Kzb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=h3e.prototype=e3e.prototype=new njb;_.ig=function i3e(b){g3e(this,Q1c(b,216))};_.gC=function j3e(){return Smd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_.i=null;_=m3e.prototype=k3e.prototype=new Lle;_.gC=function n3e(){return Rmd};_.Rl=function o3e(b){this.b.am();b.ok();BQb(VIe(Huh,Iuh),b.ok())};_.ye=function p3e(b){var c;this.b.am();c=null;T1c(this.b,354)?(c=Q1c(this.b,354).d.u):T1c(this.b,355)&&(c=Q1c(this.b,355));if(!!c&&pWd(this.c,Q1c(NW(c.q.j,bjh),1),0)!=-1){this.b.cm(2);this.b.dm(null)}else{this.b.cm(63);this.b.dm(null)}};_.cM={};_.b=null;_.c=null;_=t3e.prototype=q3e.prototype=new njb;_.ig=function u3e(b){s3e(this,Q1c(b,216))};_.gC=function v3e(){return Tmd};_.cM={188:1};_.b=null;var Wed=A6d(_4h,vzi),Umd=A6d(jdi,wzi),Qmd=A6d(jdi,xzi),Smd=A6d(jdi,yzi),Rmd=A6d(jdi,zzi),Tmd=A6d(jdi,Azi);$entry(sGd)();