function dCd(){}
function ZBd(){}
function s0e(){}
function x0e(){}
function C0e(){}
function I0e(){}
function O0e(){}
function K0e(b){this.b=b}
function R0e(b){this.b=b}
function Q0e(b){ZGb(b.b,null)}
function rXf(b){sHb(new v0e(b.b.p,b.b.p.p,b.b.b))}
function F0e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function z0e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function cCd(){var b;while($Bd){b=$Bd;$Bd=$Bd.c;!$Bd&&(_Bd=null);rXf(b.b)}}
function E0e(b){var c,d;ZGb(b.b,null);U4e(b.c,PEe(Pvh,Pvh));c=EFe();d=new K0e(b.c);b.d?fGe(c,b.e,d):$Ge(c,b.e,C_c(nXb(b.g),1),d)}
function fCd(){aCd=new dCd;MGc((JGc(),IGc),5);!!$stats&&$stats(BHc(gci,IVg,-1,-1));aCd.bl();!!$stats&&$stats(BHc(gci,C_g,-1,-1))}
function u0e(b,c){var d;c>1?(d=QEe(jci,kci,n_c(Wxd,{113:1,175:1,177:1,321:1},1,[urg+c]))):C_c(aV(C_c(b.k.il(0),150),p2g),174).Sd(Hdh)?(d=QEe(lci,mci,n_c(Wxd,{113:1,175:1,177:1,321:1},1,[C_c(aV(b.s,Qzg),1)]))):(d=QEe(GAh,HAh,n_c(Wxd,{113:1,175:1,177:1,321:1},1,[C_c(aV(b.s,Qzg),1)])));return d}
function $Ge(c,d,e,g){var b,j,k,n,o;n=new kQd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:A_g,evtGroup:n.b,method:hci,millis:(new Date).getTime(),type:IVg});o=AOd(c);try{sOd(o.b,urg+INd(o,z4g));sOd(o.b,urg+INd(o,ici));sOd(o.b,hxg);sOd(o.b,urg+INd(o,J4g));sOd(o.b,urg+INd(o,i3g));ONd(o,d);sOd(o.b,urg+INd(o,e));k=pOd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:A_g,evtGroup:n.b,method:hci,millis:(new Date).getTime(),type:k3g});BOd(c,($Od(),ZOd),hci,n,k,g)}catch(b){b=_yd(b);if(F_c(b,311)){j=b;Phe(g,j)}else throw b}}
function v0e(b,c,d){t5();var e,g,i,j,k,n,o,p,q,r,s,t;uHb.call(this);c8(this,650,500);KIb(this.ub,nci);!!this.E&&aP(RO(this.E,NJg),nci);qHb(this,false);this.b=new w6b;KIb(this.b.ub,PEe(Vfh,Vfh));this.b.xb=false;z6(this.b,false);H6(this.b,oci);Exb(this.b,new Mrc(0));c8(this.b,650,500);t=new hKb;lyb(this.b,t);p=new vSd;q=new vSd;for(n=c.k.Ud();n.$d();){k=C_c(n._d(),150);p_c(p.d,p.e++,k);eSd(q,C_c(aV(k,R1g),1))}i=new qzb;Exb(i,new ppc);i.hc=0;i.Jc&&SO(OP(P5(i),ywg),false);i.xb=false;this.c=j6e(p);c8(this.c,650,200);lyb(i,this.c);lyb(this.b,i);s=new ibc;c8(s,620,100);if(!d){lyb(this.b,new iKb(pci+PEe(oBh,pBh)+qci));lyb(this.b,s)}j=p.e;zX(this.c.I.g,new z0e(this,c,j,i,s,d,t));if(d){o=PEe(IAh,rci);lyb(this.b,new iKb(o));JIb(this.ub,(nNe(),lNe(),iNe))}r=new cGb(PEe(kyh,kyh),new F0e(this,b,d,q,s));g=new cGb(PEe(myh,myh),new R0e(this));e=new qWb;e.E=(SH(),PH);_Vb(e,r,e.Hb.e);_Vb(e,g,e.Hb.e);lyb(this.b,e);jzb(this,e);this.rh(this.b,this.Hb.e)}
var xci='620',yci='70%',qci=': <br />',pci='<br />',sci='<br /><br />',rci='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',zci='AsyncLoader5',Aci='DeleteItemWindow',Bci='DeleteItemWindow$1',Cci='DeleteItemWindow$2',Dci='DeleteItemWindow$2$1',Eci='DeleteItemWindow$3',mci='Do you really want to remove the selected PAGE {0}?',kci='Do you really want to remove the {0} selected resources?',nci='Informations',hci='JahiaContentManagementService_Proxy.markForDeletion',oci='JahiaGxtDeleteItem',wci='This node is still used by:',uci='Those nodes are still used in:',ici='markForDeletion',jci='message.remove.multiple.confirm',tci='message.remove.multiple.usage',lci='message.remove.single.page.confirm',vci='message.remove.single.usage',gci='runCallbacks5';_=dCd.prototype=ZBd.prototype=new JF;_.gC=function eCd(){return Gcd};_.bl=function iCd(){cCd()};_.cM={};_=v0e.prototype=s0e.prototype=new NGb;_.gC=function w0e(){return Rkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=z0e.prototype=x0e.prototype=new Xfb;_.gC=function A0e(){return Nkd};_.ag=function B0e(b){var c,d,e;c=C_c(b.d,174);d=c.Nd();e=u0e(this.d,this.e);if(d>0){e+=sci+(this.e>1?PEe(tci,uci):PEe(vci,wci))}else{xyb(this.b.b,this.c);d8(this.i,xci,yci);if(this.g){c8(this.b,-1,130);c8(this.b.b,-1,130)}}gKb(this.j,e);txb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=F0e.prototype=C0e.prototype=new _gb;_.fg=function G0e(b){E0e(this,C_c(b,216))};_.gC=function H0e(){return Pkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=K0e.prototype=I0e.prototype=new Mhe;_.gC=function L0e(){return Okd};_.Il=function M0e(b){T4e(this.b);b.fk();$Nb(PEe(ceh,deh),b.fk())};_.ye=function N0e(b){T4e(this.b);Y4e(this.b,63);a5e(this.b)};_.cM={};_.b=null;_=R0e.prototype=O0e.prototype=new _gb;_.fg=function S0e(b){Q0e(this,C_c(b,216))};_.gC=function T0e(){return Qkd};_.cM={188:1};_.b=null;var Gcd=B2d(CQh,zci),Rkd=B2d(cZh,Aci),Nkd=B2d(cZh,Bci),Pkd=B2d(cZh,Cci),Okd=B2d(cZh,Dci),Qkd=B2d(cZh,Eci);$entry(fCd)();