function vBd(){}
function pBd(){}
function t_e(){}
function y_e(){}
function D_e(){}
function J_e(){}
function P_e(){}
function L_e(b){this.b=b}
function S_e(b){this.b=b}
function R_e(b){UGb(b.b,null)}
function sWf(b){nHb(new w_e(b.b.p,b.b.p.p,b.b.b))}
function G_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function A_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function uBd(){var b;while(qBd){b=qBd;qBd=qBd.c;!qBd&&(rBd=null);sWf(b.b)}}
function F_e(b){var c,d;UGb(b.b,null);V3e(b.c,QDe(_th,_th));c=FEe();d=new L_e(b.c);b.d?gFe(c,b.e,d):_Fe(c,b.e,W$c(iXb(b.g),1),d)}
function xBd(){sBd=new vBd;HGc((EGc(),DGc),5);!!$stats&&$stats(wHc(qai,HUg,-1,-1));sBd.bl();!!$stats&&$stats(wHc(qai,f$g,-1,-1))}
function v_e(b,c){var d;c>1?(d=RDe(tai,uai,H$c(mxd,{113:1,175:1,177:1,321:1},1,[vqg+c]))):W$c(WU(W$c(b.k.il(0),150),E0g),174).Sd(Wbh)?(d=RDe(vai,wai,H$c(mxd,{113:1,175:1,177:1,321:1},1,[W$c(WU(b.s,Syg),1)]))):(d=RDe(Syh,Tyh,H$c(mxd,{113:1,175:1,177:1,321:1},1,[W$c(WU(b.s,Syg),1)])));return d}
function _Fe(c,d,e,g){var b,j,k,n,o;n=new rPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:d$g,evtGroup:n.b,method:rai,millis:(new Date).getTime(),type:HUg});o=HNd(c);try{zNd(o.b,vqg+PMd(o,O2g));zNd(o.b,vqg+PMd(o,sai));zNd(o.b,hwg);zNd(o.b,vqg+PMd(o,Y2g));zNd(o.b,vqg+PMd(o,x1g));VMd(o,d);zNd(o.b,vqg+PMd(o,e));k=wNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:d$g,evtGroup:n.b,method:rai,millis:(new Date).getTime(),type:z1g});INd(c,(fOd(),eOd),rai,n,k,g)}catch(b){b=ryd(b);if(Z$c(b,311)){j=b;Qge(g,j)}else throw b}}
function w_e(b,c,d){n5();var e,g,i,j,k,n,o,p,q,r,s,t;pHb.call(this);Y7(this,650,500);FIb(this.ub,xai);!!this.E&&$O(PO(this.E,NIg),xai);lHb(this,false);this.b=new r6b;FIb(this.b.ub,QDe(heh,heh));this.b.xb=false;t6(this.b,false);B6(this.b,yai);zxb(this.b,new Hrc(0));Y7(this.b,650,500);t=new cKb;gyb(this.b,t);p=new CRd;q=new CRd;for(n=c.k.Ud();n.$d();){k=W$c(n._d(),150);J$c(p.d,p.e++,k);lRd(q,W$c(WU(k,e0g),1))}i=new lzb;zxb(i,new kpc);i.hc=0;i.Jc&&QO(MP(J5(i),xvg),false);i.xb=false;this.c=k5e(p);Y7(this.c,650,200);gyb(i,this.c);gyb(this.b,i);s=new dbc;Y7(s,620,100);if(!d){gyb(this.b,new dKb(zai+QDe(Azh,Bzh)+Aai));gyb(this.b,s)}j=p.e;tX(this.c.I.g,new A_e(this,c,j,i,s,d,t));if(d){o=QDe(Uyh,Bai);gyb(this.b,new dKb(o));EIb(this.ub,(oMe(),mMe(),jMe))}r=new ZFb(QDe(wwh,wwh),new G_e(this,b,d,q,s));g=new ZFb(QDe(ywh,ywh),new S_e(this));e=new lWb;e.E=(QH(),NH);WVb(e,r,e.Hb.e);WVb(e,g,e.Hb.e);gyb(this.b,e);ezb(this,e);this.rh(this.b,this.Hb.e)}
var Hai='620',Iai='70%',Aai=': <br />',zai='<br />',Cai='<br /><br />',Bai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Jai='AsyncLoader5',Kai='DeleteItemWindow',Lai='DeleteItemWindow$1',Mai='DeleteItemWindow$2',Nai='DeleteItemWindow$2$1',Oai='DeleteItemWindow$3',wai='Do you really want to remove the selected PAGE {0}?',uai='Do you really want to remove the {0} selected resources?',xai='Informations',rai='JahiaContentManagementService_Proxy.markForDeletion',yai='JahiaGxtDeleteItem',Gai='This node is still used by:',Eai='Those nodes are still used in:',sai='markForDeletion',tai='message.remove.multiple.confirm',Dai='message.remove.multiple.usage',vai='message.remove.single.page.confirm',Fai='message.remove.single.usage',qai='runCallbacks5';_=vBd.prototype=pBd.prototype=new HF;_.gC=function wBd(){return $bd};_.bl=function ABd(){uBd()};_.cM={};_=w_e.prototype=t_e.prototype=new IGb;_.gC=function x_e(){return hkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=A_e.prototype=y_e.prototype=new Rfb;_.gC=function B_e(){return dkd};_.ag=function C_e(b){var c,d,e;c=W$c(b.d,174);d=c.Nd();e=v_e(this.d,this.e);if(d>0){e+=Cai+(this.e>1?QDe(Dai,Eai):QDe(Fai,Gai))}else{syb(this.b.b,this.c);Z7(this.i,Hai,Iai);if(this.g){Y7(this.b,-1,130);Y7(this.b.b,-1,130)}}bKb(this.j,e);oxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=G_e.prototype=D_e.prototype=new Vgb;_.fg=function H_e(b){F_e(this,W$c(b,216))};_.gC=function I_e(){return fkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=L_e.prototype=J_e.prototype=new Nge;_.gC=function M_e(){return ekd};_.Il=function N_e(b){U3e(this.b);b.fk();VNb(QDe(rch,yQg),b.fk())};_.ye=function O_e(b){U3e(this.b);Z3e(this.b,63);b4e(this.b)};_.cM={};_.b=null;_=S_e.prototype=P_e.prototype=new Vgb;_.fg=function T_e(b){R_e(this,W$c(b,216))};_.gC=function U_e(){return gkd};_.cM={188:1};_.b=null;var $bd=C1d(OOh,Jai),hkd=C1d(mXh,Kai),dkd=C1d(mXh,Lai),fkd=C1d(mXh,Mai),ekd=C1d(mXh,Nai),gkd=C1d(mXh,Oai);$entry(xBd)();