function $Bd(){}
function UBd(){}
function N_e(){}
function S_e(){}
function X_e(){}
function b0e(){}
function h0e(){}
function d0e(b){this.b=b}
function k0e(b){this.b=b}
function j0e(b){VGb(b.b,null)}
function MWf(b){oHb(new Q_e(b.b.p,b.b.p.p,b.b.b))}
function $_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function U_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function ZBd(){var b;while(VBd){b=VBd;VBd=VBd.c;!VBd&&(WBd=null);MWf(b.b)}}
function Z_e(b){var c,d;VGb(b.b,null);n4e(b.c,iEe(wuh,wuh));c=ZEe();d=new d0e(b.c);b.d?AFe(c,b.e,d):tGe(c,b.e,y_c(jXb(b.g),1),d)}
function aCd(){XBd=new $Bd;IGc((FGc(),EGc),5);!!$stats&&$stats(xHc(Oai,_Ug,-1,-1));XBd.fl();!!$stats&&$stats(xHc(Oai,C$g,-1,-1))}
function P_e(b,c){var d;c>1?(d=jEe(Rai,Sai,j_c(Rxd,{113:1,175:1,177:1,321:1},1,[Pqg+c]))):y_c(XU(y_c(b.k.ml(0),150),_0g),174).Sd(rch)?(d=jEe(Tai,Uai,j_c(Rxd,{113:1,175:1,177:1,321:1},1,[y_c(XU(b.s,kzg),1)]))):(d=jEe(nzh,ozh,j_c(Rxd,{113:1,175:1,177:1,321:1},1,[y_c(XU(b.s,kzg),1)])));return d}
function tGe(c,d,e,g){var b,j,k,n,o;n=new UPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:A$g,evtGroup:n.b,method:Pai,millis:(new Date).getTime(),type:_Ug});o=iOd(c);try{aOd(o.b,Pqg+qNd(o,j3g));aOd(o.b,Pqg+qNd(o,Qai));aOd(o.b,Bwg);aOd(o.b,Pqg+qNd(o,t3g));aOd(o.b,Pqg+qNd(o,U1g));wNd(o,d);aOd(o.b,Pqg+qNd(o,e));k=ZNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:A$g,evtGroup:n.b,method:Pai,millis:(new Date).getTime(),type:W1g});jOd(c,(IOd(),HOd),Pai,n,k,g)}catch(b){b=Wyd(b);if(B_c(b,311)){j=b;ihe(g,j)}else throw b}}
function Q_e(b,c,d){o5();var e,g,i,j,k,n,o,p,q,r,s,t;qHb.call(this);Z7(this,650,500);GIb(this.ub,Vai);!!this.E&&_O(QO(this.E,fJg),Vai);mHb(this,false);this.b=new s6b;GIb(this.b.ub,iEe(Eeh,Eeh));this.b.xb=false;u6(this.b,false);C6(this.b,Wai);Axb(this.b,new Irc(0));Z7(this.b,650,500);t=new dKb;hyb(this.b,t);p=new dSd;q=new dSd;for(n=c.k.Ud();n.$d();){k=y_c(n._d(),150);l_c(p.d,p.e++,k);ORd(q,y_c(XU(k,B0g),1))}i=new mzb;Axb(i,new lpc);i.hc=0;i.Jc&&RO(NP(K5(i),Rvg),false);i.xb=false;this.c=E5e(p);Z7(this.c,650,200);hyb(i,this.c);hyb(this.b,i);s=new ebc;Z7(s,620,100);if(!d){hyb(this.b,new eKb(Xai+iEe(Xzh,Yzh)+Yai));hyb(this.b,s)}j=p.e;uX(this.c.I.g,new U_e(this,c,j,i,s,d,t));if(d){o=iEe(pzh,Zai);hyb(this.b,new eKb(o));FIb(this.ub,(IMe(),GMe(),DMe))}r=new $Fb(iEe(Twh,Twh),new $_e(this,b,d,q,s));g=new $Fb(iEe(Vwh,Vwh),new k0e(this));e=new mWb;e.E=(RH(),OH);XVb(e,r,e.Hb.e);XVb(e,g,e.Hb.e);hyb(this.b,e);fzb(this,e);this.rh(this.b,this.Hb.e)}
var dbi='620',ebi='70%',Yai=': <br />',Xai='<br />',$ai='<br /><br />',Zai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',fbi='AsyncLoader5',gbi='DeleteItemWindow',hbi='DeleteItemWindow$1',ibi='DeleteItemWindow$2',jbi='DeleteItemWindow$2$1',kbi='DeleteItemWindow$3',Uai='Do you really want to remove the selected PAGE {0}?',Sai='Do you really want to remove the {0} selected resources?',Vai='Informations',Pai='JahiaContentManagementService_Proxy.markForDeletion',Wai='JahiaGxtDeleteItem',cbi='This node is still used by:',abi='Those nodes are still used in:',Qai='markForDeletion',Rai='message.remove.multiple.confirm',_ai='message.remove.multiple.usage',Tai='message.remove.single.page.confirm',bbi='message.remove.single.usage',Oai='runCallbacks5';_=$Bd.prototype=UBd.prototype=new IF;_.gC=function _Bd(){return Fcd};_.fl=function dCd(){ZBd()};_.cM={};_=Q_e.prototype=N_e.prototype=new JGb;_.gC=function R_e(){return Mkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=U_e.prototype=S_e.prototype=new Sfb;_.gC=function V_e(){return Ikd};_.ag=function W_e(b){var c,d,e;c=y_c(b.d,174);d=c.Nd();e=P_e(this.d,this.e);if(d>0){e+=$ai+(this.e>1?iEe(_ai,abi):iEe(bbi,cbi))}else{tyb(this.b.b,this.c);$7(this.i,dbi,ebi);if(this.g){Z7(this.b,-1,130);Z7(this.b.b,-1,130)}}cKb(this.j,e);pxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=$_e.prototype=X_e.prototype=new Wgb;_.fg=function __e(b){Z_e(this,y_c(b,216))};_.gC=function a0e(){return Kkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=d0e.prototype=b0e.prototype=new fhe;_.gC=function e0e(){return Jkd};_.Ml=function f0e(b){m4e(this.b);b.fk();WNb(iEe(Och,SQg),b.fk())};_.ye=function g0e(b){m4e(this.b);r4e(this.b,63);v4e(this.b)};_.cM={};_.b=null;_=k0e.prototype=h0e.prototype=new Wgb;_.fg=function l0e(b){j0e(this,y_c(b,216))};_.gC=function m0e(){return Lkd};_.cM={188:1};_.b=null;var Fcd=W1d(mPh,fbi),Mkd=W1d(KXh,gbi),Ikd=W1d(KXh,hbi),Kkd=W1d(KXh,ibi),Jkd=W1d(KXh,jbi),Lkd=W1d(KXh,kbi);$entry(aCd)();