function xBd(){}
function rBd(){}
function r_e(){}
function m_e(){}
function w_e(){}
function C_e(){}
function I_e(){}
function E_e(b){this.b=b}
function L_e(b){this.b=b}
function K_e(b){SGb(b.b,null)}
function lWf(b){lHb(new p_e(b.b.p,b.b.p.p,b.b.b))}
function z_e(b,c,d,e,g){this.b=b;this.c=c;this.d=d;this.e=e;this.g=g}
function t_e(b,c,d,e,g,i,j){this.b=b;this.d=c;this.e=d;this.c=e;this.i=g;this.g=i;this.j=j}
function wBd(){var b;while(sBd){b=sBd;sBd=sBd.c;!sBd&&(tBd=null);lWf(b.b)}}
function zBd(){uBd=new xBd;FGc((CGc(),BGc),5);!!$stats&&$stats(uHc(fai,BUg,-1,-1));uBd.bl();!!$stats&&$stats(uHc(fai,YZg,-1,-1))}
function y_e(b){var c,d;SGb(b.b,null);O3e(b.c,JDe(Sth,Sth));c=yEe();d=new E_e(b.c);b.d?_Ee(c,b.e,d):UFe(c,b.e,$$c(gXb(b.g),1),d)}
function o_e(b,c){var d;c>1?(d=KDe(iai,jai,L$c(oxd,{113:1,175:1,177:1,321:1},1,[oqg+c]))):$$c(UU($$c(b.k.il(0),150),v0g),174).Sd(Nbh)?(d=KDe(kai,lai,L$c(oxd,{113:1,175:1,177:1,321:1},1,[$$c(UU(b.s,Lyg),1)]))):(d=KDe(Jyh,Kyh,L$c(oxd,{113:1,175:1,177:1,321:1},1,[$$c(UU(b.s,Lyg),1)])));return d}
function UFe(c,d,e,g){var b,j,k,n,o;n=new tPd;!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:WZg,evtGroup:n.b,method:gai,millis:(new Date).getTime(),type:BUg});o=JNd(c);try{BNd(o.b,oqg+RMd(o,F2g));BNd(o.b,oqg+RMd(o,hai));BNd(o.b,awg);BNd(o.b,oqg+RMd(o,P2g));BNd(o.b,oqg+RMd(o,o1g));XMd(o,d);BNd(o.b,oqg+RMd(o,e));k=yNd(o);!!$stats&&$stats({moduleName:$moduleName,sessionId:$sessionId,subSystem:WZg,evtGroup:n.b,method:gai,millis:(new Date).getTime(),type:q1g});KNd(c,(hOd(),gOd),gai,n,k,g)}catch(b){b=tyd(b);if(b_c(b,311)){j=b;Jge(g,j)}else throw b}}
function p_e(b,c,d){l5();var e,g,i,j,k,n,o,p,q,r,s,t;nHb.call(this);W7(this,650,500);DIb(this.ub,mai);!!this.E&&YO(NO(this.E,GIg),mai);jHb(this,false);this.b=new p6b;DIb(this.b.ub,JDe($dh,$dh));this.b.xb=false;r6(this.b,false);z6(this.b,nai);xxb(this.b,new Frc(0));W7(this.b,650,500);t=new aKb;eyb(this.b,t);p=new ERd;q=new ERd;for(n=c.k.Ud();n.$d();){k=$$c(n._d(),150);N$c(p.d,p.e++,k);nRd(q,$$c(UU(k,X_g),1))}i=new jzb;xxb(i,new ipc);i.hc=0;i.Jc&&OO(KP(H5(i),qvg),false);i.xb=false;this.c=d5e(p);W7(this.c,650,200);eyb(i,this.c);eyb(this.b,i);s=new bbc;W7(s,620,100);if(!d){eyb(this.b,new bKb(oai+JDe(rzh,szh)+pai));eyb(this.b,s)}j=p.e;rX(this.c.I.g,new t_e(this,c,j,i,s,d,t));if(d){o=JDe(Lyh,qai);eyb(this.b,new bKb(o));CIb(this.ub,(hMe(),fMe(),cMe))}r=new XFb(JDe(nwh,nwh),new z_e(this,b,d,q,s));g=new XFb(JDe(pwh,pwh),new L_e(this));e=new jWb;e.E=(OH(),LH);UVb(e,r,e.Hb.e);UVb(e,g,e.Hb.e);eyb(this.b,e);czb(this,e);this.rh(this.b,this.Hb.e)}
var wai='620',xai='70%',pai=': <br />',oai='<br />',rai='<br /><br />',qai='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',yai='AsyncLoader5',zai='DeleteItemWindow',Aai='DeleteItemWindow$1',Bai='DeleteItemWindow$2',Cai='DeleteItemWindow$2$1',Dai='DeleteItemWindow$3',lai='Do you really want to remove the selected PAGE {0}?',jai='Do you really want to remove the {0} selected resources?',mai='Informations',gai='JahiaContentManagementService_Proxy.markForDeletion',nai='JahiaGxtDeleteItem',vai='This node is still used by:',tai='Those nodes are still used in:',hai='markForDeletion',iai='message.remove.multiple.confirm',sai='message.remove.multiple.usage',kai='message.remove.single.page.confirm',uai='message.remove.single.usage',fai='runCallbacks5';_=xBd.prototype=rBd.prototype=new FF;_.gC=function yBd(){return ccd};_.bl=function CBd(){wBd()};_.cM={};_=p_e.prototype=m_e.prototype=new GGb;_.gC=function q_e(){return jkd};_.cM={3:1,4:1,8:1,17:1,18:1,24:1,76:1,80:1,98:1,99:1,105:1,108:1,109:1,269:1};_.b=null;_.c=null;_=t_e.prototype=r_e.prototype=new Pfb;_.gC=function u_e(){return fkd};_.ag=function v_e(b){var c,d,e;c=$$c(b.d,174);d=c.Nd();e=o_e(this.d,this.e);if(d>0){e+=rai+(this.e>1?JDe(sai,tai):JDe(uai,vai))}else{qyb(this.b.b,this.c);X7(this.i,wai,xai);if(this.g){W7(this.b,-1,130);W7(this.b.b,-1,130)}}_Jb(this.j,e);mxb(this.b.b,false)};_.cM={188:1};_.b=null;_.c=null;_.d=null;_.e=0;_.g=false;_.i=null;_.j=null;_=z_e.prototype=w_e.prototype=new Tgb;_.fg=function A_e(b){y_e(this,$$c(b,216))};_.gC=function B_e(){return hkd};_.cM={188:1};_.b=null;_.c=null;_.d=false;_.e=null;_.g=null;_=E_e.prototype=C_e.prototype=new Gge;_.gC=function F_e(){return gkd};_.Il=function G_e(b){N3e(this.b);b.fk();TNb(JDe(ich,sQg),b.fk())};_.ye=function H_e(b){N3e(this.b);S3e(this.b,63);W3e(this.b)};_.cM={};_.b=null;_=L_e.prototype=I_e.prototype=new Tgb;_.fg=function M_e(b){K_e(this,$$c(b,216))};_.gC=function N_e(){return ikd};_.cM={188:1};_.b=null;var ccd=v1d(FOh,yai),jkd=v1d(bXh,zai),fkd=v1d(bXh,Aai),hkd=v1d(bXh,Bai),gkd=v1d(bXh,Cai),ikd=v1d(bXh,Dai);$entry(zBd)();